In [1]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from lib.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float64

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [3]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

TypeError: load_all_tracks() got an unexpected keyword argument 'penality_factors'

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [ ]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]

,username,id,affinity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
0,jaslkh,75rqqKvzJCGv2oq9C4yFDt,1.00,0.630,0.374,0.2270,0.8610,0.000075,0.2940,0.3730,104.955,-9.007,196426,2023,63
1,jaslkh,2FYGZDfsAnNsrm1gVbyKnG,0.98,0.827,0.768,0.2650,0.7900,0.000024,0.4970,0.7340,99.988,-5.702,137533,2022,70
2,jaslkh,4kroNlz8BTfswE4M0i3YCh,0.96,0.583,0.297,0.4060,0.8790,0.000000,0.1270,0.2910,124.279,-11.273,162906,2022,61
3,jaslkh,2N3YZ075lq9z1ObaAiX6l1,0.94,0.651,0.327,0.4020,0.9280,0.000000,0.2250,0.5510,135.325,-10.070,89749,2022,54
4,jaslkh,2SiAcexM2p1yX6joESbehd,0.92,0.555,0.634,0.2730,0.1290,0.000002,0.1880,0.5550,170.228,-5.522,174044,2023,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12318,dany,4GRMPDD3V6rM2BlmRdYCUJ,0.10,0.491,0.699,0.0924,0.1620,0.864000,0.1050,0.0762,130.325,-10.500,214000,2022,41
12319,dany,17Xof0GRZZfS7ZgjUJ27pH,0.08,0.271,0.503,0.0314,0.7500,0.000102,0.0941,0.0742,127.960,-4.142,241821,2020,50
12320,dany,2Rd4eJ4KwXQQn2sMSToyUM,0.06,0.319,0.236,0.0318,0.8980,0.000016,0.2720,0.2540,162.351,-9.644,156091,2021,6
12321,dany,4fPBB44eDH71YohayI4eKV,0.04,0.630,0.908,0.0326,0.0238,0.592000,0.1160,0.9680,120.522,-2.420,189226,2006,75
12322,dany,2obi4sPO32ZkIiNwejVLRq,0.02,0.317,0.547,0.0333,0.1490,0.000005,0.3850,0.2940,139.752,-8.122,194173,2000,37

In [ ]:
# df_matrix_mf = pd.read_csv(os.path.join(data_path.DATA_PATH, "artificial_data.csv"), index_col=0)

In [ ]:
df_matrix_mf["affinity"] *= 1

In [ ]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity", device=device, dtype=dtype)
R = matrix_mf.R
R.to(device)
R.shape

torch.Size([8, 923])

In [ ]:
alpha = matrix_mf.compute_alpha().item()
R *= alpha
alpha

10.527777671813965

In [ ]:
R

tensor([[0.0000, 0.0000, 6.5272,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 8.8433],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [4.6322, 6.3167, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 9.6856, 0.0000, 0.0000]],
       device='mps:0')

In [ ]:
num_latent_factors = 3
lmf = LogisticMatrixFactorization(
    counts=R,
    num_factors=num_latent_factors,
    reg_param=0.01,
    device=device,
    dtype=dtype,
)
lmf.to(device)

num_epochs = 100
lmf.train_model(
    num_epochs=num_epochs,
    learning_rate=1,
    log_interval=1,
    tqdm=False
)

Epoch: 1, log-likelihood: 8083.0674, MPR: 0.1860
Epoch: 2, log-likelihood: 7206.9624, MPR: 0.1969
Epoch: 3, log-likelihood: 5633.9463, MPR: 0.1064
Epoch: 4, log-likelihood: 4922.1699, MPR: 0.0939
Epoch: 5, log-likelihood: 4365.6475, MPR: 0.0840
Epoch: 6, log-likelihood: 4044.5720, MPR: 0.0754
Epoch: 7, log-likelihood: 3835.4778, MPR: 0.0706
Epoch: 8, log-likelihood: 3688.9722, MPR: 0.0676
Epoch: 9, log-likelihood: 3579.4253, MPR: 0.0642
Epoch: 10, log-likelihood: 3496.1040, MPR: 0.0626
Epoch: 11, log-likelihood: 3431.9084, MPR: 0.0611
Epoch: 12, log-likelihood: 3399.6892, MPR: 0.0606
Epoch: 13, log-likelihood: 3340.1677, MPR: 0.0593
Epoch: 14, log-likelihood: 3282.5676, MPR: 0.0581
Epoch: 15, log-likelihood: 3222.8381, MPR: 0.0581
Epoch: 16, log-likelihood: 3169.9709, MPR: 0.0567
Epoch: 17, log-likelihood: 3122.5405, MPR: 0.0574
Epoch: 18, log-likelihood: 3080.5771, MPR: 0.0556
Epoch: 19, log-likelihood: 3041.4014, MPR: 0.0563
Epoch: 20, log-likelihood: 3011.2158, MPR: 0.0550
Epoch: 21, log-likelihood: 2982.5981, MPR: 0.0554
Epoch: 22, log-likelihood: 2960.9290, MPR: 0.0545
Epoch: 23, log-likelihood: 2938.4939, MPR: 0.0548
Epoch: 24, log-likelihood: 2922.8616, MPR: 0.0541
Epoch: 25, log-likelihood: 2907.2141, MPR: 0.0543
Epoch: 26, log-likelihood: 2899.2859, MPR: 0.0541
Epoch: 27, log-likelihood: 2891.4270, MPR: 0.0542
Epoch: 28, log-likelihood: 2892.4607, MPR: 0.0543
Epoch: 29, log-likelihood: 2888.3198, MPR: 0.0542
Epoch: 30, log-likelihood: 2893.2361, MPR: 0.0546
Epoch: 31, log-likelihood: 2884.8750, MPR: 0.0541
Epoch: 32, log-likelihood: 2877.8357, MPR: 0.0546
Epoch: 33, log-likelihood: 2866.6851, MPR: 0.0538
Epoch: 34, log-likelihood: 2849.2444, MPR: 0.0542
Epoch: 35, log-likelihood: 2833.2900, MPR: 0.0531
Epoch: 36, log-likelihood: 2817.5845, MPR: 0.0532
Epoch: 37, log-likelihood: 2806.1189, MPR: 0.0521
Epoch: 38, log-likelihood: 2796.7954, MPR: 0.0525
Epoch: 39, log-likelihood: 2789.0017, MPR: 0.0516
Epoch: 40, log-likelihood: 2782.9902, MPR: 0.0524
Epoch: 41, log-likelihood: 2778.6521, MPR: 0.0517
Epoch: 42, log-likelihood: 2778.2966, MPR: 0.0525
Epoch: 43, log-likelihood: 2786.8242, MPR: 0.0519
Epoch: 44, log-likelihood: 2799.4011, MPR: 0.0526
Epoch: 45, log-likelihood: 2780.9968, MPR: 0.0518
Epoch: 46, log-likelihood: 2802.4395, MPR: 0.0527
Epoch: 47, log-likelihood: 2930.7769, MPR: 0.0521
Epoch: 48, log-likelihood: 2838.8730, MPR: 0.0526
Epoch: 49, log-likelihood: 2959.9514, MPR: 0.0525
Epoch: 50, log-likelihood: 2803.0171, MPR: 0.0528
Epoch: 51, log-likelihood: 2824.0271, MPR: 0.0522
Epoch: 52, log-likelihood: 2803.9768, MPR: 0.0528
Epoch: 53, log-likelihood: 2824.5046, MPR: 0.0521
Epoch: 54, log-likelihood: 2796.1531, MPR: 0.0525
Epoch: 55, log-likelihood: 2806.6592, MPR: 0.0518
Epoch: 56, log-likelihood: 2781.3677, MPR: 0.0522
Epoch: 57, log-likelihood: 2785.8650, MPR: 0.0515
Epoch: 58, log-likelihood: 2763.6960, MPR: 0.0519
Epoch: 59, log-likelihood: 2761.0417, MPR: 0.0512
Epoch: 60, log-likelihood: 2746.4294, MPR: 0.0516
Epoch: 61, log-likelihood: 2743.7581, MPR: 0.0508
Epoch: 62, log-likelihood: 2735.5737, MPR: 0.0513
Epoch: 63, log-likelihood: 2734.9111, MPR: 0.0504
Epoch: 64, log-likelihood: 2730.2646, MPR: 0.0510
Epoch: 65, log-likelihood: 2728.5654, MPR: 0.0502
Epoch: 66, log-likelihood: 2725.0706, MPR: 0.0508
Epoch: 67, log-likelihood: 2728.6846, MPR: 0.0505
Epoch: 68, log-likelihood: 2732.9187, MPR: 0.0508
Epoch: 69, log-likelihood: 2747.8953, MPR: 0.0508
Epoch: 70, log-likelihood: 2736.4053, MPR: 0.0512
Epoch: 71, log-likelihood: 2737.0706, MPR: 0.0507
Epoch: 72, log-likelihood: 2731.0034, MPR: 0.0514
Epoch: 73, log-likelihood: 2728.8369, MPR: 0.0507
Epoch: 74, log-likelihood: 2729.5051, MPR: 0.0515
Epoch: 75, log-likelihood: 2724.5461, MPR: 0.0506
Epoch: 76, log-likelihood: 2724.2434, MPR: 0.0515
Epoch: 77, log-likelihood: 2718.8718, MPR: 0.0505
Epoch: 78, log-likelihood: 2717.5723, MPR: 0.0514
Epoch: 79, log-likelihood: 2713.6379, MPR: 0.0505
Epoch: 80, log-likelihood: 2712.5659, MPR: 0.0513
Epoch: 81, log-likelihood: 2709.4714, MPR: 0.0503
Epoch: 82, log-likelihood: 2708.5571, MPR: 0.0510
Epoch: 83, log-likelihood: 2706.3606, MPR: 0.0499
Epoch: 84, log-likelihood: 2707.0881, MPR: 0.0506
Epoch: 85, log-likelihood: 2706.0693, MPR: 0.0497
Epoch: 86, log-likelihood: 2706.6138, MPR: 0.0507
Epoch: 87, log-likelihood: 2704.8972, MPR: 0.0499
Epoch: 88, log-likelihood: 2704.4050, MPR: 0.0507
Epoch: 89, log-likelihood: 2701.8977, MPR: 0.0499
Epoch: 90, log-likelihood: 2701.0278, MPR: 0.0506
Epoch: 91, log-likelihood: 2698.3896, MPR: 0.0499
Epoch: 92, log-likelihood: 2697.7524, MPR: 0.0504
Epoch: 93, log-likelihood: 2695.8879, MPR: 0.0497
Epoch: 94, log-likelihood: 2696.4663, MPR: 0.0502
Epoch: 95, log-likelihood: 2697.3279, MPR: 0.0495
Epoch: 96, log-likelihood: 2702.8621, MPR: 0.0500
Epoch: 97, log-likelihood: 2712.0605, MPR: 0.0494
Epoch: 98, log-likelihood: 2727.5574, MPR: 0.0499
Epoch: 99, log-likelihood: 2740.3735, MPR: 0.0494
Epoch: 100, log-likelihood: 2746.1548, MPR: 0.0503

In [ ]:
lmf.save("models", "lmf")

In [ ]:
px.line(x=range(len(lmf.losses)), y=lmf.losses.cpu(), title="Loss").show()
px.line(x=range(len(lmf.mpr_history)), y=lmf.mpr_history.cpu(), title="MPRS").show()

In [ ]:
user_id = matrix_mf.usernames_to_ids(["paul"])[0]
print(user_id)

# Get the top 10 recommendations for the user
top_10_ids, top_10_ids_scores = lmf.recommend(user_id, top_k=20, filter_user_items=True)

# Get the top 10 recommendations for the user
matrix_mf.item_ids_to_df(top_10_ids)

7

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
11,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162929,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/7y...,https://api.spotify.com/v1/tracks/7y1r8U18JSN9...,7y1r8U18JSN93zZARYKfhT,...,medium_term,0.78,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
12,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,194543,False,{'isrc': 'USSM12301258'},{'spotify': 'https://open.spotify.com/track/60...,https://api.spotify.com/v1/tracks/609E1JCInJnc...,609E1JCInJncactoMmkDon,...,medium_term,0.76,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
18,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,127733,False,{'isrc': 'GBCBS6732267'},{'spotify': 'https://open.spotify.com/track/56...,https://api.spotify.com/v1/tracks/560OsnDa7tps...,560OsnDa7tpsK2B0krVlOP,...,medium_term,0.64,jaslkh,1968,"[pop, english, rock, rock, rock]",NaT,NaN,NaN,NaN,NaN
21,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,272533,False,{'isrc': 'USIR10311862'},{'spotify': 'https://open.spotify.com/track/0x...,https://api.spotify.com/v1/tracks/0xmjwnQ3FNE6...,0xmjwnQ3FNE6HuWCt2nHdZ,...,medium_term,0.58,jaslkh,2003,"[pop, pop, pop]",NaT,NaN,NaN,NaN,NaN
35,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,179379,True,{'isrc': 'USUG12203930'},{'spotify': 'https://open.spotify.com/track/70...,https://api.spotify.com/v1/tracks/70msjvZ6xw9e...,70msjvZ6xw9eGcjBPI5osG,...,medium_term,0.30,jaslkh,2022,"[rnb, pop]",NaT,NaN,NaN,NaN,NaN
40,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,194087,False,{'isrc': 'USUM71900764'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2Fxmhks0bxGS...,2Fxmhks0bxGSBdJ92vM42m,...,medium_term,0.20,jaslkh,2019,"[pop, pop]",NaT,NaN,NaN,NaN,NaN
54,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,206728,True,{'isrc': 'USUG12203928'},{'spotify': 'https://open.spotify.com/track/6P...,https://api.spotify.com/v1/tracks/6PFyd6Gmp2LZ...,6PFyd6Gmp2LZHI1IpkZGgy,...,short_term,0.92,jaslkh,2022,"[rnb, pop]",NaT,NaN,NaN,NaN,NaN
55,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,179379,True,{'isrc': 'USUG12203930'},{'spotify': 'https://open.spotify.com/track/70...,https://api.spotify.com/v1/tracks/70msjvZ6xw9e...,70msjvZ6xw9eGcjBPI5osG,...,short_term,0.90,jaslkh,2022,"[rnb, pop]",NaT,NaN,NaN,NaN,NaN
57,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,272533,False,{'isrc': 'USIR10311862'},{'spotify': 'https://open.spotify.com/track/0x...,https://api.spotify.com/v1/tracks/0xmjwnQ3FNE6...,0xmjwnQ3FNE6HuWCt2nHdZ,...,short_term,0.86,jaslkh,2003,"[pop, pop, pop]",NaT,NaN,NaN,NaN,NaN
58,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,95000,False,{'isrc': 'USQY51792135'},{'spotify': 'https://open.spotify.com/track/15...,https://api.spotify.com/v1/tracks/15z5xDY6UAjE...,15z5xDY6UAjEiWoMXhTK3Q,...,short_term,0.84,jaslkh,2017,"[indie, lofi]",NaT,NaN,NaN,NaN,NaN
68,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,194087,False,{'isrc': 'USUM71900764'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2Fxmhks0bxGS...,2Fxmhks0bxGSBdJ92vM42m,...,short_term,0.64,jaslkh,2019,"[pop, pop]",NaT,NaN,NaN,NaN,NaN
69,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,210005,False,{'isrc': 'USUM72013019'},{'spotify': 'https://open.spotify.com/track/3Y...,https://api.spotify.com/v1/tracks/3YUMWmx8EJq0...,3YUMWmx8EJq0DurfuIwoGh,...,short_term,0.62,jaslkh,2021,"[pop, pop]",NaT,NaN,NaN,NaN,NaN
85,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,127733,False,{'isrc': 'GBCBS6732267'},{'spotify': 'https://open.spotify.com/track/56...,https://api.spotify.com/v1/tracks/560OsnDa7tps...,560OsnDa7tpsK2B0krVlOP,...,short_term,0.30,jaslkh,1968,"[pop, english, rock, rock, rock]",NaT,NaN,NaN,NaN,NaN
95,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162929,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/7y...,https://api.spotify.com/v1/tracks/7y1r8U18JSN9...,7y1r8U18JSN93zZARYKfhT,...,short_term,0.10,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
100,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,183083,False,{'isrc': 'ES5702000376'},{'spotify': 'https://open.spotify.com/track/2o...,https://api.spotify.com/v1/tracks/2oVYnyDY1NA9...,2oVYnyDY1NA9SmJrxXhyWd,...,long_term,1.00,jaslkh,2020,[spanish],NaT,NaN,NaN,NaN,NaN
103,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,214613,False,{'isrc': 'USWD12112917'},{'spotify': 'https://open.spotify.com/track/5r...,https://api.spotify.com/v1/tracks/5rohUzwEoRsU...,5rohUzwEoRsUvAA1Bf3DLo,...,long_term,0.94,jaslkh,2021,"[pop, spanish, reggaeton, reggaeton colombiano...",NaT,NaN,NaN,NaN,NaN
104,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,272533,False,{'isrc': 'USIR10311862'},{'spotify': 'https://open.spotify.com/track/0x...,https://api.spotify.com/v1/tracks/0xmjwnQ3FNE6...,0xmjwnQ3FNE6HuWCt2nHdZ,...,long_term,0.92,jaslkh,2003,"[pop, pop, pop]",NaT,NaN,NaN,NaN,NaN
105,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,157642,False,{'isrc': 'SEYOK1870714'},{'spotify': 'https://open.spotify.com/track/1p...,https://api.spotify.com/v1/tracks/1pVvfmQB9OB8...,1pVvfmQB9OB8FqCbp2UGA8,...,long_term,0.90,jaslkh,2019,[],NaT,NaN,NaN,NaN,NaN
107,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,283148,False,{'isrc': 'FR6F32102470'},{'spotify': 'https://open.spotify.com/track/64...,https://api.spotify.com/v1/tracks/64mVjYpiuyDC...,64mVjYpiuyDCNu2FcPsium,...,long_term,0.86,jaslkh,2021,"[rap, rap, rap]",NaT,NaN,NaN,NaN,NaN
108,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,238215,False,{'isrc': 'QZNWU2036495'},{'spotify': 'https://open.spotify.com/track/2V...,https://api.spotify.com/v1/tracks/2VweLDWvwHcI...,2VweLDWvwHcICU6g8RoFbO,...,long_term,0.84,jaslkh,2021,[gen z singer-songwriter],NaT,NaN,NaN,NaN,NaN
113,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BG, BH, BO, BR, CA, CH, C...",1,233456,False,{'isrc': 'USWB12201789'},{'spotify': 'https://open.spotify.com/track/6x...,https://api.spotify.com/v1/tracks/6xGruZOHLs39...,6xGruZOHLs39ZbVccQTuPZ,...,long_term,0.74,jaslkh,2022,[pop],NaT,NaN,NaN,NaN,NaN
114,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,130304,False,{'isrc': 'QZHZ52250087'},{'spotify': 'https://open.spotify.com/track/7s...,https://api.spotify.com/v1/tracks/7sG8wL0DRZvU...,7sG8wL0DRZvUNH3PKVmyr4,...,long_term,0.72,jaslkh,2004,[],NaT,NaN,NaN,NaN,NaN
115,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,299873,True,{'isrc': 'FR9W12006017'},{'spotify': 'https://open.spotify.com/track/2U...,https://api.spotify.com/v1/tracks/2Uv2DyJ1EiJ8...,2Uv2DyJ1EiJ8FawI9mCDTp,...,long_term,0.70,jaslkh,2019,"[rap, rap]",NaT,NaN,NaN,NaN,NaN
119,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174760,False,{'isrc': 'GBBPJ9800675'},{'spotify': 'https://open.spotify.com/track/5T...,https://api.spotify.com/v1/tracks/5Ts1DYOuouQL...,5Ts1DYOuouQLgzTaisxWYh,...,long_term,0.62,jaslkh,1970,[],NaT,NaN,NaN,NaN,NaN
144,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,230266,False,{'isrc': 'GBARL0700464'},{'spotify': 'https://open.spotify.com/track/3V...,https://api.spotify.com/v1/tracks/3VnwIIjxOrdk...,3VnwIIjxOrdkbYmp402CIo,...,long_term,0.12,jaslkh,1991,"[flamenco, rumba, world]",NaT,NaN,NaN,NaN,NaN
12238,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,283148,False,{'isrc': 'FR6F32102470'},{'spotify': 'https://open.spotify.com/track/64...,https://api.spotify.com/v1/tracks/64mVjYpiuyDC...,64mVjYpiuyDCNu2FcPsium,...,short_term,0.70,dany,2021,"[rap, rap, rap]",NaT,NaN,NaN,NaN,NaN

In [ ]:
if lmf.num_factors <= 3:
    df_tracks = df_matrix_mf.copy()
    df_tracks = df_tracks.sample(frac=1) # Shuffle the dataframe
    df_tracks = df_tracks[:150] # Keep only 1000 tracks

    # Add item latent factors to the dataframe
    items_latent_columns = [f"track_latent_{i}" for i in range(lmf.num_factors)]
    for track_id in df_tracks["id"].unique():
        latent_factors = lmf.get_item_factors([matrix_mf.itemnames_to_ids([track_id])[0]]).tolist()
        df_tracks.loc[df_tracks["id"] == track_id, items_latent_columns] = latent_factors

    # Add user latent factors to the dataframe
    users_latent_columns = [f"latent_factor_{i}" for i in range(lmf.num_factors)]
    for user_id in df_tracks["username"].unique():
        latent_factors = lmf.get_user_factors([matrix_mf.usernames_to_ids([user_id])[0]]).tolist()
        df_tracks.loc[df_tracks["username"] == user_id, users_latent_columns] = latent_factors

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=items_latent_columns,
    ).show()

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=users_latent_columns,
    ).show()