In [1]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from recommenders.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float64

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [3]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.98,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.96,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.94,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.92,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [4]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
# used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100

In [5]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity", device=device, dtype=dtype)
R = matrix_mf.R
R

tensor([[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        ...,
        [ 80.,   0.,   0.,  ...,   0.,   0.,  80.],
        [ 50., 180.,  50.,  ...,   0.,  50.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.]], device='mps:0')

In [6]:
alpha = matrix_mf.compute_alpha().item()
R *= alpha
alpha

0.09144702553749084

In [7]:
num_latent_factors = 100
lmf = LogisticMatrixFactorization(
    R=R,
    num_factors=num_latent_factors,
    alpha=alpha,
    lambd=0.01,
    device=device,
    dtype=dtype,
)

num_epochs = 10000
lmf.train_with_gradients(
    num_epochs=num_epochs,
    learning_rate=0.01,
    log_interval=10,
)

Epoch 1: loss = 107504.6484375, MPR = 0.49529629945755005
Epoch 11: loss = 68812.0, MPR = 0.4382598102092743
Epoch 21: loss = 65343.12890625, MPR = 0.4032478928565979
Epoch 31: loss = 54251.6796875, MPR = 0.37432730197906494
Epoch 41: loss = 43614.390625, MPR = 0.34907814860343933
Epoch 51: loss = 51348.34375, MPR = 0.32703930139541626
Epoch 61: loss = 70398.1953125, MPR = 0.3070744574069977
Epoch 71: loss = 39351.3515625, MPR = 0.2885867655277252
Epoch 81: loss = 41856.76953125, MPR = 0.272062212228775
Epoch 91: loss = 33016.640625, MPR = 0.25723353028297424
Epoch 101: loss = 35650.76953125, MPR = 0.24339456856250763
Epoch 111: loss = 36313.765625, MPR = 0.23067109286785126
Epoch 121: loss = 58521.7890625, MPR = 0.21964555978775024
Epoch 131: loss = 23597.244140625, MPR = 0.2088986188173294
Epoch 141: loss = 30619.607421875, MPR = 0.1989588439464569
Epoch 151: loss = 54841.83984375, MPR = 0.1902640461921692
Epoch 161: loss = 29517.71875, MPR = 0.1821192502975464
Epoch 171: loss = 25246.923828125, MPR = 0.17448638379573822
Epoch 181: loss = 24195.775390625, MPR = 0.16752947866916656
Epoch 191: loss = 21158.08984375, MPR = 0.16103701293468475
Epoch 201: loss = 49127.140625, MPR = 0.1550748199224472
Epoch 211: loss = 24174.794921875, MPR = 0.14959600567817688
Epoch 221: loss = 24309.89453125, MPR = 0.14450444281101227
Epoch 231: loss = 40534.10546875, MPR = 0.13992738723754883
Epoch 241: loss = 20201.482421875, MPR = 0.13553375005722046
Epoch 251: loss = 21401.771484375, MPR = 0.13150295615196228
Epoch 261: loss = 23988.0625, MPR = 0.12769971787929535
Epoch 271: loss = 45216.0234375, MPR = 0.12436877191066742
Epoch 281: loss = 18336.09765625, MPR = 0.12116069346666336
Epoch 291: loss = 20966.814453125, MPR = 0.1182309165596962
Epoch 301: loss = 15293.82421875, MPR = 0.11545613408088684
Epoch 311: loss = 18722.361328125, MPR = 0.11281362920999527
Epoch 321: loss = 24896.880859375, MPR = 0.11043606698513031
Epoch 331: loss = 42679.3515625, MPR = 0.1083638146519661
Epoch 341: loss = 16670.1484375, MPR = 0.10634010285139084
Epoch 351: loss = 17717.029296875, MPR = 0.1044587716460228
Epoch 361: loss = 16107.48828125, MPR = 0.10265801846981049
Epoch 371: loss = 22537.125, MPR = 0.10099904239177704
Epoch 381: loss = 43072.171875, MPR = 0.09963615238666534
Epoch 391: loss = 17566.513671875, MPR = 0.09827417135238647
Epoch 401: loss = 21197.8203125, MPR = 0.09701645374298096
Epoch 411: loss = 19694.58984375, MPR = 0.09580465406179428
Epoch 421: loss = 21269.609375, MPR = 0.09467066824436188
Epoch 431: loss = 20849.39453125, MPR = 0.09355930984020233
Epoch 441: loss = 20926.609375, MPR = 0.09248410165309906
Epoch 451: loss = 38078.640625, MPR = 0.09156754612922668
Epoch 461: loss = 14886.6787109375, MPR = 0.09068437665700912
Epoch 471: loss = 15016.8154296875, MPR = 0.08982548117637634
Epoch 481: loss = 22661.771484375, MPR = 0.08901485055685043
Epoch 491: loss = 37415.68359375, MPR = 0.0883447527885437
Epoch 501: loss = 15791.3955078125, MPR = 0.08770052343606949
Epoch 511: loss = 41393.82421875, MPR = 0.08703462034463882
Epoch 521: loss = 16142.6328125, MPR = 0.08648623526096344
Epoch 531: loss = 17566.09375, MPR = 0.08594782650470734
Epoch 541: loss = 18315.02734375, MPR = 0.0854184478521347
Epoch 551: loss = 30788.525390625, MPR = 0.08494280278682709
Epoch 561: loss = 16321.439453125, MPR = 0.08444495499134064
Epoch 571: loss = 19245.462890625, MPR = 0.08397651463747025
Epoch 581: loss = 36448.859375, MPR = 0.08362172544002533
Epoch 591: loss = 13957.244140625, MPR = 0.08329100161790848
Epoch 601: loss = 18072.73828125, MPR = 0.08295582979917526
Epoch 611: loss = 16369.7587890625, MPR = 0.08260788023471832
Epoch 621: loss = 22070.509765625, MPR = 0.0823008194565773
Epoch 631: loss = 35357.30859375, MPR = 0.08201517909765244
Epoch 641: loss = 15956.9580078125, MPR = 0.08173659443855286
Epoch 651: loss = 39877.109375, MPR = 0.08146553486585617
Epoch 661: loss = 16947.765625, MPR = 0.08124364167451859
Epoch 671: loss = 18116.60546875, MPR = 0.08099734038114548
Epoch 681: loss = 20860.16015625, MPR = 0.08073904365301132
Epoch 691: loss = 35451.5078125, MPR = 0.0805308073759079
Epoch 701: loss = 14130.5361328125, MPR = 0.08032738417387009
Epoch 711: loss = 18227.544921875, MPR = 0.0801185742020607
Epoch 721: loss = 27128.091796875, MPR = 0.07992010563611984
Epoch 731: loss = 15367.845703125, MPR = 0.07973353564739227
Epoch 741: loss = 14313.6953125, MPR = 0.07952237129211426
Epoch 751: loss = 14603.6650390625, MPR = 0.07934696227312088
Epoch 761: loss = 20774.326171875, MPR = 0.0791863203048706
Epoch 771: loss = 34568.23046875, MPR = 0.07904519140720367
Epoch 781: loss = 17011.443359375, MPR = 0.07893393188714981
Epoch 791: loss = 20271.30859375, MPR = 0.07880020886659622
Epoch 801: loss = 38665.05078125, MPR = 0.07869283854961395
Epoch 811: loss = 14483.462890625, MPR = 0.07860050350427628
Epoch 821: loss = 21766.109375, MPR = 0.07849453389644623
Epoch 831: loss = 33026.2734375, MPR = 0.0783933773636818
Epoch 841: loss = 17389.490234375, MPR = 0.07830840349197388
Epoch 851: loss = 18618.19140625, MPR = 0.0782138779759407
Epoch 861: loss = 34745.21484375, MPR = 0.07812798023223877
Epoch 871: loss = 14463.3583984375, MPR = 0.0780518651008606
Epoch 881: loss = 21196.509765625, MPR = 0.07796112447977066
Epoch 891: loss = 31585.8125, MPR = 0.07787203788757324
Epoch 901: loss = 16926.025390625, MPR = 0.07779377698898315
Epoch 911: loss = 18329.87890625, MPR = 0.0776984840631485
Epoch 921: loss = 33355.00390625, MPR = 0.07761318981647491
Epoch 931: loss = 14257.6337890625, MPR = 0.07754578441381454
Epoch 941: loss = 20928.359375, MPR = 0.07746906578540802
Epoch 951: loss = 30446.630859375, MPR = 0.07739661633968353
Epoch 961: loss = 16641.802734375, MPR = 0.07733689248561859
Epoch 971: loss = 18454.435546875, MPR = 0.07726599276065826
Epoch 981: loss = 32285.490234375, MPR = 0.07719994336366653
Epoch 991: loss = 14535.00390625, MPR = 0.07714398205280304
Epoch 1001: loss = 19669.900390625, MPR = 0.077077716588974
Epoch 1011: loss = 30047.482421875, MPR = 0.0770227462053299
Epoch 1021: loss = 16627.908203125, MPR = 0.07697489112615585
Epoch 1031: loss = 17501.19140625, MPR = 0.07692117989063263
Epoch 1041: loss = 31401.05859375, MPR = 0.07687272876501083
Epoch 1051: loss = 14260.5625, MPR = 0.07683098316192627
Epoch 1061: loss = 18868.50390625, MPR = 0.0767858475446701
Epoch 1071: loss = 28621.14453125, MPR = 0.07674555480480194
Epoch 1081: loss = 16201.693359375, MPR = 0.07671081274747849
Epoch 1091: loss = 17113.8203125, MPR = 0.07667086273431778
Epoch 1101: loss = 29451.12890625, MPR = 0.07663112878799438
Epoch 1111: loss = 14573.10546875, MPR = 0.07659916579723358
Epoch 1121: loss = 17907.68359375, MPR = 0.0765673965215683
Epoch 1131: loss = 27634.228515625, MPR = 0.07653535157442093
Epoch 1141: loss = 15350.6044921875, MPR = 0.07650808244943619
Epoch 1151: loss = 16535.68359375, MPR = 0.07648245990276337
Epoch 1161: loss = 26709.8671875, MPR = 0.0764574185013771
Epoch 1171: loss = 14680.4970703125, MPR = 0.07643267512321472
Epoch 1181: loss = 24345.544921875, MPR = 0.07640822976827621
Epoch 1191: loss = 20959.4140625, MPR = 0.07638788223266602
Epoch 1201: loss = 20858.00390625, MPR = 0.07636748254299164
Epoch 1211: loss = 29939.51953125, MPR = 0.0763479694724083
Epoch 1221: loss = 17934.24609375, MPR = 0.07633029669523239
Epoch 1231: loss = 14210.8408203125, MPR = 0.07631215453147888
Epoch 1241: loss = 15594.2265625, MPR = 0.07629349827766418
Epoch 1251: loss = 19733.48828125, MPR = 0.07627544552087784
Epoch 1261: loss = 13738.9482421875, MPR = 0.0762602761387825
Epoch 1271: loss = 16759.79296875, MPR = 0.07624439895153046
Epoch 1281: loss = 13795.5732421875, MPR = 0.07622785866260529
Epoch 1291: loss = 34926.015625, MPR = 0.07621289789676666
Epoch 1301: loss = 16009.32421875, MPR = 0.07619693130254745
Epoch 1311: loss = 26115.755859375, MPR = 0.07618258893489838
Epoch 1321: loss = 13551.564453125, MPR = 0.07616817951202393
Epoch 1331: loss = 15556.115234375, MPR = 0.07615376263856888
Epoch 1341: loss = 21263.0234375, MPR = 0.07613389939069748
Epoch 1351: loss = 34235.921875, MPR = 0.07611875236034393
Epoch 1361: loss = 13475.2099609375, MPR = 0.07610630989074707
Epoch 1371: loss = 22445.544921875, MPR = 0.07609181106090546
Epoch 1381: loss = 15384.0986328125, MPR = 0.07607939839363098
Epoch 1391: loss = 20472.4609375, MPR = 0.0760672464966774
Epoch 1401: loss = 30236.546875, MPR = 0.07605649530887604
Epoch 1411: loss = 14855.0087890625, MPR = 0.07604645192623138
Epoch 1421: loss = 18806.134765625, MPR = 0.07603703439235687
Epoch 1431: loss = 31071.109375, MPR = 0.07602883130311966
Epoch 1441: loss = 35063.8203125, MPR = 0.0760209709405899
Epoch 1451: loss = 14315.09765625, MPR = 0.07601406425237656
Epoch 1461: loss = 18120.041015625, MPR = 0.07600727677345276
Epoch 1471: loss = 32611.35546875, MPR = 0.07599940150976181
Epoch 1481: loss = 13641.3828125, MPR = 0.0759916603565216
Epoch 1491: loss = 16957.703125, MPR = 0.07598404586315155
Epoch 1501: loss = 31015.060546875, MPR = 0.0759771466255188
Epoch 1511: loss = 14185.236328125, MPR = 0.07597015798091888
Epoch 1521: loss = 17556.5625, MPR = 0.0759626254439354
Epoch 1531: loss = 32397.40234375, MPR = 0.07595564424991608
Epoch 1541: loss = 14088.8203125, MPR = 0.07594865560531616
Epoch 1551: loss = 20467.982421875, MPR = 0.07594159245491028
Epoch 1561: loss = 33591.578125, MPR = 0.0759340301156044
Epoch 1571: loss = 14959.7216796875, MPR = 0.07592833042144775
Epoch 1581: loss = 20427.609375, MPR = 0.07592172175645828
Epoch 1591: loss = 33774.35546875, MPR = 0.07591523230075836
Epoch 1601: loss = 14771.34765625, MPR = 0.07590961456298828
Epoch 1611: loss = 21017.783203125, MPR = 0.07590343058109283
Epoch 1621: loss = 33022.015625, MPR = 0.07589811086654663
Epoch 1631: loss = 15518.44140625, MPR = 0.07589396089315414
Epoch 1641: loss = 20601.26953125, MPR = 0.07588853687047958
Epoch 1651: loss = 33126.6796875, MPR = 0.07588346302509308
Epoch 1661: loss = 15345.173828125, MPR = 0.07587996125221252
Epoch 1671: loss = 20948.5546875, MPR = 0.07587572932243347
Epoch 1681: loss = 32282.810546875, MPR = 0.07587188482284546
Epoch 1691: loss = 16030.2060546875, MPR = 0.07586878538131714
Epoch 1701: loss = 20251.81640625, MPR = 0.07586513459682465
Epoch 1711: loss = 32298.96484375, MPR = 0.07586164772510529
Epoch 1721: loss = 15739.236328125, MPR = 0.07585888355970383
Epoch 1731: loss = 20366.529296875, MPR = 0.0758553221821785
Epoch 1741: loss = 31383.09765625, MPR = 0.07585223019123077
Epoch 1751: loss = 16252.505859375, MPR = 0.07584930211305618
Epoch 1761: loss = 19531.01953125, MPR = 0.07584575563669205
Epoch 1771: loss = 31339.447265625, MPR = 0.07584211975336075
Epoch 1781: loss = 15779.5078125, MPR = 0.07583896815776825
Epoch 1791: loss = 19570.7890625, MPR = 0.07583551853895187
Epoch 1801: loss = 30375.087890625, MPR = 0.07583169639110565
Epoch 1811: loss = 16122.140625, MPR = 0.07582810521125793
Epoch 1821: loss = 18705.712890625, MPR = 0.07582477480173111
Epoch 1831: loss = 30263.19140625, MPR = 0.0758211761713028
Epoch 1841: loss = 15515.0908203125, MPR = 0.0758175402879715
Epoch 1851: loss = 18716.40625, MPR = 0.07581375539302826
Epoch 1861: loss = 29210.28125, MPR = 0.07580993324518204
Epoch 1871: loss = 15738.9970703125, MPR = 0.07580424100160599
Epoch 1881: loss = 17814.861328125, MPR = 0.075799860060215
Epoch 1891: loss = 28937.884765625, MPR = 0.07579690217971802
Epoch 1901: loss = 15032.09765625, MPR = 0.07579278945922852
Epoch 1911: loss = 17721.216796875, MPR = 0.0757889449596405
Epoch 1921: loss = 27522.189453125, MPR = 0.07578536868095398
Epoch 1931: loss = 15085.51953125, MPR = 0.07578238099813461
Epoch 1941: loss = 15303.6787109375, MPR = 0.07577938586473465
Epoch 1951: loss = 14254.822265625, MPR = 0.07577643543481827
Epoch 1961: loss = 15789.8046875, MPR = 0.07577448338270187
Epoch 1971: loss = 15394.05078125, MPR = 0.0757715255022049
Epoch 1981: loss = 15264.27734375, MPR = 0.07576872408390045
Epoch 1991: loss = 16529.76171875, MPR = 0.07576631754636765
Epoch 2001: loss = 26473.375, MPR = 0.07576390355825424
Epoch 2011: loss = 14170.482421875, MPR = 0.07576125115156174
Epoch 2021: loss = 20523.30859375, MPR = 0.07575938105583191
Epoch 2031: loss = 13894.166015625, MPR = 0.07575623691082001
Epoch 2041: loss = 22608.791015625, MPR = 0.07575369626283646
Epoch 2051: loss = 23240.576171875, MPR = 0.07575114816427231
Epoch 2061: loss = 13682.9609375, MPR = 0.0757492408156395
Epoch 2071: loss = 31845.9140625, MPR = 0.07574629783630371
Epoch 2081: loss = 13826.3857421875, MPR = 0.07574377954006195
Epoch 2091: loss = 21359.08984375, MPR = 0.07574187219142914
Epoch 2101: loss = 15457.82421875, MPR = 0.07573801279067993
Epoch 2111: loss = 25437.423828125, MPR = 0.07573706656694412
Epoch 2121: loss = 21409.33984375, MPR = 0.07573486119508743
Epoch 2131: loss = 20509.9375, MPR = 0.07573238760232925
Epoch 2141: loss = 13238.0439453125, MPR = 0.07572880387306213
Epoch 2151: loss = 14126.826171875, MPR = 0.07572533190250397
Epoch 2161: loss = 31785.255859375, MPR = 0.07572229951620102
Epoch 2171: loss = 21119.025390625, MPR = 0.07571892440319061
Epoch 2181: loss = 32726.232421875, MPR = 0.07571553438901901
Epoch 2191: loss = 15125.138671875, MPR = 0.07571185380220413
Epoch 2201: loss = 13267.4150390625, MPR = 0.07570772618055344
Epoch 2211: loss = 20901.728515625, MPR = 0.07570546865463257
Epoch 2221: loss = 13279.361328125, MPR = 0.0757024958729744
Epoch 2231: loss = 22034.7265625, MPR = 0.07569947838783264
Epoch 2241: loss = 28398.84375, MPR = 0.07569554448127747
Epoch 2251: loss = 13968.369140625, MPR = 0.07569322735071182
Epoch 2261: loss = 34203.7578125, MPR = 0.07569092512130737
Epoch 2271: loss = 13519.693359375, MPR = 0.07568856328725815
Epoch 2281: loss = 32909.359375, MPR = 0.07568657398223877
Epoch 2291: loss = 14606.291015625, MPR = 0.07568458467721939
Epoch 2301: loss = 18315.76953125, MPR = 0.0756828561425209
Epoch 2311: loss = 19727.48046875, MPR = 0.07568112015724182
Epoch 2321: loss = 22505.85546875, MPR = 0.07567965984344482
Epoch 2331: loss = 33275.28515625, MPR = 0.07567769289016724
Epoch 2341: loss = 13322.564453125, MPR = 0.0756763368844986
Epoch 2351: loss = 18132.0625, MPR = 0.07567473500967026
Epoch 2361: loss = 32149.158203125, MPR = 0.07567331194877625
Epoch 2371: loss = 13815.220703125, MPR = 0.07567182183265686
Epoch 2381: loss = 17518.21875, MPR = 0.07567030191421509
Epoch 2391: loss = 30774.478515625, MPR = 0.07566893100738525
Epoch 2401: loss = 13371.7802734375, MPR = 0.0756676197052002
Epoch 2411: loss = 17290.228515625, MPR = 0.07566619664430618
Epoch 2421: loss = 30648.3203125, MPR = 0.07566522061824799
Epoch 2431: loss = 13957.4296875, MPR = 0.07566424459218979
Epoch 2441: loss = 18657.818359375, MPR = 0.07566329091787338
Epoch 2451: loss = 33215.21875, MPR = 0.07566235959529877
Epoch 2461: loss = 14005.896484375, MPR = 0.0756615549325943
Epoch 2471: loss = 20462.75390625, MPR = 0.07566097378730774
Epoch 2481: loss = 32831.54296875, MPR = 0.07566026598215103
Epoch 2491: loss = 14678.7783203125, MPR = 0.07565976679325104
Epoch 2501: loss = 20495.2890625, MPR = 0.07565926760435104
Epoch 2511: loss = 33094.09765625, MPR = 0.0756588950753212
Epoch 2521: loss = 14556.2265625, MPR = 0.0756584033370018
Epoch 2531: loss = 21159.2109375, MPR = 0.07565782219171524
Epoch 2541: loss = 32503.16796875, MPR = 0.07565724104642868
Epoch 2551: loss = 15244.73828125, MPR = 0.07565676420927048
Epoch 2561: loss = 20838.30859375, MPR = 0.07565601170063019
Epoch 2571: loss = 32681.796875, MPR = 0.07565544545650482
Epoch 2581: loss = 15109.384765625, MPR = 0.07565485686063766
Epoch 2591: loss = 21164.6015625, MPR = 0.0756542831659317
Epoch 2601: loss = 32020.06640625, MPR = 0.07565353810787201
Epoch 2611: loss = 15738.171875, MPR = 0.07565280050039291
Epoch 2621: loss = 20555.994140625, MPR = 0.07565222680568695
Epoch 2631: loss = 32138.94140625, MPR = 0.07565147429704666
Epoch 2641: loss = 15502.0185546875, MPR = 0.07565084844827652
Epoch 2651: loss = 20670.609375, MPR = 0.0756501853466034
Epoch 2661: loss = 31431.837890625, MPR = 0.07564935833215714
Epoch 2671: loss = 16001.5458984375, MPR = 0.0756487026810646
Epoch 2681: loss = 19935.875, MPR = 0.07564765214920044
Epoch 2691: loss = 31508.5703125, MPR = 0.07564643025398254
Epoch 2701: loss = 15635.5087890625, MPR = 0.07564559578895569
Epoch 2711: loss = 19984.47265625, MPR = 0.0756443664431572
Epoch 2721: loss = 30764.8984375, MPR = 0.07564321160316467
Epoch 2731: loss = 16011.416015625, MPR = 0.07564196735620499
Epoch 2741: loss = 19228.888671875, MPR = 0.07564063370227814
Epoch 2751: loss = 30796.755859375, MPR = 0.07563824951648712
Epoch 2761: loss = 15544.283203125, MPR = 0.07563701272010803
Epoch 2771: loss = 19269.8984375, MPR = 0.07563590258359909
Epoch 2781: loss = 30008.849609375, MPR = 0.07563494890928268
Epoch 2791: loss = 15829.6171875, MPR = 0.07563363760709763
Epoch 2801: loss = 18518.013671875, MPR = 0.07563265413045883
Epoch 2811: loss = 29979.779296875, MPR = 0.07563191652297974
Epoch 2821: loss = 15292.697265625, MPR = 0.0756310299038887
Epoch 2831: loss = 18549.53515625, MPR = 0.07563015818595886
Epoch 2841: loss = 29122.34375, MPR = 0.07562936842441559
Epoch 2851: loss = 15510.2109375, MPR = 0.07562868297100067
Epoch 2861: loss = 17782.044921875, MPR = 0.07562834024429321
Epoch 2871: loss = 28985.75, MPR = 0.07562782615423203
Epoch 2881: loss = 14917.3642578125, MPR = 0.0756273865699768
Epoch 2891: loss = 17764.16796875, MPR = 0.07562799006700516
Epoch 2901: loss = 27963.19140625, MPR = 0.0756278708577156
Epoch 2911: loss = 15063.92578125, MPR = 0.07562760263681412
Epoch 2921: loss = 16888.115234375, MPR = 0.07562746852636337
Epoch 2931: loss = 27374.75, MPR = 0.0756276547908783
Epoch 2941: loss = 14291.423828125, MPR = 0.07562751322984695
Epoch 2951: loss = 31667.46484375, MPR = 0.07562834024429321
Epoch 2961: loss = 22253.333984375, MPR = 0.07562736421823502
Epoch 2971: loss = 18562.84375, MPR = 0.07562730461359024
Epoch 2981: loss = 15180.783203125, MPR = 0.07562705129384995
Epoch 2991: loss = 22237.9296875, MPR = 0.07562703639268875
Epoch 3001: loss = 14267.2841796875, MPR = 0.0756269246339798
Epoch 3011: loss = 20442.75, MPR = 0.07562709599733353
Epoch 3021: loss = 14495.7880859375, MPR = 0.07562703639268875
Epoch 3031: loss = 24906.703125, MPR = 0.07562702894210815
Epoch 3041: loss = 21323.91796875, MPR = 0.0756278932094574
Epoch 3051: loss = 14054.572265625, MPR = 0.07562686502933502
Epoch 3061: loss = 28220.19921875, MPR = 0.07562749832868576
Epoch 3071: loss = 15136.7822265625, MPR = 0.07562689483165741
Epoch 3081: loss = 32956.1328125, MPR = 0.075628362596035
Epoch 3091: loss = 24601.841796875, MPR = 0.07562785595655441
Epoch 3101: loss = 14606.638671875, MPR = 0.07562684267759323
Epoch 3111: loss = 13687.4326171875, MPR = 0.07562792301177979
Epoch 3121: loss = 13524.201171875, MPR = 0.07562778890132904
Epoch 3131: loss = 13566.404296875, MPR = 0.07562579959630966
Epoch 3141: loss = 13309.400390625, MPR = 0.07562492042779922
Epoch 3151: loss = 13571.970703125, MPR = 0.07562478631734848
Epoch 3161: loss = 13490.1298828125, MPR = 0.07562417536973953
Epoch 3171: loss = 26053.20703125, MPR = 0.07562397420406342
Epoch 3181: loss = 31431.12109375, MPR = 0.07562384009361267
Epoch 3191: loss = 32967.328125, MPR = 0.07562361657619476
Epoch 3201: loss = 17585.01953125, MPR = 0.07562335580587387
Epoch 3211: loss = 17853.982421875, MPR = 0.07562319189310074
Epoch 3221: loss = 13269.29296875, MPR = 0.07562307268381119
Epoch 3231: loss = 13479.978515625, MPR = 0.07562284916639328
Epoch 3241: loss = 20432.078125, MPR = 0.07562273740768433
Epoch 3251: loss = 25060.89453125, MPR = 0.0756227895617485
Epoch 3261: loss = 13065.48046875, MPR = 0.07562287896871567
Epoch 3271: loss = 13843.494140625, MPR = 0.07562264800071716
Epoch 3281: loss = 33796.8046875, MPR = 0.07562258839607239
Epoch 3291: loss = 14954.51953125, MPR = 0.07562240958213806
Epoch 3301: loss = 13016.6201171875, MPR = 0.07562217116355896

In [8]:
lmf.save("models", "lmf_all_types_100")
lmf = LogisticMatrixFactorization.load(os.path.join("models", "lmf_all_types_100.pt"))

In [9]:
px.line(x=range(len(lmf.losses)), y=lmf.losses.cpu(), title="Loss").show()
px.line(x=range(len(lmf.mprs)), y=lmf.mprs.cpu(), title="MPRS").show()

In [13]:
user_id = matrix_mf.usernames_to_ids(["michelle"])[0]

# Get the top 10 recommendations for the user
top_10_ids, top_10_ids_scores = lmf.recommend(user_id, top_k=20, filter_user_items=True)

# Get the top 10 recommendations for the user
matrix_mf.items_ids_to_df(top_10_ids)[spoti.PRETTY_PRINT_FEATURES]

,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
112,jaslkh,Fleetwood Mac,Dreams - 2004 Remaster,1977,89,0.828,0.492,0.0276,0.0644,0.004280,0.128,0.789,120.151,-9.744,257800,1977,89
282,jaslkh,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.6320,0.001190,0.103,0.465,105.011,-9.535,176026,2022,59
359,jaslkh,Jacques Brel,Ces gens-là,1988,49,0.531,0.210,0.1640,0.6260,0.000000,0.163,0.494,129.663,-18.451,278400,1988,49
409,jaslkh,Fleetwood Mac,Dreams - 2004 Remaster,1977,89,0.828,0.492,0.0276,0.0644,0.004280,0.128,0.789,120.151,-9.744,257800,1977,89
914,jaslkh,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.6320,0.001190,0.103,0.465,105.011,-9.535,176026,2022,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10531,paul,Josman,L'Occasion,2018,47,0.799,0.593,0.3730,0.2690,0.000000,0.117,0.714,85.995,-5.865,223255,2018,47
10532,paul,Josman,L'Occasion,2018,47,0.799,0.593,0.3730,0.2690,0.000000,0.117,0.714,85.995,-5.865,223255,2018,47
10756,paul,Téléphone,Cendrillon,2004,46,0.507,0.489,0.0326,0.3010,0.019200,0.105,0.288,147.932,-13.273,238333,2004,46
10864,paul,PNL,Le monde ou rien,2015,64,0.648,0.465,0.1710,0.7720,0.000002,0.287,0.407,103.025,-9.716,256280,2015,64
12223,dany,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.6320,0.001190,0.103,0.465,105.011,-9.535,176026,2022,59

In [11]:
if lmf.num_factors <= 3:
    df_tracks = df_matrix_mf.copy()
    df_tracks = df_tracks.sample(frac=1) # Shuffle the dataframe
    df_tracks = df_tracks[:1000] # Keep only 1000 tracks

    # Add item latent factors to the dataframe
    items_latent_columns = [f"track_latent_{i}" for i in range(lmf.num_factors)]
    for track_id in df_tracks["id"].unique():
        latent_factors = lmf.get_item_latent_factors(matrix_mf.items_to_ids([track_id])[0]).tolist()
        df_tracks.loc[df_tracks["id"] == track_id, items_latent_columns] = latent_factors

    # Add user latent factors to the dataframe
    users_latent_columns = [f"latent_factor_{i}" for i in range(lmf.num_factors)]
    for user_id in df_tracks["username"].unique():
        latent_factors = lmf.get_user_latent_factors(matrix_mf.usernames_to_ids([user_id])[0]).tolist()
        df_tracks.loc[df_tracks["username"] == user_id, users_latent_columns] = latent_factors

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=items_latent_columns,
    ).show()

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=users_latent_columns,
    ).show()