In [1]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torch.nn import functional as F
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from recommenders.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float32

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [3]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.98,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.96,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.94,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.92,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [4]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100

In [5]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity", device=device, dtype=dtype)
user_interacted_with = matrix_mf.R
user_interacted_with

tensor([[ 0.,  0., 62.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0., 84.],
        ...,
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [44., 60.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ..., 92.,  0.,  0.]], device='mps:0')

In [6]:
user_interacted_with.shape

torch.Size([8, 923])

In [7]:
alpha = matrix_mf.compute_alpha().item()
user_interacted_with *= alpha
alpha

0.10527777671813965

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from typing import List, Optional


class MultiVAE(nn.Module):
    """
    Variational Autoencoder with Multinomial Likelihood (Multi-VAE).

    This VAE is designed for collaborative filtering tasks. The architecture
    comprises of encoder (q-network) and decoder (p-network) layers. The encoder
    produces a latent representation, and the decoder reconstructs the input data.

    Attributes:
        encoder_dims (List[int]): Dimensions for the encoder layers.
        decoder_dims (List[int]): Dimensions for the decoder layers.
        dropout_rate (float): Dropout rate for regularization.

    References:
        [1] Liang, Dawen, et al. "Variational autoencoders for collaborative filtering."
            Proceedings of the 2018 World Wide Web Conference. 2018.
        [2] Variational autoencoders for collaborative filtering
            by @dawenl.
            https://github.com/dawenl/vae_cf
        [3] Variational Autoencoders for Collaborative Filtering - Implementation in PyTorch
            by @younggyoseo.
            https://github.com/younggyoseo/vae-cf-pytorch
    """

    def __init__(
        self,
        encoder_dims: List[int],
        decoder_dims: Optional[List[int]] = None,
        dropout_rate: float = 0.5,
        device: torch.device = torch.device("cpu"),
        dtype: torch.dtype = torch.float32,
    ) -> None:
        super(MultiVAE, self).__init__()
        self.device = device
        self.dtype = dtype

        self.encoder_dims = encoder_dims
        self.decoder_dims = decoder_dims if decoder_dims else encoder_dims[::-1]

        assert (
            self.decoder_dims[0] == encoder_dims[-1]
        ), "Output dimension of encoder must match input dimension of decoder."
        assert (
            self.decoder_dims[-1] == encoder_dims[0]
        ), "Latent dimension mismatch between encoder and decoder."

        # Modify the last dimension of encoder for mean and variance
        modified_encoder_dims = self.encoder_dims[:-1] + [self.encoder_dims[-1] * 2]
        self.encoder_layers = nn.ModuleList(
            [
                nn.Linear(in_features, out_features)
                for in_features, out_features in zip(
                    modified_encoder_dims[:-1], modified_encoder_dims[1:]
                )
            ]
        )
        self.decoder_layers = nn.ModuleList(
            [
                nn.Linear(in_features, out_features)
                for in_features, out_features in zip(
                    self.decoder_dims[:-1], self.decoder_dims[1:]
                )
            ]
        )

        self.dropout = nn.Dropout(dropout_rate)
        self.initialize_weights()
        self.to(device=device, dtype=dtype)

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        mu, logvar = self.encode(input)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

    def encode(self, input: torch.Tensor) -> torch.Tensor:
        h = F.normalize(input)
        h = self.dropout(h)

        for i, layer in enumerate(self.encoder_layers):
            h = layer(h)
            if i != len(self.encoder_layers) - 1:
                h = torch.tanh(h)
            else:
                mu = h[:, : self.encoder_dims[-1]]
                logvar = h[:, self.encoder_dims[-1] :]
        return mu, logvar

    def reparameterize(self, mu: torch.Tensor, logvar: torch.Tensor) -> torch.Tensor:
        if self.training:
            std = torch.exp(0.5 * logvar)
            eps = torch.randn_like(std)
            return eps.mul(std).add_(mu)
        else:
            return mu

    def decode(self, z: torch.Tensor) -> torch.Tensor:
        h = z
        for i, layer in enumerate(self.decoder_layers):
            h = layer(h)
            if i != len(self.decoder_layers) - 1:
                h = torch.tanh(h)
        return h

    def initialize_weights(self) -> None:
        for layer in self.encoder_layers + self.decoder_layers:
            size = layer.weight.size()
            fan_out, fan_in = size[0], size[1]
            std = np.sqrt(2.0 / (fan_in + fan_out))
            layer.weight.data.normal_(0.0, std)
            layer.bias.data.normal_(0.0, 0.001)

    def loss(
        self,
        recon_x: torch.Tensor,
        x: torch.Tensor,
        mu: torch.Tensor,
        logvar: torch.Tensor,
        anneal: float = 1.0,
    ) -> torch.Tensor:
        """
        Loss function for MultiVAE.

        Combines Binary Cross Entropy (BCE) and Kullback–Leibler Divergence (KLD)
        to form the Variational Autoencoder loss.

        Parameters:
            recon_x (torch.Tensor): Reconstructed input.
            x (torch.Tensor): Original input.
            mu (torch.Tensor): Mean from the latent space.
            logvar (torch.Tensor): Log variance from the latent space.
            anneal (float): Annealing factor for KLD.

        Returns:
            torch.Tensor: Calculated loss.
        """
        BCE = -torch.mean(torch.sum(F.log_softmax(recon_x, 1) * x, -1))
        KLD = -0.5 * torch.mean(torch.sum(1 + logvar - mu.pow(2) - logvar.exp(), dim=1))
        return BCE + anneal * KLD

    def mpr(self, I: torch.Tensor, R: torch.Tensor) -> float:
        num_users, num_items = R.shape
        total_interactions = torch.sum(R)

        # Create a tensor for percentile ranks (shape: num_items)
        percentile_ranks = (
            torch.arange(num_items, dtype=dtype, device=device) / num_items
        )

        # Use I to index into R and rearrange it, then multiply by the percentile ranks
        # Reshape and expand percentile ranks to match the shape of R
        # (shape of expanded percentile ranks: 1 x num_items)
        weighted_ranks = R.gather(1, I) * percentile_ranks.expand(num_users, -1)

        # Sum over all items and users, and normalize
        mpr = torch.sum(weighted_ranks) / total_interactions

        return mpr.item()

    def recommend_items(
        self,
        user_data: torch.Tensor,
        interacted_indices: Optional[torch.Tensor] = None,
        top_k: int = 10,
    ) -> List[int]:
        """
        Generate item recommendations for a user using the MultiVAE model.

        Args:
        model (MultiVAE): The trained MultiVAE model.
        user_data (torch.Tensor): The user-item interaction vector for a single user.
        interacted_indices (Optional[torch.Tensor]): A binary vector indicating items the user has already interacted with. If None, no filtering is applied.
        top_k (int): Number of top recommendations to return.

        Returns:
        List[int]: List of item indices recommended for the user.
        """
        self.eval()  # Ensure the model is in evaluation mode

        # Encode user data to latent space
        mu, logvar = self.encode(user_data)
        z = self.reparameterize(mu, logvar)

        # Decode the latent representation
        reconstructed_user_data = self.decode(z)

        # Convert to probabilities
        proba = torch.softmax(reconstructed_user_data, dim=1)

        # If interacted_indices is provided, mask out already interacted items
        if interacted_indices is not None:
            interaction_mask = torch.zeros(proba.size(), dtype=torch.bool, device=self.device)
            interaction_mask[0, interacted_indices] = True  # Assumes user_data is a single user batch
            proba.masked_fill_(interaction_mask, 0)

        # Get top k items that have the highest probability
        recommended_items = torch.topk(proba, top_k, dim=1)[1].squeeze().tolist()

        return recommended_items

In [9]:
users, items = user_interacted_with.shape

In [10]:
batch_size = 32

# train_set, val_set = train_test_split(R, test_size=0.2, random_state=42)

# # Convert the train and validation sets into TensorDataset objects
# train_dataset = TensorDataset(train_set)
# val_dataset = TensorDataset(val_set)

# # Create DataLoaders for batching
# train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
# val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

train_set = user_interacted_with
train_dataset = TensorDataset(train_set)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)

eval_set = user_interacted_with
eval_dataset = TensorDataset(eval_set)
eval_loader = DataLoader(eval_dataset, batch_size=batch_size, shuffle=False)

In [11]:
# Define dimensions for the encoder and decoder
encoder_dims = [user_interacted_with.shape[1], 800, 400]
decoder_dims = encoder_dims[::-1]  # Symmetric decoder

# Initialize the model
model = MultiVAE(encoder_dims, decoder_dims, dropout_rate=0.5, device=device, dtype=dtype)

In [12]:
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 1000  # Number of epochs
mprs = []  # Keep track of the MPRs
val_losses = []  # Keep track of the validation loss
train_losses = []  # Keep track of the training loss
for epoch in range(num_epochs):
    model.train()

    train_loss = 0.0
    for data in train_loader:
        data = data[0]
        # Assuming data is a batch of user-item interactions
        optimizer.zero_grad()
        recon_batch, mu, logvar = model(data)
        loss = model.loss(recon_batch, data, mu, logvar)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)
    train_losses.append(train_loss)

    print(
        f"Epoch {epoch + 1}/{num_epochs}: Train Loss: {train_loss:.4f}"
    )

Epoch 1/1000: Train Loss: 5624.1055
Epoch 2/1000: Train Loss: 5607.3218
Epoch 3/1000: Train Loss: 5582.1230
Epoch 4/1000: Train Loss: 5539.0137
Epoch 5/1000: Train Loss: 5550.3882
Epoch 6/1000: Train Loss: 5592.0303
Epoch 7/1000: Train Loss: 5541.9160
Epoch 8/1000: Train Loss: 5496.5386
Epoch 9/1000: Train Loss: 5460.3896
Epoch 10/1000: Train Loss: 5438.9292
Epoch 11/1000: Train Loss: 5383.5469
Epoch 12/1000: Train Loss: 5342.7998
Epoch 13/1000: Train Loss: 5317.3174
Epoch 14/1000: Train Loss: 5117.1313
Epoch 15/1000: Train Loss: 5065.2104
Epoch 16/1000: Train Loss: 4921.5352
Epoch 17/1000: Train Loss: 4819.5454
Epoch 18/1000: Train Loss: 4760.5747
Epoch 19/1000: Train Loss: 4637.3257
Epoch 20/1000: Train Loss: 4414.9365
Epoch 21/1000: Train Loss: 4349.8472
Epoch 22/1000: Train Loss: 4275.3413
Epoch 23/1000: Train Loss: 4177.3701
Epoch 24/1000: Train Loss: 4088.6387
Epoch 25/1000: Train Loss: 4015.2397
Epoch 26/1000: Train Loss: 3991.8376
Epoch 27/1000: Train Loss: 3953.4673
Epoch 28/1000: Train Loss: 3939.2515
Epoch 29/1000: Train Loss: 3933.5076
Epoch 30/1000: Train Loss: 3904.2810
Epoch 31/1000: Train Loss: 3924.5283
Epoch 32/1000: Train Loss: 3900.3870
Epoch 33/1000: Train Loss: 3898.0754
Epoch 34/1000: Train Loss: 3914.2192
Epoch 35/1000: Train Loss: 3906.0693
Epoch 36/1000: Train Loss: 3919.3022
Epoch 37/1000: Train Loss: 3892.8823
Epoch 38/1000: Train Loss: 3899.6091
Epoch 39/1000: Train Loss: 3884.3296
Epoch 40/1000: Train Loss: 3913.5901
Epoch 41/1000: Train Loss: 3888.0042
Epoch 42/1000: Train Loss: 3898.9014
Epoch 43/1000: Train Loss: 3890.1138
Epoch 44/1000: Train Loss: 3878.2542
Epoch 45/1000: Train Loss: 3892.0625
Epoch 46/1000: Train Loss: 3863.7695
Epoch 47/1000: Train Loss: 3881.9075
Epoch 48/1000: Train Loss: 3857.8210
Epoch 49/1000: Train Loss: 3848.6741
Epoch 50/1000: Train Loss: 3862.1836
Epoch 51/1000: Train Loss: 3834.9434
Epoch 52/1000: Train Loss: 3842.3601
Epoch 53/1000: Train Loss: 3839.4719
Epoch 54/1000: Train Loss: 3832.1450
Epoch 55/1000: Train Loss: 3838.1655
Epoch 56/1000: Train Loss: 3816.4617
Epoch 57/1000: Train Loss: 3829.6060
Epoch 58/1000: Train Loss: 3811.3433
Epoch 59/1000: Train Loss: 3823.3328
Epoch 60/1000: Train Loss: 3801.9065
Epoch 61/1000: Train Loss: 3805.8096
Epoch 62/1000: Train Loss: 3802.9919
Epoch 63/1000: Train Loss: 3811.1392
Epoch 64/1000: Train Loss: 3799.2195
Epoch 65/1000: Train Loss: 3806.9331
Epoch 66/1000: Train Loss: 3798.6523
Epoch 67/1000: Train Loss: 3800.7705
Epoch 68/1000: Train Loss: 3802.6697
Epoch 69/1000: Train Loss: 3791.9409
Epoch 70/1000: Train Loss: 3788.6680
Epoch 71/1000: Train Loss: 3795.7915
Epoch 72/1000: Train Loss: 3792.4922
Epoch 73/1000: Train Loss: 3791.0044
Epoch 74/1000: Train Loss: 3799.8748
Epoch 75/1000: Train Loss: 3778.7688
Epoch 76/1000: Train Loss: 3787.6941
Epoch 77/1000: Train Loss: 3793.6206
Epoch 78/1000: Train Loss: 3789.8386
Epoch 79/1000: Train Loss: 3788.2432
Epoch 80/1000: Train Loss: 3787.6389
Epoch 81/1000: Train Loss: 3794.9048
Epoch 82/1000: Train Loss: 3777.7803
Epoch 83/1000: Train Loss: 3783.9382
Epoch 84/1000: Train Loss: 3784.7397
Epoch 85/1000: Train Loss: 3796.3770
Epoch 86/1000: Train Loss: 3802.1472
Epoch 87/1000: Train Loss: 3789.8130
Epoch 88/1000: Train Loss: 3794.0613
Epoch 89/1000: Train Loss: 3811.5950
Epoch 90/1000: Train Loss: 3777.1592
Epoch 91/1000: Train Loss: 3779.1523
Epoch 92/1000: Train Loss: 3785.8701
Epoch 93/1000: Train Loss: 3776.6853
Epoch 94/1000: Train Loss: 3786.9045
Epoch 95/1000: Train Loss: 3781.9526
Epoch 96/1000: Train Loss: 3782.9663
Epoch 97/1000: Train Loss: 3789.5745
Epoch 98/1000: Train Loss: 3795.4541
Epoch 99/1000: Train Loss: 3782.7815
Epoch 100/1000: Train Loss: 3780.5867
Epoch 101/1000: Train Loss: 3778.8718
Epoch 102/1000: Train Loss: 3778.2275
Epoch 103/1000: Train Loss: 3779.0288
Epoch 104/1000: Train Loss: 3777.8591
Epoch 105/1000: Train Loss: 3792.7627
Epoch 106/1000: Train Loss: 3770.8362
Epoch 107/1000: Train Loss: 3780.7297
Epoch 108/1000: Train Loss: 3775.4919
Epoch 109/1000: Train Loss: 3777.5608
Epoch 110/1000: Train Loss: 3776.8972
Epoch 111/1000: Train Loss: 3768.2754
Epoch 112/1000: Train Loss: 3761.5728
Epoch 113/1000: Train Loss: 3778.1899
Epoch 114/1000: Train Loss: 3772.0471
Epoch 115/1000: Train Loss: 3784.4624
Epoch 116/1000: Train Loss: 3789.7029
Epoch 117/1000: Train Loss: 3782.6943
Epoch 118/1000: Train Loss: 3770.6770
Epoch 119/1000: Train Loss: 3772.4021
Epoch 120/1000: Train Loss: 3770.3364
Epoch 121/1000: Train Loss: 3766.0669
Epoch 122/1000: Train Loss: 3775.2454
Epoch 123/1000: Train Loss: 3768.8762
Epoch 124/1000: Train Loss: 3770.0955
Epoch 125/1000: Train Loss: 3764.6973
Epoch 126/1000: Train Loss: 3780.8391
Epoch 127/1000: Train Loss: 3772.4744
Epoch 128/1000: Train Loss: 3775.5876
Epoch 129/1000: Train Loss: 3772.8555
Epoch 130/1000: Train Loss: 3768.7085
Epoch 131/1000: Train Loss: 3770.7573
Epoch 132/1000: Train Loss: 3766.7285
Epoch 133/1000: Train Loss: 3775.0859
Epoch 134/1000: Train Loss: 3792.5586
Epoch 135/1000: Train Loss: 3766.7114
Epoch 136/1000: Train Loss: 3762.7034
Epoch 137/1000: Train Loss: 3769.2578
Epoch 138/1000: Train Loss: 3772.6409
Epoch 139/1000: Train Loss: 3759.9373
Epoch 140/1000: Train Loss: 3769.3523
Epoch 141/1000: Train Loss: 3766.3848
Epoch 142/1000: Train Loss: 3764.2598
Epoch 143/1000: Train Loss: 3770.6724
Epoch 144/1000: Train Loss: 3759.8503
Epoch 145/1000: Train Loss: 3768.6938
Epoch 146/1000: Train Loss: 3761.8064
Epoch 147/1000: Train Loss: 3762.5659
Epoch 148/1000: Train Loss: 3776.6973
Epoch 149/1000: Train Loss: 3754.5549
Epoch 150/1000: Train Loss: 3764.2590
Epoch 151/1000: Train Loss: 3750.5774
Epoch 152/1000: Train Loss: 3767.1946
Epoch 153/1000: Train Loss: 3784.8330
Epoch 154/1000: Train Loss: 3763.2634
Epoch 155/1000: Train Loss: 3765.0366
Epoch 156/1000: Train Loss: 3763.6797
Epoch 157/1000: Train Loss: 3768.1160
Epoch 158/1000: Train Loss: 3750.8096
Epoch 159/1000: Train Loss: 3762.6299
Epoch 160/1000: Train Loss: 3769.0649
Epoch 161/1000: Train Loss: 3765.0181
Epoch 162/1000: Train Loss: 3753.2051
Epoch 163/1000: Train Loss: 3782.5518
Epoch 164/1000: Train Loss: 3754.0989
Epoch 165/1000: Train Loss: 3762.5754
Epoch 166/1000: Train Loss: 3766.0190
Epoch 167/1000: Train Loss: 3761.5583
Epoch 168/1000: Train Loss: 3775.6138
Epoch 169/1000: Train Loss: 3751.0388
Epoch 170/1000: Train Loss: 3760.1309
Epoch 171/1000: Train Loss: 3753.8276
Epoch 172/1000: Train Loss: 3755.6882
Epoch 173/1000: Train Loss: 3745.2188
Epoch 174/1000: Train Loss: 3754.6738
Epoch 175/1000: Train Loss: 3745.5088
Epoch 176/1000: Train Loss: 3762.6372
Epoch 177/1000: Train Loss: 3761.1873
Epoch 178/1000: Train Loss: 3748.8027
Epoch 179/1000: Train Loss: 3757.9617
Epoch 180/1000: Train Loss: 3750.2554
Epoch 181/1000: Train Loss: 3740.7415
Epoch 182/1000: Train Loss: 3752.5684
Epoch 183/1000: Train Loss: 3759.8503
Epoch 184/1000: Train Loss: 3743.4736
Epoch 185/1000: Train Loss: 3752.2378
Epoch 186/1000: Train Loss: 3756.0884
Epoch 187/1000: Train Loss: 3754.3384
Epoch 188/1000: Train Loss: 3745.7854
Epoch 189/1000: Train Loss: 3750.7549
Epoch 190/1000: Train Loss: 3756.2612
Epoch 191/1000: Train Loss: 3751.5645
Epoch 192/1000: Train Loss: 3771.7810
Epoch 193/1000: Train Loss: 3753.2188
Epoch 194/1000: Train Loss: 3760.6987
Epoch 195/1000: Train Loss: 3762.1699
Epoch 196/1000: Train Loss: 3749.2405
Epoch 197/1000: Train Loss: 3755.6694
Epoch 198/1000: Train Loss: 3739.0771
Epoch 199/1000: Train Loss: 3745.0303
Epoch 200/1000: Train Loss: 3759.2837
Epoch 201/1000: Train Loss: 3755.1990
Epoch 202/1000: Train Loss: 3755.6738
Epoch 203/1000: Train Loss: 3767.1343
Epoch 204/1000: Train Loss: 3744.9878
Epoch 205/1000: Train Loss: 3758.9856
Epoch 206/1000: Train Loss: 3744.4834
Epoch 207/1000: Train Loss: 3747.8918
Epoch 208/1000: Train Loss: 3770.6917
Epoch 209/1000: Train Loss: 3755.9075
Epoch 210/1000: Train Loss: 3747.2048
Epoch 211/1000: Train Loss: 3756.0085
Epoch 212/1000: Train Loss: 3760.0061
Epoch 213/1000: Train Loss: 3746.4224
Epoch 214/1000: Train Loss: 3747.9609
Epoch 215/1000: Train Loss: 3748.1836
Epoch 216/1000: Train Loss: 3741.0049
Epoch 217/1000: Train Loss: 3765.0974
Epoch 218/1000: Train Loss: 3748.0525
Epoch 219/1000: Train Loss: 3743.9280
Epoch 220/1000: Train Loss: 3738.6621
Epoch 221/1000: Train Loss: 3743.9778
Epoch 222/1000: Train Loss: 3753.2576
Epoch 223/1000: Train Loss: 3747.9934
Epoch 224/1000: Train Loss: 3745.3503
Epoch 225/1000: Train Loss: 3740.5107
Epoch 226/1000: Train Loss: 3740.0701
Epoch 227/1000: Train Loss: 3748.0872
Epoch 228/1000: Train Loss: 3743.2188
Epoch 229/1000: Train Loss: 3756.1682
Epoch 230/1000: Train Loss: 3742.9075
Epoch 231/1000: Train Loss: 3747.5120
Epoch 232/1000: Train Loss: 3745.8643
Epoch 233/1000: Train Loss: 3740.8315
Epoch 234/1000: Train Loss: 3751.1980
Epoch 235/1000: Train Loss: 3748.5361
Epoch 236/1000: Train Loss: 3743.6841
Epoch 237/1000: Train Loss: 3744.2163
Epoch 238/1000: Train Loss: 3748.6318
Epoch 239/1000: Train Loss: 3736.3313
Epoch 240/1000: Train Loss: 3735.1309
Epoch 241/1000: Train Loss: 3749.1926
Epoch 242/1000: Train Loss: 3754.4941
Epoch 243/1000: Train Loss: 3773.5500
Epoch 244/1000: Train Loss: 3748.4490
Epoch 245/1000: Train Loss: 3769.2388
Epoch 246/1000: Train Loss: 3747.8723
Epoch 247/1000: Train Loss: 3768.4812
Epoch 248/1000: Train Loss: 3747.9490
Epoch 249/1000: Train Loss: 3753.7573
Epoch 250/1000: Train Loss: 3750.9922
Epoch 251/1000: Train Loss: 3749.3218
Epoch 252/1000: Train Loss: 3761.5928
Epoch 253/1000: Train Loss: 3755.8154
Epoch 254/1000: Train Loss: 3757.8562
Epoch 255/1000: Train Loss: 3753.8025
Epoch 256/1000: Train Loss: 3743.2529
Epoch 257/1000: Train Loss: 3747.1096
Epoch 258/1000: Train Loss: 3736.0247
Epoch 259/1000: Train Loss: 3752.4844
Epoch 260/1000: Train Loss: 3743.8115
Epoch 261/1000: Train Loss: 3740.4443
Epoch 262/1000: Train Loss: 3768.1526
Epoch 263/1000: Train Loss: 3734.0420
Epoch 264/1000: Train Loss: 3748.2065
Epoch 265/1000: Train Loss: 3755.4727
Epoch 266/1000: Train Loss: 3748.6968
Epoch 267/1000: Train Loss: 3740.4094
Epoch 268/1000: Train Loss: 3752.7402
Epoch 269/1000: Train Loss: 3754.7893
Epoch 270/1000: Train Loss: 3744.7046
Epoch 271/1000: Train Loss: 3743.9536
Epoch 272/1000: Train Loss: 3756.7903
Epoch 273/1000: Train Loss: 3743.8474
Epoch 274/1000: Train Loss: 3745.2930
Epoch 275/1000: Train Loss: 3745.9163
Epoch 276/1000: Train Loss: 3750.8713
Epoch 277/1000: Train Loss: 3747.6467
Epoch 278/1000: Train Loss: 3746.1621
Epoch 279/1000: Train Loss: 3749.0823
Epoch 280/1000: Train Loss: 3750.7170
Epoch 281/1000: Train Loss: 3746.0894
Epoch 282/1000: Train Loss: 3742.1653
Epoch 283/1000: Train Loss: 3744.9827
Epoch 284/1000: Train Loss: 3744.4272
Epoch 285/1000: Train Loss: 3753.0664
Epoch 286/1000: Train Loss: 3741.2397
Epoch 287/1000: Train Loss: 3742.6921
Epoch 288/1000: Train Loss: 3739.9697
Epoch 289/1000: Train Loss: 3747.4927
Epoch 290/1000: Train Loss: 3738.8979
Epoch 291/1000: Train Loss: 3743.3311
Epoch 292/1000: Train Loss: 3737.8167
Epoch 293/1000: Train Loss: 3735.9104
Epoch 294/1000: Train Loss: 3733.6924
Epoch 295/1000: Train Loss: 3732.2915
Epoch 296/1000: Train Loss: 3744.3779
Epoch 297/1000: Train Loss: 3737.0103
Epoch 298/1000: Train Loss: 3738.1997
Epoch 299/1000: Train Loss: 3744.7031
Epoch 300/1000: Train Loss: 3746.3145
Epoch 301/1000: Train Loss: 3733.3474
Epoch 302/1000: Train Loss: 3746.8999
Epoch 303/1000: Train Loss: 3736.2014
Epoch 304/1000: Train Loss: 3735.5212
Epoch 305/1000: Train Loss: 3736.9932
Epoch 306/1000: Train Loss: 3731.8064
Epoch 307/1000: Train Loss: 3736.4944
Epoch 308/1000: Train Loss: 3748.7795
Epoch 309/1000: Train Loss: 3738.4001
Epoch 310/1000: Train Loss: 3738.5842
Epoch 311/1000: Train Loss: 3732.9246
Epoch 312/1000: Train Loss: 3747.7146
Epoch 313/1000: Train Loss: 3740.9910
Epoch 314/1000: Train Loss: 3739.6670
Epoch 315/1000: Train Loss: 3764.3293
Epoch 316/1000: Train Loss: 3742.9465
Epoch 317/1000: Train Loss: 3743.2791
Epoch 318/1000: Train Loss: 3751.0010
Epoch 319/1000: Train Loss: 3742.7100
Epoch 320/1000: Train Loss: 3732.9756
Epoch 321/1000: Train Loss: 3737.6680
Epoch 322/1000: Train Loss: 3740.7939
Epoch 323/1000: Train Loss: 3738.9495
Epoch 324/1000: Train Loss: 3743.2664
Epoch 325/1000: Train Loss: 3735.5876
Epoch 326/1000: Train Loss: 3733.1877
Epoch 327/1000: Train Loss: 3731.0164
Epoch 328/1000: Train Loss: 3730.8306
Epoch 329/1000: Train Loss: 3747.5488
Epoch 330/1000: Train Loss: 3735.1172
Epoch 331/1000: Train Loss: 3739.2434
Epoch 332/1000: Train Loss: 3728.4629
Epoch 333/1000: Train Loss: 3732.6746
Epoch 334/1000: Train Loss: 3740.7112
Epoch 335/1000: Train Loss: 3741.8914
Epoch 336/1000: Train Loss: 3736.5435
Epoch 337/1000: Train Loss: 3732.4541
Epoch 338/1000: Train Loss: 3727.1826
Epoch 339/1000: Train Loss: 3730.8958
Epoch 340/1000: Train Loss: 3731.9570
Epoch 341/1000: Train Loss: 3729.9993
Epoch 342/1000: Train Loss: 3733.2415
Epoch 343/1000: Train Loss: 3736.1086
Epoch 344/1000: Train Loss: 3742.4072
Epoch 345/1000: Train Loss: 3745.9883
Epoch 346/1000: Train Loss: 3742.6982
Epoch 347/1000: Train Loss: 3725.5579
Epoch 348/1000: Train Loss: 3727.3201
Epoch 349/1000: Train Loss: 3746.5317
Epoch 350/1000: Train Loss: 3737.2830
Epoch 351/1000: Train Loss: 3732.5994
Epoch 352/1000: Train Loss: 3728.7334
Epoch 353/1000: Train Loss: 3784.2598
Epoch 354/1000: Train Loss: 3741.6990
Epoch 355/1000: Train Loss: 3740.4961
Epoch 356/1000: Train Loss: 3724.3669
Epoch 357/1000: Train Loss: 3738.8550
Epoch 358/1000: Train Loss: 3733.4592
Epoch 359/1000: Train Loss: 3737.7578
Epoch 360/1000: Train Loss: 3733.1289
Epoch 361/1000: Train Loss: 3728.8623
Epoch 362/1000: Train Loss: 3735.8625
Epoch 363/1000: Train Loss: 3737.3276
Epoch 364/1000: Train Loss: 3738.4407
Epoch 365/1000: Train Loss: 3734.1389
Epoch 366/1000: Train Loss: 3727.3523
Epoch 367/1000: Train Loss: 3734.2925
Epoch 368/1000: Train Loss: 3733.3503
Epoch 369/1000: Train Loss: 3730.2805
Epoch 370/1000: Train Loss: 3736.7085
Epoch 371/1000: Train Loss: 3724.8171
Epoch 372/1000: Train Loss: 3732.9922
Epoch 373/1000: Train Loss: 3733.6484
Epoch 374/1000: Train Loss: 3724.6516
Epoch 375/1000: Train Loss: 3732.5566
Epoch 376/1000: Train Loss: 3722.8640
Epoch 377/1000: Train Loss: 3732.1768
Epoch 378/1000: Train Loss: 3736.7593
Epoch 379/1000: Train Loss: 3730.3044
Epoch 380/1000: Train Loss: 3721.5095
Epoch 381/1000: Train Loss: 3733.0127
Epoch 382/1000: Train Loss: 3730.4282
Epoch 383/1000: Train Loss: 3744.5396
Epoch 384/1000: Train Loss: 3722.3997
Epoch 385/1000: Train Loss: 3727.4214
Epoch 386/1000: Train Loss: 3730.7322
Epoch 387/1000: Train Loss: 3732.4143
Epoch 388/1000: Train Loss: 3733.5403
Epoch 389/1000: Train Loss: 3727.6863
Epoch 390/1000: Train Loss: 3725.7458
Epoch 391/1000: Train Loss: 3730.8882
Epoch 392/1000: Train Loss: 3736.5918
Epoch 393/1000: Train Loss: 3726.4094
Epoch 394/1000: Train Loss: 3737.9006
Epoch 395/1000: Train Loss: 3734.4001
Epoch 396/1000: Train Loss: 3725.7354
Epoch 397/1000: Train Loss: 3729.7007
Epoch 398/1000: Train Loss: 3721.1172
Epoch 399/1000: Train Loss: 3729.8486
Epoch 400/1000: Train Loss: 3785.2478
Epoch 401/1000: Train Loss: 3735.8511
Epoch 402/1000: Train Loss: 3749.6545
Epoch 403/1000: Train Loss: 3738.4380
Epoch 404/1000: Train Loss: 3736.4866
Epoch 405/1000: Train Loss: 3729.7556
Epoch 406/1000: Train Loss: 3748.7820
Epoch 407/1000: Train Loss: 3740.9099
Epoch 408/1000: Train Loss: 3730.5574
Epoch 409/1000: Train Loss: 3733.9790
Epoch 410/1000: Train Loss: 3727.4136
Epoch 411/1000: Train Loss: 3727.4932
Epoch 412/1000: Train Loss: 3735.1245
Epoch 413/1000: Train Loss: 3751.3706
Epoch 414/1000: Train Loss: 3728.5601
Epoch 415/1000: Train Loss: 3735.7239
Epoch 416/1000: Train Loss: 3731.9915
Epoch 417/1000: Train Loss: 3727.9832
Epoch 418/1000: Train Loss: 3740.2224
Epoch 419/1000: Train Loss: 3736.1301
Epoch 420/1000: Train Loss: 3724.4492
Epoch 421/1000: Train Loss: 3723.2173
Epoch 422/1000: Train Loss: 3726.2253
Epoch 423/1000: Train Loss: 3733.5271
Epoch 424/1000: Train Loss: 3726.6829
Epoch 425/1000: Train Loss: 3746.9727
Epoch 426/1000: Train Loss: 3735.2632
Epoch 427/1000: Train Loss: 3732.5505
Epoch 428/1000: Train Loss: 3727.6660
Epoch 429/1000: Train Loss: 3722.0769
Epoch 430/1000: Train Loss: 3728.8196
Epoch 431/1000: Train Loss: 3719.1421
Epoch 432/1000: Train Loss: 3736.7239
Epoch 433/1000: Train Loss: 3794.4358
Epoch 434/1000: Train Loss: 3736.3669
Epoch 435/1000: Train Loss: 3732.5969
Epoch 436/1000: Train Loss: 3726.7246
Epoch 437/1000: Train Loss: 3734.4529
Epoch 438/1000: Train Loss: 3735.8459
Epoch 439/1000: Train Loss: 3732.5015
Epoch 440/1000: Train Loss: 3736.8037
Epoch 441/1000: Train Loss: 3750.2920
Epoch 442/1000: Train Loss: 3733.4810
Epoch 443/1000: Train Loss: 3724.7683
Epoch 444/1000: Train Loss: 3753.9238
Epoch 445/1000: Train Loss: 3729.7402
Epoch 446/1000: Train Loss: 3733.6897
Epoch 447/1000: Train Loss: 3730.7830
Epoch 448/1000: Train Loss: 3750.6274
Epoch 449/1000: Train Loss: 3727.0940
Epoch 450/1000: Train Loss: 3734.8191
Epoch 451/1000: Train Loss: 3757.7190
Epoch 452/1000: Train Loss: 3730.7852
Epoch 453/1000: Train Loss: 3730.6711
Epoch 454/1000: Train Loss: 3745.0103
Epoch 455/1000: Train Loss: 3726.3484
Epoch 456/1000: Train Loss: 3730.0369
Epoch 457/1000: Train Loss: 3775.9692
Epoch 458/1000: Train Loss: 3735.1497
Epoch 459/1000: Train Loss: 3725.6948
Epoch 460/1000: Train Loss: 3738.7263
Epoch 461/1000: Train Loss: 3730.9258
Epoch 462/1000: Train Loss: 3733.3450
Epoch 463/1000: Train Loss: 3726.3394
Epoch 464/1000: Train Loss: 3741.1731
Epoch 465/1000: Train Loss: 3746.7466
Epoch 466/1000: Train Loss: 3746.7649
Epoch 467/1000: Train Loss: 3732.3291
Epoch 468/1000: Train Loss: 3731.7234
Epoch 469/1000: Train Loss: 3730.0444
Epoch 470/1000: Train Loss: 3737.8364
Epoch 471/1000: Train Loss: 3731.2805
Epoch 472/1000: Train Loss: 3721.8735
Epoch 473/1000: Train Loss: 3735.2351
Epoch 474/1000: Train Loss: 3727.6187
Epoch 475/1000: Train Loss: 3726.5464
Epoch 476/1000: Train Loss: 3731.8931
Epoch 477/1000: Train Loss: 3730.6704
Epoch 478/1000: Train Loss: 3722.5933
Epoch 479/1000: Train Loss: 3740.4922
Epoch 480/1000: Train Loss: 3731.8667
Epoch 481/1000: Train Loss: 3725.0449
Epoch 482/1000: Train Loss: 3732.2588
Epoch 483/1000: Train Loss: 3727.2039
Epoch 484/1000: Train Loss: 3723.5696
Epoch 485/1000: Train Loss: 3726.9094
Epoch 486/1000: Train Loss: 3723.8618
Epoch 487/1000: Train Loss: 3726.2910
Epoch 488/1000: Train Loss: 3730.0493
Epoch 489/1000: Train Loss: 3722.0901
Epoch 490/1000: Train Loss: 3715.0930
Epoch 491/1000: Train Loss: 3723.8579
Epoch 492/1000: Train Loss: 3727.8047
Epoch 493/1000: Train Loss: 3723.8374
Epoch 494/1000: Train Loss: 3718.2334
Epoch 495/1000: Train Loss: 3718.6497
Epoch 496/1000: Train Loss: 3721.1545
Epoch 497/1000: Train Loss: 3730.6426
Epoch 498/1000: Train Loss: 3731.4421
Epoch 499/1000: Train Loss: 3748.9700
Epoch 500/1000: Train Loss: 3713.5796
Epoch 501/1000: Train Loss: 3731.0215
Epoch 502/1000: Train Loss: 3722.8552
Epoch 503/1000: Train Loss: 3721.3726
Epoch 504/1000: Train Loss: 3725.0474
Epoch 505/1000: Train Loss: 3730.7188
Epoch 506/1000: Train Loss: 3719.9685
Epoch 507/1000: Train Loss: 3718.5369
Epoch 508/1000: Train Loss: 3752.3728
Epoch 509/1000: Train Loss: 3711.8718
Epoch 510/1000: Train Loss: 3717.0232
Epoch 511/1000: Train Loss: 3733.2537
Epoch 512/1000: Train Loss: 3731.9543
Epoch 513/1000: Train Loss: 3715.8613
Epoch 514/1000: Train Loss: 3731.0845
Epoch 515/1000: Train Loss: 3731.0723
Epoch 516/1000: Train Loss: 3724.1123
Epoch 517/1000: Train Loss: 3722.1304
Epoch 518/1000: Train Loss: 3732.6440
Epoch 519/1000: Train Loss: 3720.0532
Epoch 520/1000: Train Loss: 3728.8352
Epoch 521/1000: Train Loss: 3722.5554
Epoch 522/1000: Train Loss: 3726.1694
Epoch 523/1000: Train Loss: 3715.5247
Epoch 524/1000: Train Loss: 3725.7778
Epoch 525/1000: Train Loss: 3722.3003
Epoch 526/1000: Train Loss: 3733.8169
Epoch 527/1000: Train Loss: 3729.6394
Epoch 528/1000: Train Loss: 3722.2639
Epoch 529/1000: Train Loss: 3729.0930

In [13]:
go.Figure(
    data=[
        go.Scatter(
            x=list(range(len(train_losses))),
            y=train_losses,
            name="Train Loss",
            mode="lines",
        ),
        go.Scatter(
            x=list(range(len(val_losses))),
            y=val_losses,
            name="Validation Loss",
            mode="lines",
        ),
    ],
    layout=go.Layout(
        title="Training and Validation Loss",
        xaxis=dict(title="Epoch"),
        yaxis=dict(title="Loss"),
    ),
)

In [14]:
# retrieve users latent representations (mean and variance)
usersnames = matrix_mf.get_usernames()

model.eval()
with torch.no_grad():
    mu, logvar = model.encode(user_interacted_with)
    z = model.reparameterize(mu, logvar)
    z = z.cpu().numpy()
    mu = mu.cpu().numpy()
    std = np.exp(0.5 * logvar.cpu().numpy())
    logvar = logvar.cpu().numpy()

print(z)
print(mu)
print(logvar)

[[ 0.38791552 -0.3356129  -0.36279678 ...  0.21034864 -0.652727
   0.73466605]
 [ 0.34460232  0.5198928  -0.23736435 ... -0.18044353 -0.08430137
  -0.05968325]
 [ 0.37243858 -0.27983394  0.36257616 ... -0.15310022  0.52561784
  -0.02193665]
 ...
 [-0.39632425  0.03191594 -0.00384138 ...  0.18850668 -0.51583374
  -0.65912867]
 [ 0.21524253 -0.02846021 -0.25904062 ...  0.29879734  0.26102725
  -0.415601  ]
 [-0.30007997 -0.04083337  0.30987248 ...  0.0309695  -0.00379538
   0.25391623]]
[[ 0.38791552 -0.3356129  -0.36279678 ...  0.21034864 -0.652727
   0.73466605]
 [ 0.34460232  0.5198928  -0.23736435 ... -0.18044353 -0.08430137
  -0.05968325]
 [ 0.37243858 -0.27983394  0.36257616 ... -0.15310022  0.52561784
  -0.02193665]
 ...
 [-0.39632425  0.03191594 -0.00384138 ...  0.18850668 -0.51583374
  -0.65912867]
 [ 0.21524253 -0.02846021 -0.25904062 ...  0.29879734  0.26102725
  -0.415601  ]
 [-0.30007997 -0.04083337  0.30987248 ...  0.0309695  -0.00379538
   0.25391623]]
[[-0.13494131 -0.2286918  -0.14782423 ... -0.16435939 -0.22577633
  -0.3080078 ]
 [-0.09176952  0.13952719 -0.07411837 ... -0.07514133 -0.16670151
  -0.00966816]
 [-0.2818047  -0.16631204 -0.15765542 ... -0.15419441 -0.15727422
  -0.20981732]
 ...
 [-0.1065938  -0.22410676 -0.17614365 ... -0.09279343 -0.13165657
   0.05901126]
 [ 0.03653962 -0.13345197  0.04285868 ... -0.27603486 -0.21037379
  -0.32108006]
 [ 0.14213847  0.00242577 -0.10420271 ... -0.12594315 -0.24824946
  -0.17546266]]

In [15]:
# Define the number of points for grid, the width of the gaussian curves and color map
if encoder_dims[-1] == 2:
        # Plot 2D latent space using and add annotations with usernames
    fig = px.scatter(x=z[:, 0], y=z[:, 1], hover_name=usersnames, color=usersnames)
    fig.update_traces(marker=dict(size=10))
    fig.update_layout(title="2D Latent Space")
    # Show the usernames next to the points
    for i, username in enumerate(usersnames):
        fig.add_annotation(
            x=z[i, 0], y=z[i, 1], text=username, showarrow=False, xshift=-20, yshift=15
        )
    fig.show()
    
    plotting.plot_multivariate_gaussian_image_with_labels(mu, std, usersnames)

In [23]:
user = "paul"
user_idx = matrix_mf.usernames_to_ids([user])[0]
user_data = matrix_mf.get_user(user_idx).to(device).unsqueeze(0)
user_interacted_with = matrix_mf.user_interacted_with(user_idx)

recommended_items_ids = model.recommend_items(user_data, user_interacted_with, top_k=10)
recommended_items_ids

recommended_items = matrix_mf.ids_to_itemnames(recommended_items_ids)
df_recommended_items = df_matrix_mf[df_matrix_mf["id"].isin(recommended_items)]
df_recommended_items[spoti.PRETTY_PRINT_FEATURES]

,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
1516,owen,Hamza,Free YSL,2023,62,0.907,0.577,0.0574,0.063400,0.000010,0.1580,0.459,125.981,-8.146,186253,2023,62
1519,owen,Doja Cat,Agora Hills,2023,91,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.392,123.026,-6.128,265360,2023,91
1522,owen,BabySolo33,LnlyBby,2022,30,0.708,0.300,0.0752,0.410000,0.320000,0.1030,0.260,95.018,-12.861,174147,2022,30
1523,owen,BabySolo33,BFF <3,2022,28,0.845,0.280,0.1410,0.295000,0.001040,0.0896,0.527,120.031,-12.457,193654,2022,28
1528,owen,betcover!!,海豚少年 - アルバムバージョン,2019,21,0.681,0.708,0.0912,0.117000,0.011000,0.1000,0.324,100.386,-7.375,293733,2019,21
1533,owen,YG Pablo,22h22,2023,60,0.737,0.506,0.1310,0.747000,0.000130,0.1020,0.320,129.910,-11.587,191066,2023,60
1547,owen,Troye Sivan,One Of Your Girls,2023,88,0.629,0.654,0.0584,0.087800,0.006550,0.2200,0.799,93.034,-7.852,181481,2023,88
1551,owen,Dosseh,Macabre,2023,56,0.815,0.648,0.3030,0.559000,0.000000,0.1080,0.707,140.043,-6.465,208841,2023,56
1555,owen,YG Pablo,22h22,2023,60,0.737,0.506,0.1310,0.747000,0.000130,0.1020,0.320,129.910,-11.587,191066,2023,60
1556,owen,betcover!!,海豚少年 - アルバムバージョン,2019,21,0.681,0.708,0.0912,0.117000,0.011000,0.1000,0.324,100.386,-7.375,293733,2019,21
1560,owen,Troye Sivan,One Of Your Girls,2023,88,0.629,0.654,0.0584,0.087800,0.006550,0.2200,0.799,93.034,-7.852,181481,2023,88
1561,owen,Dosseh,Macabre,2023,56,0.815,0.648,0.3030,0.559000,0.000000,0.1080,0.707,140.043,-6.465,208841,2023,56
1583,owen,Doja Cat,Agora Hills,2023,91,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.392,123.026,-6.128,265360,2023,91
1585,owen,Jason Mraz,I'm Yours,2008,80,0.703,0.444,0.0417,0.559000,0.000000,0.0973,0.712,150.960,-9.331,242946,2008,80
1619,owen,The 1975,Robbers,2013,74,0.621,0.692,0.0291,0.000363,0.000017,0.3350,0.381,99.806,-6.858,254509,2013,74