In [1]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from recommenders.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float64

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [3]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.98,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.96,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.94,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.92,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [4]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100

In [5]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity")
R = torch.tensor(matrix_mf.R, dtype=dtype, device=device)
R

tensor([[ 0.,  0., 62.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0., 54.],
        ...,
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [44., 60.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ..., 92.,  0.,  0.]], device='mps:0')

In [6]:
alpha = matrix_mf.compute_alpha()
R *= alpha
alpha

0.13540265635507734

In [7]:
lmf = LogisticMatrixFactorization(
    R=R,
    num_factors=3,
    alpha=alpha,
    lambd=0.01,
    device=device,
    dtype=dtype,
)

num_epochs = 1000
lmf.train_with_gradients(
    num_epochs=num_epochs,
    learning_rate=0.01,
    log_interval=10,
)

Epoch 1: loss = 4347.703125, MPR = 0.4925605058670044
Epoch 11: loss = 3938.254638671875, MPR = 0.47927209734916687
Epoch 21: loss = 3790.806640625, MPR = 0.4692744314670563
Epoch 31: loss = 3673.7470703125, MPR = 0.45993542671203613
Epoch 41: loss = 3576.69482421875, MPR = 0.4515012800693512
Epoch 51: loss = 3494.406982421875, MPR = 0.4434061646461487
Epoch 61: loss = 3423.61181640625, MPR = 0.4354008436203003
Epoch 71: loss = 3362.043212890625, MPR = 0.42772936820983887
Epoch 81: loss = 3308.036376953125, MPR = 0.42047563195228577
Epoch 91: loss = 3260.319580078125, MPR = 0.41344597935676575
Epoch 101: loss = 3217.894775390625, MPR = 0.40692228078842163
Epoch 111: loss = 3179.962890625, MPR = 0.4005732536315918
Epoch 121: loss = 3145.873291015625, MPR = 0.39454859495162964
Epoch 131: loss = 3115.089599609375, MPR = 0.3887907862663269
Epoch 141: loss = 3087.16552734375, MPR = 0.3834521174430847
Epoch 151: loss = 3061.725830078125, MPR = 0.37837544083595276
Epoch 161: loss = 3038.452880859375, MPR = 0.3736145794391632
Epoch 171: loss = 3017.077392578125, MPR = 0.3691646158695221
Epoch 181: loss = 2997.36767578125, MPR = 0.3649773597717285
Epoch 191: loss = 2979.125, MPR = 0.3609517812728882
Epoch 201: loss = 2962.17822265625, MPR = 0.3572104871273041
Epoch 211: loss = 2946.379638671875, MPR = 0.35384026169776917
Epoch 221: loss = 2931.600830078125, MPR = 0.3506559133529663
Epoch 231: loss = 2917.729736328125, MPR = 0.3475356698036194

In [ ]:
lmf.save("models", "lmf_3")
lmf = LogisticMatrixFactorization.load(os.path.join("models", "lmf_3.pt"))

In [ ]:
px.line(x=range(len(lmf.mprs)), y=lmf.mprs.cpu()).show()
px.line(x=range(len(lmf.losses)), y=lmf.losses.cpu()).show()

In [ ]:
user_id = matrix_mf.usernames_to_ids(["paul"])[0]

# Get the top 10 recommendations for the user
top_10_ids, top_10_ids_scores = lmf.recommend(user_id, top_k=20, filter_user_items=True)

# Get the top 10 recommendations for the user
matrix_mf.items_ids_to_df(top_10_ids)[spoti.PRETTY_PRINT_FEATURES]

,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
0,jaslkh,ROSALÍA,PROMESA,2023,63,0.630,0.374,0.2270,0.86100,0.000075,0.2940,0.3730,104.955,-9.007,196426,2023,63
50,jaslkh,Jain,Makeba,2016,80,0.824,0.656,0.0704,0.38800,0.506000,0.2530,0.4180,116.068,-9.432,249533,2016,80
1605,owen,Josman,Goal,2021,50,0.822,0.590,0.4200,0.46200,0.000000,0.0904,0.5530,113.963,-8.981,281052,2021,50
1614,owen,Iliona,micha,2022,49,0.795,0.417,0.0364,0.67900,0.573000,0.1090,0.4460,121.989,-12.028,233413,2022,49
1615,owen,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.63200,0.001190,0.1030,0.4650,105.011,-9.535,176026,2022,59
1616,owen,Iliona,Garçon manqué,2022,46,0.822,0.399,0.0381,0.69300,0.101000,0.1030,0.3990,119.981,-9.382,211386,2022,46
6967,brenda,Angèle,Oui ou non,2019,62,0.649,0.574,0.1430,0.63500,0.000013,0.1610,0.3610,199.906,-7.856,196800,2019,62
6970,brenda,Taylor Swift,I Knew You Were Trouble.,2012,82,0.622,0.469,0.0363,0.00454,0.000002,0.0335,0.6790,77.019,-6.798,219720,2012,82
6980,brenda,Imagine Dragons,Bones,2022,86,0.772,0.750,0.0455,0.02010,0.000000,0.0740,0.5870,114.061,-3.670,165264,2022,86
6981,brenda,Imagine Dragons,Enemy (with JID) - from the series Arcane Leag...,2021,81,0.728,0.783,0.2660,0.23700,0.000000,0.4340,0.5550,77.011,-4.424,173381,2021,81
6985,brenda,Clean Bandit,Rather Be (feat. Jess Glynne),2014,76,0.799,0.586,0.0377,0.16200,0.000002,0.1930,0.5490,120.970,-6.735,227833,2014,76
6998,brenda,Sóley,Smashed Birds,2011,33,0.670,0.255,0.0408,0.90200,0.000218,0.1090,0.5310,109.999,-15.223,222714,2011,33
7002,brenda,Of Monsters and Men,King And Lionheart,2012,64,0.520,0.655,0.0394,0.10500,0.003840,0.1240,0.2900,126.593,-6.519,273853,2012,64
7014,brenda,Agnes Obel,Avenue,2010,40,0.539,0.273,0.0256,0.97000,0.011700,0.1220,0.1190,149.885,-11.350,247000,2010,40
7016,brenda,Clean Bandit,Rather Be (feat. Jess Glynne),2014,76,0.799,0.586,0.0377,0.16200,0.000002,0.1930,0.5490,120.970,-6.735,227833,2014,76
7018,brenda,Sóley,Smashed Birds,2011,33,0.670,0.255,0.0408,0.90200,0.000218,0.1090,0.5310,109.999,-15.223,222714,2011,33
7021,brenda,Of Monsters and Men,King And Lionheart,2012,64,0.520,0.655,0.0394,0.10500,0.003840,0.1240,0.2900,126.593,-6.519,273853,2012,64
7028,brenda,Agnes Obel,Avenue,2010,40,0.539,0.273,0.0256,0.97000,0.011700,0.1220,0.1190,149.885,-11.350,247000,2010,40
7066,brenda,Imagine Dragons,Enemy (with JID) - from the series Arcane Leag...,2021,81,0.728,0.783,0.2660,0.23700,0.000000,0.4340,0.5550,77.011,-4.424,173381,2021,81
7067,brenda,Imagine Dragons,Bones,2022,86,0.772,0.750,0.0455,0.02010,0.000000,0.0740,0.5870,114.061,-3.670,165264,2022,86
7387,arthur,M83,Laura,2023,46,0.418,0.689,0.0287,0.00319,0.122000,0.0946,0.2230,143.883,-5.694,248133,2023,46
7430,arthur,Swedish House Mafia,Ray Of Solar,2023,77,0.355,0.802,0.0478,0.03670,0.000011,0.1970,0.0391,135.017,-5.114,241793,2023,77
7431,arthur,Loreen,Euphoria,2013,59,0.475,0.667,0.0358,0.10000,0.000105,0.0513,0.0995,132.126,-5.477,212640,2013,59
7455,arthur,M83,Laura,2023,46,0.418,0.689,0.0287,0.00319,0.122000,0.0946,0.2230,143.883,-5.694,248133,2023,46
7477,arthur,M83,Laura,2023,46,0.418,0.689,0.0287,0.00319,0.122000,0.0946,0.2230,143.883,-5.694,248133,2023,46
7522,arthur,Imagine Dragons,Enemy (with JID) - from the series Arcane Leag...,2021,81,0.728,0.783,0.2660,0.23700,0.000000,0.4340,0.5550,77.011,-4.424,173381,2021,81
11361,lsirwguhu,AnnenMayKantereit,Toxic,2023,62,0.707,0.439,0.0316,0.55500,0.068100,0.1430,0.5210,102.006,-8.860,269952,2023,62
11415,lsirwguhu,AnnenMayKantereit,Toxic,2023,62,0.707,0.439,0.0316,0.55500,0.068100,0.1430,0.5210,102.006,-8.860,269952,2023,62
11467,lsirwguhu,Derivakat,Captain's Call,2021,52,0.703,0.694,0.0344,0.01680,0.000000,0.2620,0.8910,89.943,-6.926,146666,2021,52
12181,dany,Post Malone,Chemical,2023,73,0.486,0.899,0.0489,0.00115,0.000000,0.1020,0.3560,169.934,-4.713,183410,2023,73
12223,dany,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.63200,0.001190,0.1030,0.4650,105.011,-9.535,176026,2022,59
12226,dany,Iliona,micha,2022,49,0.795,0.417,0.0364,0.67900,0.573000,0.1090,0.4460,121.989,-12.028,233413,2022,49
12227,dany,Iliona,Garçon manqué,2022,45,0.822,0.399,0.0381,0.69300,0.101000,0.1030,0.3990,119.981,-9.382,211386,2022,45

In [ ]:
df_tracks = df_matrix_mf.copy()
df_tracks = df_tracks.sample(frac=1) # Shuffle the dataframe
df_tracks = df_tracks[:1000] # Keep only 1000 tracks

# Add item latent factors to the dataframe
items_latent_columns = [f"track_latent_{i}" for i in range(lmf.num_factors)]
for track_id in df_tracks["id"].unique():
    latent_factors = lmf.get_item_latent_factors(matrix_mf.items_to_ids([track_id])[0]).tolist()
    df_tracks.loc[df_tracks["id"] == track_id, items_latent_columns] = latent_factors

# Add user latent factors to the dataframe
users_latent_columns = [f"latent_factor_{i}" for i in range(lmf.num_factors)]
for user_id in df_tracks["username"].unique():
    latent_factors = lmf.get_user_latent_factors(matrix_mf.usernames_to_ids([user_id])[0]).tolist()
    df_tracks.loc[df_tracks["username"] == user_id, users_latent_columns] = latent_factors

plotting.plot_latent_space(
    df=df_tracks,
    color=df_tracks["username"],
    text=df_tracks["username"],
    latent_columns=items_latent_columns,
).show()

plotting.plot_latent_space(
    df=df_tracks,
    color=df_tracks["username"],
    text=df_tracks["username"],
    latent_columns=users_latent_columns,
).show()