In [16]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from recommenders.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [17]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float64

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [18]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.98,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.96,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.94,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.92,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [19]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
# used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100

In [20]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity")
R = torch.tensor(matrix_mf.R, dtype=dtype, device=device)
R

tensor([[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        ...,
        [30.,  0.,  0.,  ...,  0.,  0., 30.],
        [50., 30., 50.,  ...,  0., 50.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.]], device='mps:0')

In [21]:
alpha = matrix_mf.compute_alpha()
R *= alpha
alpha

0.15810223831515652

In [22]:
num_latent_factors = 100
lmf = LogisticMatrixFactorization(
    R=R,
    num_factors=num_latent_factors,
    alpha=alpha,
    lambd=0.01,
    device=device,
    dtype=dtype,
)

num_epochs = 10000
lmf.train_with_gradients(
    num_epochs=num_epochs,
    learning_rate=0.01,
    log_interval=10,
)

Epoch 1: loss = 165645.0625, MPR = 0.4924679398536682
Epoch 11: loss = 91464.640625, MPR = 0.43414250016212463
Epoch 21: loss = 138877.484375, MPR = 0.4012579619884491
Epoch 31: loss = 68599.0, MPR = 0.3741844594478607
Epoch 41: loss = 99590.515625, MPR = 0.35073980689048767
Epoch 51: loss = 143355.625, MPR = 0.33077532052993774
Epoch 61: loss = 70003.8125, MPR = 0.31222769618034363
Epoch 71: loss = 89097.078125, MPR = 0.2955075204372406
Epoch 81: loss = 146857.234375, MPR = 0.28104230761528015
Epoch 91: loss = 62704.98046875, MPR = 0.2669181525707245
Epoch 101: loss = 87813.3671875, MPR = 0.25418639183044434
Epoch 111: loss = 134179.359375, MPR = 0.24302178621292114
Epoch 121: loss = 50727.08203125, MPR = 0.2319774627685547
Epoch 131: loss = 54991.1796875, MPR = 0.2221391350030899
Epoch 141: loss = 77650.9140625, MPR = 0.21285073459148407
Epoch 151: loss = 119143.3671875, MPR = 0.20458351075649261
Epoch 161: loss = 47764.390625, MPR = 0.19666992127895355
Epoch 171: loss = 62287.21484375, MPR = 0.18935813009738922
Epoch 181: loss = 45920.2734375, MPR = 0.18277068436145782
Epoch 191: loss = 66643.484375, MPR = 0.1765386164188385
Epoch 201: loss = 76067.21875, MPR = 0.1706928014755249
Epoch 211: loss = 94553.265625, MPR = 0.16562768816947937
Epoch 221: loss = 31233.37890625, MPR = 0.16063052415847778
Epoch 231: loss = 46622.2109375, MPR = 0.155992329120636
Epoch 241: loss = 88430.90625, MPR = 0.15191233158111572
Epoch 251: loss = 32924.28125, MPR = 0.147894948720932
Epoch 261: loss = 49305.07421875, MPR = 0.14428412914276123
Epoch 271: loss = 64220.78125, MPR = 0.14096441864967346
Epoch 281: loss = 49209.875, MPR = 0.13782140612602234
Epoch 291: loss = 32046.33203125, MPR = 0.1349039524793625
Epoch 301: loss = 26478.345703125, MPR = 0.132212296128273
Epoch 311: loss = 91169.3671875, MPR = 0.12970727682113647
Epoch 321: loss = 36518.25, MPR = 0.1272963583469391
Epoch 331: loss = 35706.5546875, MPR = 0.12512312829494476
Epoch 341: loss = 50165.921875, MPR = 0.12309443950653076
Epoch 351: loss = 41963.28515625, MPR = 0.12125423550605774
Epoch 361: loss = 61341.828125, MPR = 0.11951981484889984
Epoch 371: loss = 68690.171875, MPR = 0.11789196729660034
Epoch 381: loss = 35866.93359375, MPR = 0.11644027382135391
Epoch 391: loss = 43186.6875, MPR = 0.11508837342262268
Epoch 401: loss = 34638.625, MPR = 0.11387947201728821
Epoch 411: loss = 47889.99609375, MPR = 0.11275934427976608
Epoch 421: loss = 32702.8125, MPR = 0.11173295974731445
Epoch 431: loss = 51773.8671875, MPR = 0.11077865213155746
Epoch 441: loss = 24235.453125, MPR = 0.10987909883260727
Epoch 451: loss = 89862.921875, MPR = 0.10904517769813538
Epoch 461: loss = 46663.4609375, MPR = 0.10820774734020233
Epoch 471: loss = 31783.076171875, MPR = 0.1075161024928093
Epoch 481: loss = 38174.6484375, MPR = 0.10686889290809631
Epoch 491: loss = 45872.41796875, MPR = 0.10627397894859314
Epoch 501: loss = 40806.61328125, MPR = 0.10571955144405365
Epoch 511: loss = 40940.703125, MPR = 0.10521306097507477
Epoch 521: loss = 43152.56640625, MPR = 0.10474249720573425
Epoch 531: loss = 35747.31640625, MPR = 0.10430433601140976
Epoch 541: loss = 50178.75, MPR = 0.10389764606952667
Epoch 551: loss = 43482.0625, MPR = 0.1035115197300911
Epoch 561: loss = 41906.4296875, MPR = 0.10316179692745209
Epoch 571: loss = 43647.6953125, MPR = 0.10284823924303055
Epoch 581: loss = 41972.640625, MPR = 0.10255277901887894
Epoch 591: loss = 44281.61328125, MPR = 0.10227281600236893
Epoch 601: loss = 41299.0625, MPR = 0.10199853777885437
Epoch 611: loss = 44824.72265625, MPR = 0.10173844546079636
Epoch 621: loss = 41644.44921875, MPR = 0.10148786753416061
Epoch 631: loss = 44496.37890625, MPR = 0.10126152634620667
Epoch 641: loss = 43719.4375, MPR = 0.10104680806398392
Epoch 651: loss = 43662.296875, MPR = 0.1008424162864685
Epoch 661: loss = 44120.21484375, MPR = 0.10065452754497528
Epoch 671: loss = 43848.64453125, MPR = 0.10048136115074158
Epoch 681: loss = 44221.76953125, MPR = 0.10031912475824356
Epoch 691: loss = 44086.94921875, MPR = 0.10016673058271408
Epoch 701: loss = 44332.26171875, MPR = 0.10003016144037247
Epoch 711: loss = 44319.03515625, MPR = 0.0999041348695755
Epoch 721: loss = 44472.2578125, MPR = 0.09978456050157547
Epoch 731: loss = 44532.52734375, MPR = 0.09967127442359924
Epoch 741: loss = 44642.06640625, MPR = 0.09956233203411102
Epoch 751: loss = 44731.79296875, MPR = 0.09945760667324066
Epoch 761: loss = 44829.18359375, MPR = 0.09935720264911652
Epoch 771: loss = 44926.88671875, MPR = 0.09926421195268631
Epoch 781: loss = 45023.3046875, MPR = 0.09917739778757095
Epoch 791: loss = 45122.6953125, MPR = 0.09909780323505402
Epoch 801: loss = 45220.08203125, MPR = 0.0990225151181221
Epoch 811: loss = 45319.94921875, MPR = 0.09894916415214539
Epoch 821: loss = 45418.1484375, MPR = 0.0988796129822731
Epoch 831: loss = 45518.18359375, MPR = 0.09880827367305756
Epoch 841: loss = 45616.86328125, MPR = 0.09873761981725693
Epoch 851: loss = 45716.91015625, MPR = 0.09867159277200699
Epoch 861: loss = 45815.765625, MPR = 0.09860950708389282
Epoch 871: loss = 45915.7421875, MPR = 0.09855259954929352
Epoch 881: loss = 46014.46875, MPR = 0.09849759191274643
Epoch 891: loss = 46114.296875, MPR = 0.09845014661550522
Epoch 901: loss = 46212.703125, MPR = 0.09840797632932663
Epoch 911: loss = 46312.3359375, MPR = 0.09836900234222412
Epoch 921: loss = 46410.25, MPR = 0.09833339601755142
Epoch 931: loss = 46509.67578125, MPR = 0.09830061346292496
Epoch 941: loss = 46606.9609375, MPR = 0.09827148914337158
Epoch 951: loss = 46706.33984375, MPR = 0.0982445627450943
Epoch 961: loss = 46802.75, MPR = 0.09821858257055283
Epoch 971: loss = 46902.38671875, MPR = 0.09819341450929642
Epoch 981: loss = 46997.57421875, MPR = 0.09816984087228775
Epoch 991: loss = 47098.046875, MPR = 0.09814804792404175
Epoch 1001: loss = 47191.28515625, MPR = 0.09812749177217484
Epoch 1011: loss = 47293.75, MPR = 0.09810683876276016
Epoch 1021: loss = 47383.43359375, MPR = 0.09808887541294098
Epoch 1031: loss = 47490.33203125, MPR = 0.09807134419679642
Epoch 1041: loss = 47572.87890625, MPR = 0.09805550426244736
Epoch 1051: loss = 47689.7109375, MPR = 0.09804034978151321
Epoch 1061: loss = 47756.82421875, MPR = 0.09802479296922684
Epoch 1071: loss = 47896.3203125, MPR = 0.09800976514816284
Epoch 1081: loss = 47928.27734375, MPR = 0.09799541532993317
Epoch 1091: loss = 48121.12890625, MPR = 0.09798163175582886
Epoch 1101: loss = 48069.36328125, MPR = 0.09796831756830215
Epoch 1111: loss = 48391.609375, MPR = 0.09795576333999634
Epoch 1121: loss = 48133.8046875, MPR = 0.09794478118419647
Epoch 1131: loss = 48774.45703125, MPR = 0.09793418645858765
Epoch 1141: loss = 48003.31640625, MPR = 0.09792400896549225
Epoch 1151: loss = 49402.2578125, MPR = 0.0979134738445282
Epoch 1161: loss = 47448.84375, MPR = 0.09790284186601639
Epoch 1171: loss = 50309.2578125, MPR = 0.09789273887872696
Epoch 1181: loss = 46594.3515625, MPR = 0.09788224846124649
Epoch 1191: loss = 50994.17578125, MPR = 0.0978725403547287
Epoch 1201: loss = 46315.32421875, MPR = 0.0978630781173706
Epoch 1211: loss = 51246.21875, MPR = 0.09785369783639908
Epoch 1221: loss = 46585.9296875, MPR = 0.09784463047981262
Epoch 1231: loss = 51322.13671875, MPR = 0.09783509373664856
Epoch 1241: loss = 47015.3203125, MPR = 0.09782493114471436
Epoch 1251: loss = 51363.40625, MPR = 0.09781493991613388
Epoch 1261: loss = 47458.31640625, MPR = 0.09780615568161011
Epoch 1271: loss = 51401.1015625, MPR = 0.09779910743236542
Epoch 1281: loss = 47894.62890625, MPR = 0.09779279679059982
Epoch 1291: loss = 51433.72265625, MPR = 0.0977877676486969
Epoch 1301: loss = 48331.30078125, MPR = 0.09778307378292084
Epoch 1311: loss = 51454.19140625, MPR = 0.09777867794036865
Epoch 1321: loss = 48777.03515625, MPR = 0.09777428209781647
Epoch 1331: loss = 51455.390625, MPR = 0.09777019917964935
Epoch 1341: loss = 49236.9296875, MPR = 0.09776619076728821
Epoch 1351: loss = 51431.9375, MPR = 0.09776253253221512
Epoch 1361: loss = 49709.26171875, MPR = 0.09775914996862411
Epoch 1371: loss = 51383.8828125, MPR = 0.0977555587887764
Epoch 1381: loss = 50179.72265625, MPR = 0.09775224328041077
Epoch 1391: loss = 51324.45703125, MPR = 0.09774931520223618
Epoch 1401: loss = 50616.28125, MPR = 0.0977465808391571
Epoch 1411: loss = 51286.6484375, MPR = 0.09774379432201385
Epoch 1421: loss = 50977.9609375, MPR = 0.09774088859558105
Epoch 1431: loss = 51309.17578125, MPR = 0.09773795306682587
Epoch 1441: loss = 51245.9296875, MPR = 0.09773503988981247
Epoch 1451: loss = 51400.27734375, MPR = 0.09773214161396027
Epoch 1461: loss = 51441.234375, MPR = 0.09772923588752747
Epoch 1471: loss = 51531.7421875, MPR = 0.09772641211748123
Epoch 1481: loss = 51599.47265625, MPR = 0.09772349148988724
Epoch 1491: loss = 51672.953125, MPR = 0.09772086888551712
Epoch 1501: loss = 51742.01953125, MPR = 0.09771852195262909
Epoch 1511: loss = 51809.62109375, MPR = 0.09771647304296494
Epoch 1521: loss = 51874.828125, MPR = 0.09771479666233063
Epoch 1531: loss = 51937.68359375, MPR = 0.0977131575345993
Epoch 1541: loss = 51998.0390625, MPR = 0.09771161526441574
Epoch 1551: loss = 52055.7421875, MPR = 0.09771017730236053
Epoch 1561: loss = 52110.65234375, MPR = 0.09770864993333817
Epoch 1571: loss = 52162.62890625, MPR = 0.097707100212574
Epoch 1581: loss = 52211.5625, MPR = 0.09770555794239044
Epoch 1591: loss = 52257.3046875, MPR = 0.09770408272743225
Epoch 1601: loss = 52299.69140625, MPR = 0.09770231693983078
Epoch 1611: loss = 52338.59765625, MPR = 0.09770049154758453
Epoch 1621: loss = 52373.91796875, MPR = 0.09769878536462784
Epoch 1631: loss = 52405.5078125, MPR = 0.09769713878631592
Epoch 1641: loss = 52433.25390625, MPR = 0.09769569337368011
Epoch 1651: loss = 52457.078125, MPR = 0.0976947546005249
Epoch 1661: loss = 52476.87890625, MPR = 0.09769386053085327
Epoch 1671: loss = 52492.58203125, MPR = 0.09769294410943985
Epoch 1681: loss = 52504.16796875, MPR = 0.09769224375486374
Epoch 1691: loss = 52511.59765625, MPR = 0.09769139438867569
Epoch 1701: loss = 52514.92578125, MPR = 0.09769053757190704
Epoch 1711: loss = 52514.15625, MPR = 0.09768985211849213
Epoch 1721: loss = 52509.40234375, MPR = 0.09768921881914139
Epoch 1731: loss = 52500.79296875, MPR = 0.09768850356340408
Epoch 1741: loss = 52488.5, MPR = 0.09768775850534439
Epoch 1751: loss = 52472.7265625, MPR = 0.09768711775541306
Epoch 1761: loss = 52453.7421875, MPR = 0.09768635034561157
Epoch 1771: loss = 52431.81640625, MPR = 0.09768561273813248
Epoch 1781: loss = 52407.28515625, MPR = 0.09768491238355637
Epoch 1791: loss = 52380.50390625, MPR = 0.09768430888652802
Epoch 1801: loss = 52351.80859375, MPR = 0.09768370538949966
Epoch 1811: loss = 52321.6015625, MPR = 0.09768316894769669
Epoch 1821: loss = 52290.25, MPR = 0.09768252074718475
Epoch 1831: loss = 52258.12109375, MPR = 0.09768208861351013
Epoch 1841: loss = 52225.55859375, MPR = 0.09768149256706238
Epoch 1851: loss = 52192.90234375, MPR = 0.09768106788396835
Epoch 1861: loss = 52160.44140625, MPR = 0.09768057614564896
Epoch 1871: loss = 52128.4609375, MPR = 0.09768011420965195
Epoch 1881: loss = 52097.1796875, MPR = 0.09767969697713852
Epoch 1891: loss = 52066.8203125, MPR = 0.09767928719520569
Epoch 1901: loss = 52037.55078125, MPR = 0.09767886251211166
Epoch 1911: loss = 52009.51953125, MPR = 0.09767835587263107
Epoch 1921: loss = 51982.80859375, MPR = 0.09767795354127884
Epoch 1931: loss = 51957.51171875, MPR = 0.09767758101224899
Epoch 1941: loss = 51933.65625, MPR = 0.09767718613147736
Epoch 1951: loss = 51911.2734375, MPR = 0.0976768508553505
Epoch 1961: loss = 51890.375, MPR = 0.09767651557922363
Epoch 1971: loss = 51870.89453125, MPR = 0.09767615795135498
Epoch 1981: loss = 51852.8203125, MPR = 0.09767580032348633
Epoch 1991: loss = 51836.0859375, MPR = 0.09767553210258484
Epoch 2001: loss = 51820.5625, MPR = 0.09767524152994156
Epoch 2011: loss = 51806.21875, MPR = 0.09767493605613708
Epoch 2021: loss = 51792.94140625, MPR = 0.09767462313175201
Epoch 2031: loss = 51780.625, MPR = 0.09767425060272217
Epoch 2041: loss = 51769.19140625, MPR = 0.09767390787601471
Epoch 2051: loss = 51758.53515625, MPR = 0.09767366945743561
Epoch 2061: loss = 51748.5234375, MPR = 0.09767341613769531
Epoch 2071: loss = 51739.1171875, MPR = 0.09767317026853561
Epoch 2081: loss = 51730.23828125, MPR = 0.09767287969589233
Epoch 2091: loss = 51721.8203125, MPR = 0.09767257422208786
Epoch 2101: loss = 51713.78515625, MPR = 0.09767235815525055
Epoch 2111: loss = 51706.1015625, MPR = 0.09767209738492966
Epoch 2121: loss = 51698.703125, MPR = 0.09767182916402817
Epoch 2131: loss = 51691.5859375, MPR = 0.09767160564661026
Epoch 2141: loss = 51684.71875, MPR = 0.09767135232686996
Epoch 2151: loss = 51678.0703125, MPR = 0.09767112880945206
Epoch 2161: loss = 51671.671875, MPR = 0.09767093509435654
Epoch 2171: loss = 51665.49609375, MPR = 0.09767075628042221
Epoch 2181: loss = 51659.53515625, MPR = 0.09767051041126251
Epoch 2191: loss = 51653.75390625, MPR = 0.0976703092455864
Epoch 2201: loss = 51648.1640625, MPR = 0.0976700633764267
Epoch 2211: loss = 51642.73828125, MPR = 0.09766986221075058
Epoch 2221: loss = 51637.453125, MPR = 0.09766966849565506
Epoch 2231: loss = 51632.28125, MPR = 0.09766949713230133
Epoch 2241: loss = 51627.296875, MPR = 0.09766931086778641
Epoch 2251: loss = 51622.4765625, MPR = 0.09766910970211029
Epoch 2261: loss = 51617.7578125, MPR = 0.09766893088817596
Epoch 2271: loss = 51613.203125, MPR = 0.09766873717308044
Epoch 2281: loss = 51608.8515625, MPR = 0.09766853600740433
Epoch 2291: loss = 51604.6328125, MPR = 0.0976683497428894
Epoch 2301: loss = 51600.5234375, MPR = 0.09766814857721329
Epoch 2311: loss = 51596.4140625, MPR = 0.09766795486211777
Epoch 2321: loss = 51592.19921875, MPR = 0.09766776859760284
Epoch 2331: loss = 51587.73828125, MPR = 0.09766758978366852
Epoch 2341: loss = 51582.953125, MPR = 0.09766741096973419
Epoch 2351: loss = 51577.83984375, MPR = 0.09766728430986404
Epoch 2361: loss = 51572.83984375, MPR = 0.09766712039709091
Epoch 2371: loss = 51569.12890625, MPR = 0.09766695648431778
Epoch 2381: loss = 51569.51171875, MPR = 0.09766680002212524
Epoch 2391: loss = 51579.6328125, MPR = 0.09766662120819092
Epoch 2401: loss = 51609.3984375, MPR = 0.0976664274930954
Epoch 2411: loss = 51670.58984375, MPR = 0.09766626358032227
Epoch 2421: loss = 51760.203125, MPR = 0.09766604751348495
Epoch 2431: loss = 51831.1640625, MPR = 0.09766586124897003
Epoch 2441: loss = 51790.11328125, MPR = 0.09766564518213272
Epoch 2451: loss = 51462.97265625, MPR = 0.0976654663681984
Epoch 2461: loss = 47911.58984375, MPR = 0.09766530990600586
Epoch 2471: loss = 53384.421875, MPR = 0.09766513109207153
Epoch 2481: loss = 53734.46875, MPR = 0.09766490757465363
Epoch 2491: loss = 53541.11328125, MPR = 0.09766469895839691
Epoch 2501: loss = 53299.93359375, MPR = 0.09766452014446259
Epoch 2511: loss = 53012.390625, MPR = 0.09766431152820587
Epoch 2521: loss = 52660.921875, MPR = 0.09766414016485214
Epoch 2531: loss = 52181.5859375, MPR = 0.09766397625207901
Epoch 2541: loss = 51121.48046875, MPR = 0.09766378253698349
Epoch 2551: loss = 29790.806640625, MPR = 0.09766364097595215
Epoch 2561: loss = 29389.078125, MPR = 0.0976635068655014
Epoch 2571: loss = 37345.75390625, MPR = 0.09766349196434021
Epoch 2581: loss = 37411.04296875, MPR = 0.09766314923763275
Epoch 2591: loss = 37222.68359375, MPR = 0.09766288846731186
Epoch 2601: loss = 37032.234375, MPR = 0.09766263514757156
Epoch 2611: loss = 36840.35546875, MPR = 0.09766239672899246
Epoch 2621: loss = 36647.953125, MPR = 0.09766221046447754
Epoch 2631: loss = 36456.21875, MPR = 0.09766196459531784
Epoch 2641: loss = 36266.52734375, MPR = 0.09766172617673874
Epoch 2651: loss = 36080.3203125, MPR = 0.09766149520874023
Epoch 2661: loss = 35898.8984375, MPR = 0.09766130894422531
Epoch 2671: loss = 35723.14453125, MPR = 0.0976610854268074
Epoch 2681: loss = 35553.359375, MPR = 0.09766088426113129
Epoch 2691: loss = 35389.14453125, MPR = 0.09766063839197159
Epoch 2701: loss = 35229.3828125, MPR = 0.09766042232513428
Epoch 2711: loss = 35072.2734375, MPR = 0.09766021370887756
Epoch 2721: loss = 34915.11328125, MPR = 0.09766001999378204
Epoch 2731: loss = 34753.8203125, MPR = 0.09765985608100891
Epoch 2741: loss = 34580.953125, MPR = 0.09765966236591339
Epoch 2751: loss = 34378.03515625, MPR = 0.09765947610139847
Epoch 2761: loss = 34064.57421875, MPR = 0.09765928238630295
Epoch 2771: loss = 31130.05859375, MPR = 0.09765905886888504
Epoch 2781: loss = 54194.0390625, MPR = 0.09765888750553131
Epoch 2791: loss = 53786.2890625, MPR = 0.09765870869159698
Epoch 2801: loss = 53598.234375, MPR = 0.09765852987766266
Epoch 2811: loss = 53404.4296875, MPR = 0.09765832871198654
Epoch 2821: loss = 53200.8359375, MPR = 0.09765808284282684
Epoch 2831: loss = 52984.234375, MPR = 0.0976579338312149
Epoch 2841: loss = 52747.8515625, MPR = 0.09765774756669998
Epoch 2851: loss = 52476.54296875, MPR = 0.09765754640102386
Epoch 2861: loss = 52125.7578125, MPR = 0.09765739738941193
Epoch 2871: loss = 51449.16796875, MPR = 0.097657211124897
Epoch 2881: loss = 34466.0625, MPR = 0.09765705466270447
Epoch 2891: loss = 34686.5234375, MPR = 0.09765687584877014
Epoch 2901: loss = 34551.796875, MPR = 0.09765668213367462
Epoch 2911: loss = 34395.7421875, MPR = 0.09765645861625671
Epoch 2921: loss = 34222.625, MPR = 0.09765629470348358
Epoch 2931: loss = 34005.94921875, MPR = 0.09765608608722687
Epoch 2941: loss = 33583.7421875, MPR = 0.09765587002038956
Epoch 2951: loss = 43750.9765625, MPR = 0.09765570610761642
Epoch 2961: loss = 34848.0859375, MPR = 0.0976555123925209
Epoch 2971: loss = 34690.734375, MPR = 0.097655288875103
Epoch 2981: loss = 34550.08984375, MPR = 0.09765508770942688
Epoch 2991: loss = 34408.05859375, MPR = 0.09765490144491196
Epoch 3001: loss = 34259.921875, MPR = 0.09765468537807465
Epoch 3011: loss = 34097.3359375, MPR = 0.09765449911355972
Epoch 3021: loss = 33898.484375, MPR = 0.09765428304672241
Epoch 3031: loss = 33554.71875, MPR = 0.09765410423278809
Epoch 3041: loss = 29777.431640625, MPR = 0.09765390306711197
Epoch 3051: loss = 53312.46875, MPR = 0.09765365719795227
Epoch 3061: loss = 53012.85546875, MPR = 0.09765344113111496
Epoch 3071: loss = 52756.6875, MPR = 0.09765318036079407
Epoch 3081: loss = 52450.4375, MPR = 0.09765294939279556
Epoch 3091: loss = 51989.4765625, MPR = 0.09765271097421646
Epoch 3101: loss = 49939.69921875, MPR = 0.09765248745679855
Epoch 3111: loss = 54865.2109375, MPR = 0.09765227884054184
Epoch 3121: loss = 53904.7265625, MPR = 0.09765197336673737
Epoch 3131: loss = 53721.4921875, MPR = 0.0976516529917717
Epoch 3141: loss = 53536.703125, MPR = 0.09765131771564484
Epoch 3151: loss = 53342.8515625, MPR = 0.09765098243951797
Epoch 3161: loss = 53136.16796875, MPR = 0.09765051305294037
Epoch 3171: loss = 52909.640625, MPR = 0.09765006601810455
Epoch 3181: loss = 52648.359375, MPR = 0.09764937311410904
Epoch 3191: loss = 52310.3046875, MPR = 0.09764842689037323
Epoch 3201: loss = 51675.56640625, MPR = 0.09764712303876877
Epoch 3211: loss = 31274.0625, MPR = 0.09764619171619415
Epoch 3221: loss = 53707.9296875, MPR = 0.09764596074819565
Epoch 3231: loss = 53456.578125, MPR = 0.09764578193426132
Epoch 3241: loss = 53258.875, MPR = 0.097645603120327
Epoch 3251: loss = 53046.171875, MPR = 0.09764546900987625
Epoch 3261: loss = 52807.640625, MPR = 0.0976453498005867
Epoch 3271: loss = 52519.36328125, MPR = 0.09764522314071655
Epoch 3281: loss = 52096.0078125, MPR = 0.09764515608549118
Epoch 3291: loss = 50579.26171875, MPR = 0.09764503687620163
Epoch 3301: loss = 53985.390625, MPR = 0.09764495491981506
Epoch 3311: loss = 53481.53125, MPR = 0.09764483571052551
Epoch 3321: loss = 53283.01953125, MPR = 0.09764475375413895
Epoch 3331: loss = 53072.1953125, MPR = 0.09764467924833298
Epoch 3341: loss = 52835.51953125, MPR = 0.09764459729194641
Epoch 3351: loss = 52549.0859375, MPR = 0.09764453023672104

In [23]:
lmf.save("models", "lmf_all_types_100")
lmf = LogisticMatrixFactorization.load(os.path.join("models", "lmf_all_types_100.pt"))

In [24]:
px.line(x=range(len(lmf.losses)), y=lmf.losses.cpu(), title="Loss").show()
px.line(x=range(len(lmf.mprs)), y=lmf.mprs.cpu(), title="MPRS").show()

In [33]:
user_id = matrix_mf.usernames_to_ids(["paul"])[0]

# Get the top 10 recommendations for the user
top_10_ids, top_10_ids_scores = lmf.recommend(user_id, top_k=20, filter_user_items=True)

# Get the top 10 recommendations for the user
matrix_mf.items_ids_to_df(top_10_ids)[spoti.PRETTY_PRINT_FEATURES]

,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
183,jaslkh,Disiz,RENCONTRE,2022,67,0.620,0.458,0.2690,0.521000,0.000000,0.1100,0.518,125.132,-10.557,198396,2022,67
191,jaslkh,Doja Cat,Agora Hills,2023,92,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.392,123.026,-6.128,265360,2023,92
217,jaslkh,Mazzy Star,Fade Into You,1993,84,0.420,0.330,0.0275,0.245000,0.000679,0.0677,0.175,157.143,-13.925,295600,1993,84
282,jaslkh,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.632000,0.001190,0.1030,0.465,105.011,-9.535,176026,2022,59
490,jaslkh,The Rolling Stones,"Paint It, Black",1966,85,0.464,0.795,0.0926,0.049300,0.002440,0.3990,0.612,158.691,-9.267,202266,1966,85
914,jaslkh,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.632000,0.001190,0.1030,0.465,105.011,-9.535,176026,2022,59
915,jaslkh,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.632000,0.001190,0.1030,0.465,105.011,-9.535,176026,2022,59
1519,owen,Doja Cat,Agora Hills,2023,91,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.392,123.026,-6.128,265360,2023,91
1543,owen,J. Cole,l e t . g o . m y . h a n d (with Bas & 6LACK),2021,69,0.583,0.625,0.2770,0.506000,0.000000,0.1960,0.516,89.812,-8.011,266291,2021,69
1580,owen,Mistress,Liminal,2022,24,0.467,0.699,0.0353,0.647000,0.871000,0.1040,0.194,161.968,-8.140,213333,2022,24
1583,owen,Doja Cat,Agora Hills,2023,91,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.392,123.026,-6.128,265360,2023,91
1615,owen,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.632000,0.001190,0.1030,0.465,105.011,-9.535,176026,2022,59
1757,owen,Mistress,Liminal,2022,24,0.467,0.699,0.0353,0.647000,0.871000,0.1040,0.194,161.968,-8.140,213333,2022,24
1762,owen,Doja Cat,Agora Hills,2023,91,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.392,123.026,-6.128,265360,2023,91
1827,owen,J. Cole,l e t . g o . m y . h a n d (with Bas & 6LACK),2021,69,0.583,0.625,0.2770,0.506000,0.000000,0.1960,0.516,89.812,-8.011,266291,2021,69
1946,owen,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.632000,0.001190,0.1030,0.465,105.011,-9.535,176026,2022,59
2043,owen,beabadoobee,Glue Song,2023,81,0.620,0.409,0.0282,0.770000,0.054200,0.1050,0.582,113.946,-10.146,135066,2023,81
2068,owen,Roseboy666,Ta Shawty,2022,40,0.769,0.438,0.3630,0.484000,0.000020,0.1050,0.611,160.038,-11.107,160200,2022,40
2166,owen,La Dispute,King Park,2011,0,0.486,0.742,0.0637,0.041600,0.002950,0.1860,0.181,108.335,-7.406,414925,2011,0
2208,owen,Disiz,RENCONTRE,2022,67,0.620,0.458,0.2690,0.521000,0.000000,0.1100,0.518,125.132,-10.557,198396,2022,67
2325,owen,Nekfeu,Energie sombre,2019,64,0.774,0.431,0.3950,0.305000,0.000000,0.1160,0.189,133.132,-7.236,204346,2019,64
2453,owen,Green Day,American Idiot,2004,84,0.380,0.988,0.0639,0.000026,0.000079,0.3680,0.769,186.113,-2.042,176346,2004,84
2464,owen,Odezenne,Souffle le vent,2015,51,0.567,0.542,0.0663,0.080500,0.000259,0.0824,0.352,102.041,-7.882,192893,2015,51
2481,owen,The 1975,Menswear,2013,52,0.708,0.539,0.0646,0.547000,0.017400,0.0849,0.163,96.987,-10.280,206737,2013,52
2576,owen,Dayglow,Can I Call You Tonight?,2019,16,0.641,0.842,0.0292,0.132000,0.910000,0.4190,0.500,129.980,-7.270,278769,2019,16
2715,owen,Mazzy Star,Fade Into You,1993,84,0.420,0.330,0.0275,0.245000,0.000679,0.0677,0.175,157.143,-13.925,295600,1993,84
3006,owen,Post Malone,Better Now,2018,84,0.680,0.578,0.0400,0.331000,0.000000,0.1350,0.341,145.038,-5.804,231266,2018,84
3111,owen,WILLOW,t r a n s p a r e n t s o u l feat. Travis Barker,2021,65,0.390,0.830,0.0563,0.002100,0.000000,0.1560,0.191,90.021,-5.201,168030,2021,65
3247,owen,Calvin Harris,Over Now (with The Weeknd),2020,70,0.612,0.884,0.0454,0.075900,0.001320,0.2470,0.679,178.043,-4.113,210795,2020,70
3249,owen,Calvin Harris,Slide (feat. Frank Ocean & Migos),2017,75,0.736,0.795,0.0545,0.498000,0.000001,0.2540,0.511,104.066,-3.299,230813,2017,75
3312,owen,Skegss,L.S.D,2014,58,0.630,0.874,0.0425,0.546000,0.661000,0.2810,0.747,135.973,-4.183,217538,2014,58
6650,owen,The Rolling Stones,"Paint It, Black",1966,85,0.464,0.795,0.0926,0.049300,0.002440,0.3990,0.612,158.691,-9.267,202266,1966,85
6651,owen,The Rolling Stones,"Paint It, Black",1966,85,0.464,0.795,0.0926,0.049300,0.002440,0.3990,0.612,158.691,-9.267,202266,1966,85
7551,arthur,Nekfeu,Energie sombre,2019,64,0.774,0.431,0.3950,0.305000,0.000000,0.1160,0.189,133.132,-7.236,204346,2019,64
7726,arthur,Disiz,RENCONTRE,2022,67,0.620,0.458,0.2690,0.521000,0.000000,0.1100,0.518,125.132,-10.557,198396,2022,67
7861,arthur,The Rolling Stones,"Paint It, Black",1966,85,0.464,0.795,0.0926,0.049300,0.002440,0.3990,0.612,158.691,-9.267,202266,1966,85
7884,arthur,Post Malone,Better Now,2018,84,0.680,0.578,0.0400,0.331000,0.000000,0.1350,0.341,145.038,-5.804,231266,2018,84
7914,arthur,Green Day,American Idiot,2004,84,0.380,0.988,0.0639,0.000026,0.000079,0.3680,0.769,186.113,-2.042,176346,2004,84
8032,michelle,Mistress,Liminal,2022,24,0.467,0.699,0.0353,0.647000,0.871000,0.1040,0.194,161.968,-8.140,213333,2022,24
8207,michelle,Calvin Harris,Over Now (with The Weeknd),2020,70,0.612,0.884,0.0454,0.075900,0.001320,0.2470,0.679,178.043,-4.113,210795,2020,70
8214,michelle,beabadoobee,Glue Song,2023,81,0.620,0.409,0.0282,0.770000,0.054200,0.1050,0.582,113.946,-10.146,135066,2023,81
8495,michelle,WILLOW,t r a n s p a r e n t s o u l feat. Travis Barker,2021,65,0.390,0.830,0.0563,0.002100,0.000000,0.1560,0.191,90.021,-5.201,168030,2021,65
8578,michelle,Skegss,L.S.D,2014,58,0.630,0.874,0.0425,0.546000,0.661000,0.2810,0.747,135.973,-4.183,217538,2014,58
8621,michelle,Post Malone,Better Now,2018,84,0.680,0.578,0.0400,0.331000,0.000000,0.1350,0.341,145.038,-5.804,231266,2018,84
8721,michelle,La Dispute,King Park,2011,0,0.486,0.742,0.0637,0.041600,0.002950,0.1860,0.181,108.335,-7.406,414925,2011,0
8731,michelle,J. Cole,l e t . g o . m y . h a n d (with Bas & 6LACK),2021,69,0.583,0.625,0.2770,0.506000,0.000000,0.1960,0.516,89.812,-8.011,266291,2021,69
8957,michelle,Dayglow,Can I Call You Tonight?,2019,16,0.641,0.842,0.0292,0.132000,0.910000,0.4190,0.500,129.980,-7.270,278769,2019,16
9141,michelle,J. Cole,l e t . g o . m y . h a n d (with Bas & 6LACK),2021,68,0.583,0.625,0.2770,0.506000,0.000000,0.1960,0.516,89.812,-8.011,266291,2021,68
9160,michelle,Dayglow,Can I Call You Tonight?,2019,12,0.641,0.842,0.0292,0.132000,0.910000,0.4190,0.500,129.980,-7.270,278769,2019,12
9237,michelle,Post Malone,Better Now,2018,83,0.680,0.578,0.0400,0.331000,0.000000,0.1350,0.341,145.038,-5.804,231266,2018,83
9253,michelle,J. Cole,l e t . g o . m y . h a n d (with Bas & 6LACK),2021,68,0.583,0.625,0.2770,0.506000,0.000000,0.1960,0.516,89.812,-8.011,266291,2021,68
9371,michelle,Skegss,L.S.D,2014,58,0.630,0.874,0.0425,0.546000,0.661000,0.2810,0.747,135.973,-4.183,217538,2014,58
9447,michelle,Dayglow,Can I Call You Tonight?,2019,12,0.641,0.842,0.0292,0.132000,0.910000,0.4190,0.500,129.980,-7.270,278769,2019,12
9538,michelle,La Dispute,King Park,2011,0,0.486,0.742,0.0637,0.041600,0.002950,0.1860,0.181,108.335,-7.406,414925,2011,0
11389,lsirwguhu,Calvin Harris,Slide (feat. Frank Ocean & Migos),2017,75,0.736,0.795,0.0545,0.498000,0.000001,0.2540,0.511,104.066,-3.299,230813,2017,75
11544,lsirwguhu,Calvin Harris,Slide (feat. Frank Ocean & Migos),2017,75,0.736,0.795,0.0545,0.498000,0.000001,0.2540,0.511,104.066,-3.299,230813,2017,75
11954,lsirwguhu,Green Day,American Idiot,2004,84,0.380,0.988,0.0639,0.000026,0.000079,0.3680,0.769,186.113,-2.042,176346,2004,84
12223,dany,Iliona,Si tu m'aimes demain,2022,59,0.854,0.501,0.0310,0.632000,0.001190,0.1030,0.465,105.011,-9.535,176026,2022,59
12374,dany,Mazzy Star,Fade Into You,1993,83,0.420,0.330,0.0275,0.245000,0.000679,0.0677,0.175,157.143,-13.925,295600,1993,83

In [26]:
if lmf.num_factors <= 3:
    df_tracks = df_matrix_mf.copy()
    df_tracks = df_tracks.sample(frac=1) # Shuffle the dataframe
    df_tracks = df_tracks[:1000] # Keep only 1000 tracks

    # Add item latent factors to the dataframe
    items_latent_columns = [f"track_latent_{i}" for i in range(lmf.num_factors)]
    for track_id in df_tracks["id"].unique():
        latent_factors = lmf.get_item_latent_factors(matrix_mf.items_to_ids([track_id])[0]).tolist()
        df_tracks.loc[df_tracks["id"] == track_id, items_latent_columns] = latent_factors

    # Add user latent factors to the dataframe
    users_latent_columns = [f"latent_factor_{i}" for i in range(lmf.num_factors)]
    for user_id in df_tracks["username"].unique():
        latent_factors = lmf.get_user_latent_factors(matrix_mf.usernames_to_ids([user_id])[0]).tolist()
        df_tracks.loc[df_tracks["username"] == user_id, users_latent_columns] = latent_factors

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=items_latent_columns,
    ).show()

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=users_latent_columns,
    ).show()

ValueError: Invalid property specified for object of type plotly.graph_objs.Splom: 'textposition'

Did you mean "textsrc"?

    Valid properties:
        customdata
            Assigns extra data each datum. This may be useful when
            listening to hover, click and selection events. Note
            that, "scatter" traces also appends customdata items in
            the markers DOM elements
        customdatasrc
            Sets the source reference on Chart Studio Cloud for
            `customdata`.
        diagonal
            :class:`plotly.graph_objects.splom.Diagonal` instance
            or dict with compatible properties
        dimensions
            A tuple of
            :class:`plotly.graph_objects.splom.Dimension` instances
            or dicts with compatible properties
        dimensiondefaults
            When used in a template (as
            layout.template.data.splom.dimensiondefaults), sets the
            default property values to use for elements of
            splom.dimensions
        hoverinfo
            Determines which trace information appear on hover. If
            `none` or `skip` are set, no information is displayed
            upon hovering. But, if `none` is set, click and hover
            events are still fired.
        hoverinfosrc
            Sets the source reference on Chart Studio Cloud for
            `hoverinfo`.
        hoverlabel
            :class:`plotly.graph_objects.splom.Hoverlabel` instance
            or dict with compatible properties
        hovertemplate
            Template string used for rendering the information that
            appear on hover box. Note that this will override
            `hoverinfo`. Variables are inserted using %{variable},
            for example "y: %{y}" as well as %{xother}, {%_xother},
            {%_xother_}, {%xother_}. When showing info for several
            points, "xother" will be added to those with different
            x positions from the first point. An underscore before
            or after "(x|y)other" will add a space on that side,
            only when this field is shown. Numbers are formatted
            using d3-format's syntax %{variable:d3-format}, for
            example "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. The variables available in
            `hovertemplate` are the ones emitted as event data
            described at this link
            https://plotly.com/javascript/plotlyjs-events/#event-
            data. Additionally, every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available.  Anything contained in tag `<extra>` is
            displayed in the secondary box, for example
            "<extra>{fullData.name}</extra>". To hide the secondary
            box completely, use an empty tag `<extra></extra>`.
        hovertemplatesrc
            Sets the source reference on Chart Studio Cloud for
            `hovertemplate`.
        hovertext
            Same as `text`.
        hovertextsrc
            Sets the source reference on Chart Studio Cloud for
            `hovertext`.
        ids
            Assigns id labels to each datum. These ids for object
            constancy of data points during animation. Should be an
            array of strings, not numbers or any other type.
        idssrc
            Sets the source reference on Chart Studio Cloud for
            `ids`.
        legend
            Sets the reference to a legend to show this trace in.
            References to these legends are "legend", "legend2",
            "legend3", etc. Settings for these legends are set in
            the layout, under `layout.legend`, `layout.legend2`,
            etc.
        legendgroup
            Sets the legend group for this trace. Traces and shapes
            part of the same legend group hide/show at the same
            time when toggling legend items.
        legendgrouptitle
            :class:`plotly.graph_objects.splom.Legendgrouptitle`
            instance or dict with compatible properties
        legendrank
            Sets the legend rank for this trace. Items and groups
            with smaller ranks are presented on top/left side while
            with "reversed" `legend.traceorder` they are on
            bottom/right side. The default legendrank is 1000, so
            that you can use ranks less than 1000 to place certain
            items before all unranked items, and ranks greater than
            1000 to go after all unranked items. When having
            unranked or equal rank items shapes would be displayed
            after traces i.e. according to their order in data and
            layout.
        legendwidth
            Sets the width (in px or fraction) of the legend for
            this trace.
        marker
            :class:`plotly.graph_objects.splom.Marker` instance or
            dict with compatible properties
        meta
            Assigns extra meta information associated with this
            trace that can be used in various text attributes.
            Attributes such as trace `name`, graph, axis and
            colorbar `title.text`, annotation `text`
            `rangeselector`, `updatemenues` and `sliders` `label`
            text all support `meta`. To access the trace `meta`
            values in an attribute in the same trace, simply use
            `%{meta[i]}` where `i` is the index or key of the
            `meta` item in question. To access trace `meta` in
            layout attributes, use `%{data[n[.meta[i]}` where `i`
            is the index or key of the `meta` and `n` is the trace
            index.
        metasrc
            Sets the source reference on Chart Studio Cloud for
            `meta`.
        name
            Sets the trace name. The trace name appears as the
            legend item and on hover.
        opacity
            Sets the opacity of the trace.
        selected
            :class:`plotly.graph_objects.splom.Selected` instance
            or dict with compatible properties
        selectedpoints
            Array containing integer indices of selected points.
            Has an effect only for traces that support selections.
            Note that an empty array means an empty selection where
            the `unselected` are turned on for all points, whereas,
            any other non-array values means no selection all where
            the `selected` and `unselected` styles have no effect.
        showlegend
            Determines whether or not an item corresponding to this
            trace is shown in the legend.
        showlowerhalf
            Determines whether or not subplots on the lower half
            from the diagonal are displayed.
        showupperhalf
            Determines whether or not subplots on the upper half
            from the diagonal are displayed.
        stream
            :class:`plotly.graph_objects.splom.Stream` instance or
            dict with compatible properties
        text
            Sets text elements associated with each (x,y) pair to
            appear on hover. If a single string, the same string
            appears over all the data points. If an array of
            string, the items are mapped in order to the this
            trace's (x,y) coordinates.
        textsrc
            Sets the source reference on Chart Studio Cloud for
            `text`.
        uid
            Assign an id to this trace, Use this to provide object
            constancy between traces during animations and
            transitions.
        uirevision
            Controls persistence of some user-driven changes to the
            trace: `constraintrange` in `parcoords` traces, as well
            as some `editable: true` modifications such as `name`
            and `colorbar.title`. Defaults to `layout.uirevision`.
            Note that other user-driven trace attribute changes are
            controlled by `layout` attributes: `trace.visible` is
            controlled by `layout.legend.uirevision`,
            `selectedpoints` is controlled by
            `layout.selectionrevision`, and `colorbar.(x|y)`
            (accessible with `config: {editable: true}`) is
            controlled by `layout.editrevision`. Trace changes are
            tracked by `uid`, which only falls back on trace index
            if no `uid` is provided. So if your app can add/remove
            traces before the end of the `data` array, such that
            the same trace has a different index, you can still
            preserve user-driven changes if you give each trace a
            `uid` that stays with it as it moves.
        unselected
            :class:`plotly.graph_objects.splom.Unselected` instance
            or dict with compatible properties
        visible
            Determines whether or not this trace is visible. If
            "legendonly", the trace is not drawn, but can appear as
            a legend item (provided that the legend itself is
            visible).
        xaxes
            Sets the list of x axes corresponding to dimensions of
            this splom trace. By default, a splom will match the
            first N xaxes where N is the number of input
            dimensions. Note that, in case where `diagonal.visible`
            is false and `showupperhalf` or `showlowerhalf` is
            false, this splom trace will generate one less x-axis
            and one less y-axis.
        xhoverformat
            Sets the hover text formatting rulefor `x`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `xaxis.hoverformat`.
        yaxes
            Sets the list of y axes corresponding to dimensions of
            this splom trace. By default, a splom will match the
            first N yaxes where N is the number of input
            dimensions. Note that, in case where `diagonal.visible`
            is false and `showupperhalf` or `showlowerhalf` is
            false, this splom trace will generate one less x-axis
            and one less y-axis.
        yhoverformat
            Sets the hover text formatting rulefor `y`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `yaxis.hoverformat`.

Did you mean "textsrc"?

Bad property path:
textposition
^^^^^^^^^^^^