In [83]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from recommenders.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [84]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float64

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [85]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.98,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.96,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.94,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.92,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [86]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100

In [87]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity", device=device, dtype=dtype)
R = matrix_mf.R
R

tensor([[ 0.,  0., 62.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0., 84.],
        ...,
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [44., 60.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ..., 92.,  0.,  0.]], device='mps:0')

In [88]:
alpha = matrix_mf.compute_alpha().item()
R *= alpha
alpha

0.10527777671813965

In [89]:
num_latent_factors = 3
lmf = LogisticMatrixFactorization(
    R=R,
    num_factors=num_latent_factors,
    alpha=alpha,
    lambd=0.01,
    device=device,
    dtype=dtype,
)

num_epochs = 10000
lmf.train_with_gradients(
    num_epochs=num_epochs,
    learning_rate=0.01,
    log_interval=10,
)

Epoch 1: loss = 3446.721923828125, MPR = 0.4922444522380829
Epoch 11: loss = 3135.263671875, MPR = 0.4756205976009369
Epoch 21: loss = 3024.877685546875, MPR = 0.4630703032016754
Epoch 31: loss = 2936.736328125, MPR = 0.45201921463012695
Epoch 41: loss = 2863.133544921875, MPR = 0.44179868698120117
Epoch 51: loss = 2800.279541015625, MPR = 0.43237194418907166
Epoch 61: loss = 2745.841552734375, MPR = 0.42365503311157227
Epoch 71: loss = 2698.212158203125, MPR = 0.41512277722358704
Epoch 81: loss = 2656.20654296875, MPR = 0.4071062207221985
Epoch 91: loss = 2618.91455078125, MPR = 0.39938291907310486
Epoch 101: loss = 2585.61669921875, MPR = 0.39205092191696167
Epoch 111: loss = 2555.731201171875, MPR = 0.38506555557250977
Epoch 121: loss = 2528.78173828125, MPR = 0.37828996777534485
Epoch 131: loss = 2504.37255859375, MPR = 0.3720034062862396
Epoch 141: loss = 2482.17138671875, MPR = 0.3662884533405304
Epoch 151: loss = 2461.897216796875, MPR = 0.3605768084526062
Epoch 161: loss = 2443.3115234375, MPR = 0.3553735017776489
Epoch 171: loss = 2426.2099609375, MPR = 0.3504636287689209
Epoch 181: loss = 2410.41650390625, MPR = 0.34584492444992065
Epoch 191: loss = 2395.779541015625, MPR = 0.3414628803730011
Epoch 201: loss = 2382.16943359375, MPR = 0.33733564615249634
Epoch 211: loss = 2369.471435546875, MPR = 0.33337050676345825
Epoch 221: loss = 2357.588134765625, MPR = 0.3297162652015686
Epoch 231: loss = 2346.4326171875, MPR = 0.3262231945991516
Epoch 241: loss = 2335.929931640625, MPR = 0.32283303141593933
Epoch 251: loss = 2326.014404296875, MPR = 0.31980958580970764
Epoch 261: loss = 2316.627685546875, MPR = 0.31685543060302734
Epoch 271: loss = 2307.718017578125, MPR = 0.31405016779899597
Epoch 281: loss = 2299.24072265625, MPR = 0.31144261360168457
Epoch 291: loss = 2291.1552734375, MPR = 0.308851033449173
Epoch 301: loss = 2283.42626953125, MPR = 0.3062783479690552
Epoch 311: loss = 2276.021484375, MPR = 0.3039562702178955
Epoch 321: loss = 2268.91357421875, MPR = 0.3015967607498169
Epoch 331: loss = 2262.076904296875, MPR = 0.29945647716522217
Epoch 341: loss = 2255.4892578125, MPR = 0.29731082916259766
Epoch 351: loss = 2249.130859375, MPR = 0.2953222393989563
Epoch 361: loss = 2242.983154296875, MPR = 0.2934694290161133
Epoch 371: loss = 2237.03076171875, MPR = 0.2914471924304962
Epoch 381: loss = 2231.259033203125, MPR = 0.28963983058929443
Epoch 391: loss = 2225.655029296875, MPR = 0.28784212470054626
Epoch 401: loss = 2220.20703125, MPR = 0.2860097289085388
Epoch 411: loss = 2214.904541015625, MPR = 0.2842729091644287
Epoch 421: loss = 2209.73828125, MPR = 0.28258147835731506
Epoch 431: loss = 2204.698974609375, MPR = 0.2809746265411377
Epoch 441: loss = 2199.779052734375, MPR = 0.27942949533462524
Epoch 451: loss = 2194.97119140625, MPR = 0.2778277099132538
Epoch 461: loss = 2190.26904296875, MPR = 0.27629780769348145
Epoch 471: loss = 2185.666259765625, MPR = 0.274911105632782
Epoch 481: loss = 2181.157470703125, MPR = 0.27347779273986816
Epoch 491: loss = 2176.737548828125, MPR = 0.27195316553115845
Epoch 501: loss = 2172.40185546875, MPR = 0.2705703675746918
Epoch 511: loss = 2168.146240234375, MPR = 0.2691323459148407
Epoch 521: loss = 2163.96630859375, MPR = 0.2678680717945099
Epoch 531: loss = 2159.858642578125, MPR = 0.26655977964401245
Epoch 541: loss = 2155.819580078125, MPR = 0.26513636112213135
Epoch 551: loss = 2151.84619140625, MPR = 0.26384276151657104
Epoch 561: loss = 2147.935546875, MPR = 0.2625357508659363
Epoch 571: loss = 2144.084228515625, MPR = 0.26133057475090027
Epoch 581: loss = 2140.290283203125, MPR = 0.2600739598274231
Epoch 591: loss = 2136.55126953125, MPR = 0.25882428884506226
Epoch 601: loss = 2132.864990234375, MPR = 0.25765299797058105
Epoch 611: loss = 2129.22900390625, MPR = 0.2564745843410492
Epoch 621: loss = 2125.64111328125, MPR = 0.25532031059265137
Epoch 631: loss = 2122.1005859375, MPR = 0.2541547417640686
Epoch 641: loss = 2118.60400390625, MPR = 0.2530556321144104
Epoch 651: loss = 2115.15087890625, MPR = 0.2519402801990509
Epoch 661: loss = 2111.73974609375, MPR = 0.250794917345047
Epoch 671: loss = 2108.3681640625, MPR = 0.24969306588172913
Epoch 681: loss = 2105.035400390625, MPR = 0.2486124336719513
Epoch 691: loss = 2101.740234375, MPR = 0.2474401444196701
Epoch 701: loss = 2098.4814453125, MPR = 0.2463863492012024
Epoch 711: loss = 2095.2568359375, MPR = 0.24527926743030548
Epoch 721: loss = 2092.06689453125, MPR = 0.24426716566085815
Epoch 731: loss = 2088.909423828125, MPR = 0.24320873618125916
Epoch 741: loss = 2085.783447265625, MPR = 0.24214108288288116
Epoch 751: loss = 2082.6884765625, MPR = 0.24113862216472626
Epoch 761: loss = 2079.62353515625, MPR = 0.24013280868530273
Epoch 771: loss = 2076.587158203125, MPR = 0.2390918880701065
Epoch 781: loss = 2073.5791015625, MPR = 0.23814517259597778
Epoch 791: loss = 2070.598876953125, MPR = 0.23716293275356293
Epoch 801: loss = 2067.644775390625, MPR = 0.2361738085746765
Epoch 811: loss = 2064.716552734375, MPR = 0.23523275554180145
Epoch 821: loss = 2061.8134765625, MPR = 0.23433946073055267
Epoch 831: loss = 2058.935302734375, MPR = 0.2333018183708191
Epoch 841: loss = 2056.08056640625, MPR = 0.23229117691516876
Epoch 851: loss = 2053.249267578125, MPR = 0.2313777506351471
Epoch 861: loss = 2050.440673828125, MPR = 0.23046423494815826
Epoch 871: loss = 2047.654052734375, MPR = 0.22947664558887482
Epoch 881: loss = 2044.88916015625, MPR = 0.22858408093452454
Epoch 891: loss = 2042.1451416015625, MPR = 0.22764994204044342
Epoch 901: loss = 2039.4217529296875, MPR = 0.22680775821208954
Epoch 911: loss = 2036.7183837890625, MPR = 0.2259148806333542
Epoch 921: loss = 2034.03466796875, MPR = 0.2250954955816269
Epoch 931: loss = 2031.3702392578125, MPR = 0.22421810030937195
Epoch 941: loss = 2028.724609375, MPR = 0.22334490716457367
Epoch 951: loss = 2026.09716796875, MPR = 0.22248581051826477
Epoch 961: loss = 2023.4876708984375, MPR = 0.22162510454654694
Epoch 971: loss = 2020.8958740234375, MPR = 0.22079338133335114
Epoch 981: loss = 2018.3211669921875, MPR = 0.21991132199764252
Epoch 991: loss = 2015.763427734375, MPR = 0.21909254789352417
Epoch 1001: loss = 2013.22216796875, MPR = 0.21827881038188934
Epoch 1011: loss = 2010.6971435546875, MPR = 0.2174924910068512
Epoch 1021: loss = 2008.1878662109375, MPR = 0.21666280925273895
Epoch 1031: loss = 2005.6942138671875, MPR = 0.21585051715373993
Epoch 1041: loss = 2003.2158203125, MPR = 0.2150210291147232
Epoch 1051: loss = 2000.7525634765625, MPR = 0.2141764909029007
Epoch 1061: loss = 1998.3038330078125, MPR = 0.21339759230613708
Epoch 1071: loss = 1995.86962890625, MPR = 0.21255065500736237
Epoch 1081: loss = 1993.44970703125, MPR = 0.21175457537174225
Epoch 1091: loss = 1991.043701171875, MPR = 0.21094690263271332
Epoch 1101: loss = 1988.6512451171875, MPR = 0.21013885736465454
Epoch 1111: loss = 1986.2723388671875, MPR = 0.20938462018966675
Epoch 1121: loss = 1983.906494140625, MPR = 0.20857371389865875
Epoch 1131: loss = 1981.553955078125, MPR = 0.20782716572284698
Epoch 1141: loss = 1979.214111328125, MPR = 0.20708873867988586
Epoch 1151: loss = 1976.886962890625, MPR = 0.20630209147930145
Epoch 1161: loss = 1974.5718994140625, MPR = 0.20556963980197906
Epoch 1171: loss = 1972.2694091796875, MPR = 0.20478560030460358
Epoch 1181: loss = 1969.978759765625, MPR = 0.204040989279747
Epoch 1191: loss = 1967.699951171875, MPR = 0.20328818261623383
Epoch 1201: loss = 1965.4327392578125, MPR = 0.20254342257976532
Epoch 1211: loss = 1963.1771240234375, MPR = 0.201851025223732
Epoch 1221: loss = 1960.9327392578125, MPR = 0.2011633664369583
Epoch 1231: loss = 1958.6993408203125, MPR = 0.20041516423225403
Epoch 1241: loss = 1956.477294921875, MPR = 0.19969207048416138
Epoch 1251: loss = 1954.2657470703125, MPR = 0.19893383979797363
Epoch 1261: loss = 1952.0650634765625, MPR = 0.19819995760917664
Epoch 1271: loss = 1949.8748779296875, MPR = 0.1974755823612213
Epoch 1281: loss = 1947.6949462890625, MPR = 0.19676068425178528
Epoch 1291: loss = 1945.5255126953125, MPR = 0.19607223570346832
Epoch 1301: loss = 1943.3660888671875, MPR = 0.19539451599121094
Epoch 1311: loss = 1941.2166748046875, MPR = 0.19472914934158325
Epoch 1321: loss = 1939.0770263671875, MPR = 0.19400134682655334
Epoch 1331: loss = 1936.947021484375, MPR = 0.1933576911687851
Epoch 1341: loss = 1934.826904296875, MPR = 0.1927061527967453
Epoch 1351: loss = 1932.716064453125, MPR = 0.19209551811218262
Epoch 1361: loss = 1930.614501953125, MPR = 0.19141142070293427
Epoch 1371: loss = 1928.5224609375, MPR = 0.1907438486814499
Epoch 1381: loss = 1926.439453125, MPR = 0.19008603692054749
Epoch 1391: loss = 1924.3653564453125, MPR = 0.18944522738456726
Epoch 1401: loss = 1922.30029296875, MPR = 0.18878254294395447
Epoch 1411: loss = 1920.243896484375, MPR = 0.18817447125911713
Epoch 1421: loss = 1918.196533203125, MPR = 0.18752342462539673
Epoch 1431: loss = 1916.1575927734375, MPR = 0.18688064813613892
Epoch 1441: loss = 1914.1270751953125, MPR = 0.1862339824438095
Epoch 1451: loss = 1912.1051025390625, MPR = 0.18567217886447906
Epoch 1461: loss = 1910.0914306640625, MPR = 0.1850621998310089
Epoch 1471: loss = 1908.086181640625, MPR = 0.18442323803901672
Epoch 1481: loss = 1906.0888671875, MPR = 0.1837783306837082
Epoch 1491: loss = 1904.099609375, MPR = 0.18313471972942352
Epoch 1501: loss = 1902.1185302734375, MPR = 0.18254058063030243
Epoch 1511: loss = 1900.145263671875, MPR = 0.1819496750831604
Epoch 1521: loss = 1898.1798095703125, MPR = 0.18132580816745758
Epoch 1531: loss = 1896.221923828125, MPR = 0.18075956404209137
Epoch 1541: loss = 1894.27197265625, MPR = 0.18014618754386902
Epoch 1551: loss = 1892.329345703125, MPR = 0.1795598268508911
Epoch 1561: loss = 1890.39453125, MPR = 0.17892317473888397
Epoch 1571: loss = 1888.4669189453125, MPR = 0.1783238798379898
Epoch 1581: loss = 1886.546630859375, MPR = 0.1777518093585968
Epoch 1591: loss = 1884.6339111328125, MPR = 0.177133247256279
Epoch 1601: loss = 1882.7281494140625, MPR = 0.17651750147342682
Epoch 1611: loss = 1880.8294677734375, MPR = 0.17590512335300446
Epoch 1621: loss = 1878.93798828125, MPR = 0.17533105611801147
Epoch 1631: loss = 1877.053466796875, MPR = 0.17478972673416138
Epoch 1641: loss = 1875.176025390625, MPR = 0.17420007288455963
Epoch 1651: loss = 1873.3055419921875, MPR = 0.1736038327217102
Epoch 1661: loss = 1871.4415283203125, MPR = 0.17308133840560913
Epoch 1671: loss = 1869.5845947265625, MPR = 0.17252808809280396
Epoch 1681: loss = 1867.7342529296875, MPR = 0.17199209332466125
Epoch 1691: loss = 1865.890625, MPR = 0.1714583784341812
Epoch 1701: loss = 1864.053466796875, MPR = 0.1708904206752777
Epoch 1711: loss = 1862.2227783203125, MPR = 0.17033827304840088
Epoch 1721: loss = 1860.3988037109375, MPR = 0.1698158085346222
Epoch 1731: loss = 1858.5810546875, MPR = 0.16923466324806213
Epoch 1741: loss = 1856.769775390625, MPR = 0.16867472231388092
Epoch 1751: loss = 1854.9647216796875, MPR = 0.16809603571891785
Epoch 1761: loss = 1853.1658935546875, MPR = 0.1675334870815277
Epoch 1771: loss = 1851.373291015625, MPR = 0.16702261567115784
Epoch 1781: loss = 1849.5867919921875, MPR = 0.16645628213882446
Epoch 1791: loss = 1847.806640625, MPR = 0.16592250764369965
Epoch 1801: loss = 1846.0322265625, MPR = 0.1653982400894165
Epoch 1811: loss = 1844.26416015625, MPR = 0.16486652195453644
Epoch 1821: loss = 1842.501708984375, MPR = 0.16438725590705872
Epoch 1831: loss = 1840.745361328125, MPR = 0.16385836899280548
Epoch 1841: loss = 1838.9947509765625, MPR = 0.1633218228816986
Epoch 1851: loss = 1837.25, MPR = 0.16278813779354095
Epoch 1861: loss = 1835.5111083984375, MPR = 0.162239670753479
Epoch 1871: loss = 1833.7779541015625, MPR = 0.16180205345153809
Epoch 1881: loss = 1832.05029296875, MPR = 0.16129423677921295
Epoch 1891: loss = 1830.328369140625, MPR = 0.1607944667339325
Epoch 1901: loss = 1828.612060546875, MPR = 0.16032998263835907
Epoch 1911: loss = 1826.9013671875, MPR = 0.15987691283226013
Epoch 1921: loss = 1825.1961669921875, MPR = 0.15936803817749023
Epoch 1931: loss = 1823.496337890625, MPR = 0.1588490903377533
Epoch 1941: loss = 1821.802001953125, MPR = 0.1583193838596344
Epoch 1951: loss = 1820.113037109375, MPR = 0.1578405499458313
Epoch 1961: loss = 1818.4293212890625, MPR = 0.15736649930477142
Epoch 1971: loss = 1816.7510986328125, MPR = 0.15690010786056519
Epoch 1981: loss = 1815.0782470703125, MPR = 0.15642152726650238
Epoch 1991: loss = 1813.4105224609375, MPR = 0.1559297889471054
Epoch 2001: loss = 1811.748046875, MPR = 0.15546661615371704
Epoch 2011: loss = 1810.090576171875, MPR = 0.15499794483184814
Epoch 2021: loss = 1808.4383544921875, MPR = 0.15450796484947205
Epoch 2031: loss = 1806.7911376953125, MPR = 0.15401971340179443
Epoch 2041: loss = 1805.149169921875, MPR = 0.1535419076681137
Epoch 2051: loss = 1803.511962890625, MPR = 0.15308432281017303
Epoch 2061: loss = 1801.8800048828125, MPR = 0.15264251828193665
Epoch 2071: loss = 1800.2529296875, MPR = 0.152229443192482
Epoch 2081: loss = 1798.6307373046875, MPR = 0.15174932777881622
Epoch 2091: loss = 1797.013427734375, MPR = 0.15132001042366028
Epoch 2101: loss = 1795.4010009765625, MPR = 0.1508551985025406
Epoch 2111: loss = 1793.79345703125, MPR = 0.15041248500347137
Epoch 2121: loss = 1792.190673828125, MPR = 0.14993895590305328
Epoch 2131: loss = 1790.5927734375, MPR = 0.14951570332050323
Epoch 2141: loss = 1788.99951171875, MPR = 0.14902658760547638
Epoch 2151: loss = 1787.410888671875, MPR = 0.14861877262592316
Epoch 2161: loss = 1785.8270263671875, MPR = 0.14821602404117584
Epoch 2171: loss = 1784.247802734375, MPR = 0.1477590799331665
Epoch 2181: loss = 1782.673095703125, MPR = 0.14732365310192108
Epoch 2191: loss = 1781.1031494140625, MPR = 0.14689598977565765
Epoch 2201: loss = 1779.53759765625, MPR = 0.14648492634296417
Epoch 2211: loss = 1777.9766845703125, MPR = 0.14605313539505005
Epoch 2221: loss = 1776.4202880859375, MPR = 0.14567731320858002
Epoch 2231: loss = 1774.8682861328125, MPR = 0.1452566534280777
Epoch 2241: loss = 1773.32080078125, MPR = 0.14483048021793365
Epoch 2251: loss = 1771.7777099609375, MPR = 0.14440979063510895
Epoch 2261: loss = 1770.239013671875, MPR = 0.14404475688934326
Epoch 2271: loss = 1768.7047119140625, MPR = 0.14361563324928284
Epoch 2281: loss = 1767.1748046875, MPR = 0.14323313534259796
Epoch 2291: loss = 1765.649169921875, MPR = 0.14283223450183868
Epoch 2301: loss = 1764.127685546875, MPR = 0.14245817065238953
Epoch 2311: loss = 1762.610595703125, MPR = 0.14211037755012512
Epoch 2321: loss = 1761.097900390625, MPR = 0.14173652231693268
Epoch 2331: loss = 1759.58935546875, MPR = 0.14132921397686005
Epoch 2341: loss = 1758.0848388671875, MPR = 0.1409168690443039
Epoch 2351: loss = 1756.5845947265625, MPR = 0.14053547382354736
Epoch 2361: loss = 1755.0885009765625, MPR = 0.14011985063552856
Epoch 2371: loss = 1753.5965576171875, MPR = 0.1397407203912735
Epoch 2381: loss = 1752.108642578125, MPR = 0.13935422897338867
Epoch 2391: loss = 1750.624755859375, MPR = 0.13899874687194824
Epoch 2401: loss = 1749.1451416015625, MPR = 0.13861201703548431
Epoch 2411: loss = 1747.66943359375, MPR = 0.13822154700756073
Epoch 2421: loss = 1746.19775390625, MPR = 0.137808158993721
Epoch 2431: loss = 1744.72998046875, MPR = 0.13747115433216095
Epoch 2441: loss = 1743.266357421875, MPR = 0.1370745152235031
Epoch 2451: loss = 1741.806396484375, MPR = 0.13670477271080017
Epoch 2461: loss = 1740.3507080078125, MPR = 0.13635548949241638
Epoch 2471: loss = 1738.898681640625, MPR = 0.1359701305627823
Epoch 2481: loss = 1737.4505615234375, MPR = 0.1356033831834793
Epoch 2491: loss = 1736.00634765625, MPR = 0.13522766530513763
Epoch 2501: loss = 1734.5660400390625, MPR = 0.1348479688167572
Epoch 2511: loss = 1733.12939453125, MPR = 0.13448064029216766
Epoch 2521: loss = 1731.6966552734375, MPR = 0.1341244876384735
Epoch 2531: loss = 1730.2677001953125, MPR = 0.1337648332118988
Epoch 2541: loss = 1728.8426513671875, MPR = 0.13341987133026123
Epoch 2551: loss = 1727.4210205078125, MPR = 0.1330593228340149
Epoch 2561: loss = 1726.0032958984375, MPR = 0.13269343972206116
Epoch 2571: loss = 1724.58935546875, MPR = 0.1323353350162506
Epoch 2581: loss = 1723.178955078125, MPR = 0.1319807767868042
Epoch 2591: loss = 1721.7723388671875, MPR = 0.1315949261188507
Epoch 2601: loss = 1720.369384765625, MPR = 0.13126789033412933
Epoch 2611: loss = 1718.969970703125, MPR = 0.13093574345111847
Epoch 2621: loss = 1717.57421875, MPR = 0.1305854320526123
Epoch 2631: loss = 1716.1820068359375, MPR = 0.13022559881210327
Epoch 2641: loss = 1714.7933349609375, MPR = 0.1298268586397171
Epoch 2651: loss = 1713.408203125, MPR = 0.12946082651615143
Epoch 2661: loss = 1712.02685546875, MPR = 0.12910057604312897
Epoch 2671: loss = 1710.648681640625, MPR = 0.12875455617904663
Epoch 2681: loss = 1709.2744140625, MPR = 0.12840980291366577
Epoch 2691: loss = 1707.903564453125, MPR = 0.12804031372070312
Epoch 2701: loss = 1706.535888671875, MPR = 0.12769411504268646
Epoch 2711: loss = 1705.171875, MPR = 0.12739276885986328
Epoch 2721: loss = 1703.8114013671875, MPR = 0.1270713210105896
Epoch 2731: loss = 1702.454345703125, MPR = 0.12674051523208618
Epoch 2741: loss = 1701.1005859375, MPR = 0.12641552090644836
Epoch 2751: loss = 1699.750244140625, MPR = 0.12606988847255707
Epoch 2761: loss = 1698.4031982421875, MPR = 0.12571831047534943
Epoch 2771: loss = 1697.0596923828125, MPR = 0.12538988888263702
Epoch 2781: loss = 1695.7193603515625, MPR = 0.12506872415542603
Epoch 2791: loss = 1694.3826904296875, MPR = 0.12477050721645355
Epoch 2801: loss = 1693.048828125, MPR = 0.12443113327026367
Epoch 2811: loss = 1691.71875, MPR = 0.12409350275993347
Epoch 2821: loss = 1690.3917236328125, MPR = 0.12378843873739243
Epoch 2831: loss = 1689.0679931640625, MPR = 0.1234511286020279
Epoch 2841: loss = 1687.7476806640625, MPR = 0.12311851978302002
Epoch 2851: loss = 1686.430419921875, MPR = 0.12281771749258041
Epoch 2861: loss = 1685.116455078125, MPR = 0.12250423431396484
Epoch 2871: loss = 1683.8056640625, MPR = 0.12220129370689392
Epoch 2881: loss = 1682.4981689453125, MPR = 0.12189020961523056
Epoch 2891: loss = 1681.19384765625, MPR = 0.12159358710050583
Epoch 2901: loss = 1679.892822265625, MPR = 0.12128718942403793
Epoch 2911: loss = 1678.5947265625, MPR = 0.12097886204719543
Epoch 2921: loss = 1677.2998046875, MPR = 0.12066102772951126
Epoch 2931: loss = 1676.0081787109375, MPR = 0.12035465985536575
Epoch 2941: loss = 1674.7196044921875, MPR = 0.1200399324297905
Epoch 2951: loss = 1673.43408203125, MPR = 0.1197352334856987
Epoch 2961: loss = 1672.1517333984375, MPR = 0.1194266676902771
Epoch 2971: loss = 1670.87255859375, MPR = 0.11912351846694946
Epoch 2981: loss = 1669.5963134765625, MPR = 0.11882508546113968
Epoch 2991: loss = 1668.3232421875, MPR = 0.11850783973932266
Epoch 3001: loss = 1667.0531005859375, MPR = 0.11820409446954727
Epoch 3011: loss = 1665.7861328125, MPR = 0.1178923174738884
Epoch 3021: loss = 1664.5220947265625, MPR = 0.11760333180427551
Epoch 3031: loss = 1663.260986328125, MPR = 0.11729979515075684
Epoch 3041: loss = 1662.0030517578125, MPR = 0.11700273305177689
Epoch 3051: loss = 1660.748046875, MPR = 0.11673811823129654
Epoch 3061: loss = 1659.4959716796875, MPR = 0.1164623349905014
Epoch 3071: loss = 1658.246826171875, MPR = 0.11616821587085724
Epoch 3081: loss = 1657.000732421875, MPR = 0.11586907505989075
Epoch 3091: loss = 1655.757568359375, MPR = 0.11560214310884476
Epoch 3101: loss = 1654.5172119140625, MPR = 0.11530335992574692
Epoch 3111: loss = 1653.280029296875, MPR = 0.11503943800926208
Epoch 3121: loss = 1652.0455322265625, MPR = 0.11472249031066895
Epoch 3131: loss = 1650.8140869140625, MPR = 0.11443927884101868
Epoch 3141: loss = 1649.5853271484375, MPR = 0.11412203311920166
Epoch 3151: loss = 1648.3597412109375, MPR = 0.11380717903375626
Epoch 3161: loss = 1647.13671875, MPR = 0.11350682377815247

In [90]:
lmf.save("models", "lmf_all_types_100")
lmf = LogisticMatrixFactorization.load(os.path.join("models", "lmf_all_types_100.pt"))

In [91]:
px.line(x=range(len(lmf.losses)), y=lmf.losses.cpu(), title="Loss").show()
px.line(x=range(len(lmf.mprs)), y=lmf.mprs.cpu(), title="MPRS").show()

In [92]:
user_id = matrix_mf.usernames_to_ids(["michelle"])[0]

# Get the top 10 recommendations for the user
top_10_ids, top_10_ids_scores = lmf.recommend(user_id, top_k=20, filter_user_items=True)

# Get the top 10 recommendations for the user
matrix_mf.items_ids_to_df(top_10_ids)[spoti.PRETTY_PRINT_FEATURES]

,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
1,jaslkh,ROSALÍA,SAOKO,2022,70,0.827,0.768,0.2650,0.7900,0.000024,0.4970,0.7340,99.988,-5.702,137533,2022,70
46,jaslkh,Khruangbin,So We Won't Forget,2020,65,0.641,0.413,0.1020,0.0305,0.844000,0.1830,0.9670,101.270,-13.212,298333,2020,65
61,jaslkh,Etta James,At Last,1960,79,0.274,0.348,0.0293,0.5470,0.013300,0.3340,0.3280,87.430,-8.631,179693,1960,79
103,jaslkh,Sebastian Yatra,Dos Oruguitas,2021,69,0.423,0.355,0.0454,0.7610,0.000000,0.0915,0.4650,93.788,-10.565,214613,2021,69
105,jaslkh,Feyesal,please never fall in love again,2019,53,0.713,0.345,0.0374,0.3640,0.002520,0.3930,0.3470,107.637,-8.550,157642,2019,53
110,jaslkh,Poupie,Feux (feat. Jul),2020,44,0.858,0.645,0.3710,0.4780,0.000000,0.0707,0.4860,132.085,-5.564,197296,2020,44
111,jaslkh,Khruangbin,So We Won't Forget,2020,65,0.641,0.413,0.1020,0.0305,0.844000,0.1830,0.9670,101.270,-13.212,298333,2020,65
113,jaslkh,Joji,Glimpse of Us,2022,84,0.440,0.317,0.0531,0.8910,0.000005,0.1410,0.2680,169.914,-9.258,233456,2022,84
115,jaslkh,Luidji,Gisèle - Part 4 - Piano Session,2019,45,0.607,0.316,0.0688,0.8100,0.000030,0.1230,0.3050,86.890,-13.653,299873,2019,45
133,jaslkh,Ashh,Motel,2015,67,0.393,0.627,0.0537,0.2170,0.010200,0.1030,0.0966,92.937,-10.743,241352,2015,67
1609,owen,Josman,Doré,2021,36,0.784,0.504,0.0575,0.4700,0.000001,0.0999,0.3750,140.012,-8.727,195428,2021,36
11362,lsirwguhu,Preston Pablo,Flowers Need Rain,2022,67,0.655,0.539,0.0800,0.0290,0.000000,0.1700,0.2210,119.914,-7.596,168126,2022,67
11363,lsirwguhu,Charlie Puth,Attention,2018,87,0.775,0.613,0.0542,0.1090,0.000023,0.1340,0.7970,100.066,-4.586,208786,2018,87
11367,lsirwguhu,RADWIMPS,Suzume,2022,69,0.565,0.410,0.0311,0.6500,0.000000,0.3090,0.3600,78.010,-6.616,238560,2022,69
11369,lsirwguhu,SERA,Head Held High,2022,63,0.613,0.579,0.0381,0.1280,0.000000,0.5690,0.2270,94.958,-6.428,196220,2022,63
11371,lsirwguhu,Miley Cyrus,Angels Like You,2020,89,0.672,0.642,0.0313,0.0981,0.000000,0.1000,0.4940,121.981,-4.035,196453,2020,89
11374,lsirwguhu,Royal & the Serpent,overwhelmed - Chri$tian Gate$ remix,2021,66,0.619,0.502,0.2490,0.1780,0.000000,0.1550,0.3800,174.196,-8.097,134482,2021,66
11384,lsirwguhu,Sik World,I Can't Believe I Died,2020,43,0.811,0.603,0.1560,0.4680,0.000018,0.1100,0.1560,140.119,-6.306,179633,2020,43
11392,lsirwguhu,Rory Webley,Joker,2020,58,0.677,0.662,0.2370,0.2510,0.000002,0.2220,0.4640,111.980,-9.322,141272,2020,58
11411,lsirwguhu,Natalie Jane,Do or Die,2023,70,0.446,0.696,0.0580,0.0375,0.000000,0.1120,0.3010,181.887,-5.755,150314,2023,70
11419,lsirwguhu,VOILÀ,If You Were Me,2020,49,0.589,0.492,0.0520,0.2850,0.000000,0.2650,0.5450,95.960,-9.966,173476,2020,49
11424,lsirwguhu,Sik World,I Can't Believe I Died,2020,43,0.811,0.603,0.1560,0.4680,0.000018,0.1100,0.1560,140.119,-6.306,179633,2020,43
11428,lsirwguhu,Miley Cyrus,Angels Like You,2020,89,0.672,0.642,0.0313,0.0981,0.000000,0.1000,0.4940,121.981,-4.035,196453,2020,89
11430,lsirwguhu,RADWIMPS,Suzume,2022,69,0.565,0.410,0.0311,0.6500,0.000000,0.3090,0.3600,78.010,-6.616,238560,2022,69
11432,lsirwguhu,Royal & the Serpent,overwhelmed - Chri$tian Gate$ remix,2021,66,0.619,0.502,0.2490,0.1780,0.000000,0.1550,0.3800,174.196,-8.097,134482,2021,66
11433,lsirwguhu,SERA,Head Held High,2022,63,0.613,0.579,0.0381,0.1280,0.000000,0.5690,0.2270,94.958,-6.428,196220,2022,63
11439,lsirwguhu,Rory Webley,Joker,2020,58,0.677,0.662,0.2370,0.2510,0.000002,0.2220,0.4640,111.980,-9.322,141272,2020,58
11492,lsirwguhu,RADWIMPS,Suzume,2022,69,0.565,0.410,0.0311,0.6500,0.000000,0.3090,0.3600,78.010,-6.616,238560,2022,69
11496,lsirwguhu,Miley Cyrus,Angels Like You,2020,89,0.672,0.642,0.0313,0.0981,0.000000,0.1000,0.4940,121.981,-4.035,196453,2020,89
11502,lsirwguhu,Preston Pablo,Flowers Need Rain,2022,67,0.655,0.539,0.0800,0.0290,0.000000,0.1700,0.2210,119.914,-7.596,168126,2022,67
11507,lsirwguhu,Royal & the Serpent,overwhelmed - Chri$tian Gate$ remix,2021,66,0.619,0.502,0.2490,0.1780,0.000000,0.1550,0.3800,174.196,-8.097,134482,2021,66
11509,lsirwguhu,Charlie Puth,Attention,2018,87,0.775,0.613,0.0542,0.1090,0.000023,0.1340,0.7970,100.066,-4.586,208786,2018,87

In [93]:
if lmf.num_factors <= 3:
    df_tracks = df_matrix_mf.copy()
    df_tracks = df_tracks.sample(frac=1) # Shuffle the dataframe
    df_tracks = df_tracks[:1000] # Keep only 1000 tracks

    # Add item latent factors to the dataframe
    items_latent_columns = [f"track_latent_{i}" for i in range(lmf.num_factors)]
    for track_id in df_tracks["id"].unique():
        latent_factors = lmf.get_item_latent_factors(matrix_mf.items_to_ids([track_id])[0]).tolist()
        df_tracks.loc[df_tracks["id"] == track_id, items_latent_columns] = latent_factors

    # Add user latent factors to the dataframe
    users_latent_columns = [f"latent_factor_{i}" for i in range(lmf.num_factors)]
    for user_id in df_tracks["username"].unique():
        latent_factors = lmf.get_user_latent_factors(matrix_mf.usernames_to_ids([user_id])[0]).tolist()
        df_tracks.loc[df_tracks["username"] == user_id, users_latent_columns] = latent_factors

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=items_latent_columns,
    ).show()

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=users_latent_columns,
    ).show()