In [1]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML
from lib.matrix_dataset import MatrixDataset
from recommenders.lmf import LogisticMatrixFactorization

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    device = mps_device
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print ("MPS device not found.")

if device == torch.device("cuda"):
    dtype = torch.float32
    print("Using CUDA.")
elif device == torch.device("cpu"):
    dtype = torch.float64
    print("Using CPU.")
elif device == torch.device("mps"):
    dtype = torch.float32
    print("Using MPS.")

# device = "cpu"
# dtype = torch.float64

tensor([1.], device='mps:0')
Using MPS.

# Import data

In [3]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 1, "long_term": 1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,1.00,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.98,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.96,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.94,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.92,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [4]:
df_matrix_mf = df.copy()
df_matrix_mf.loc[df_matrix_mf["type"] == "liked_track", "affinity"] = 0.5
df_matrix_mf.loc[df_matrix_mf["type"] == "playlist", "affinity"] = 0.3

used_types = ["top_track", "liked_track", "playlist"]
used_types = ["top_track"]
df_matrix_mf = df_matrix_mf[df["type"].isin(used_types)]
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]

,username,id,affinity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
0,jaslkh,75rqqKvzJCGv2oq9C4yFDt,1.00,0.630,0.374,0.2270,0.8610,0.000075,0.2940,0.3730,104.955,-9.007,196426,2023,63
1,jaslkh,2FYGZDfsAnNsrm1gVbyKnG,0.98,0.827,0.768,0.2650,0.7900,0.000024,0.4970,0.7340,99.988,-5.702,137533,2022,70
2,jaslkh,4kroNlz8BTfswE4M0i3YCh,0.96,0.583,0.297,0.4060,0.8790,0.000000,0.1270,0.2910,124.279,-11.273,162906,2022,61
3,jaslkh,2N3YZ075lq9z1ObaAiX6l1,0.94,0.651,0.327,0.4020,0.9280,0.000000,0.2250,0.5510,135.325,-10.070,89749,2022,54
4,jaslkh,2SiAcexM2p1yX6joESbehd,0.92,0.555,0.634,0.2730,0.1290,0.000002,0.1880,0.5550,170.228,-5.522,174044,2023,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12318,dany,4GRMPDD3V6rM2BlmRdYCUJ,0.10,0.491,0.699,0.0924,0.1620,0.864000,0.1050,0.0762,130.325,-10.500,214000,2022,41
12319,dany,17Xof0GRZZfS7ZgjUJ27pH,0.08,0.271,0.503,0.0314,0.7500,0.000102,0.0941,0.0742,127.960,-4.142,241821,2020,50
12320,dany,2Rd4eJ4KwXQQn2sMSToyUM,0.06,0.319,0.236,0.0318,0.8980,0.000016,0.2720,0.2540,162.351,-9.644,156091,2021,6
12321,dany,4fPBB44eDH71YohayI4eKV,0.04,0.630,0.908,0.0326,0.0238,0.592000,0.1160,0.9680,120.522,-2.420,189226,2006,75
12322,dany,2obi4sPO32ZkIiNwejVLRq,0.02,0.317,0.547,0.0333,0.1490,0.000005,0.3850,0.2940,139.752,-8.122,194173,2000,37

In [5]:
df_matrix_mf = pd.read_csv(os.path.join(data_path.DATA_PATH, "artificial_data.csv"), index_col=0)

In [6]:
df_matrix_mf["affinity"] *= 1

In [7]:
matrix_mf = MatrixDataset(df_matrix_mf, "username", "id", "affinity", device=device, dtype=dtype)
R = matrix_mf.R
R.to(device)
R.shape

torch.Size([497, 53477])

In [8]:
alpha = matrix_mf.compute_alpha().item()
R *= 0.1
alpha

353.5196533203125

In [9]:
num_latent_factors = 3
lmf = LogisticMatrixFactorization(
    counts=R,
    num_factors=num_latent_factors,
    reg_param=0.01,
    device=device,
    dtype=dtype,
)
lmf.to(device)

num_epochs = 100
lmf.train_model(
    num_epochs=num_epochs,
    learning_rate=1,
    log_interval=1,
    tqdm=False
)

Epoch: 1, log-likelihood: 6936001.5000, MPR: 0.4993
Epoch: 2, log-likelihood: 2934923.5000, MPR: 0.4989
Epoch: 3, log-likelihood: 621249.5000, MPR: 0.4917
Epoch: 4, log-likelihood: 299230.8750, MPR: 0.4807
Epoch: 5, log-likelihood: 203624.9219, MPR: 0.4715
Epoch: 6, log-likelihood: 159124.4688, MPR: 0.4635
Epoch: 7, log-likelihood: 134170.0781, MPR: 0.4571
Epoch: 8, log-likelihood: 118545.8984, MPR: 0.4511
Epoch: 9, log-likelihood: 108026.9062, MPR: 0.4463
Epoch: 10, log-likelihood: 100553.5469, MPR: 0.4419
Epoch: 11, log-likelihood: 95038.3906, MPR: 0.4381
Epoch: 12, log-likelihood: 90832.1406, MPR: 0.4347
Epoch: 13, log-likelihood: 87550.2578, MPR: 0.4317
Epoch: 14, log-likelihood: 84927.8672, MPR: 0.4289
Epoch: 15, log-likelihood: 82802.5859, MPR: 0.4264
Epoch: 16, log-likelihood: 81051.3438, MPR: 0.4241
Epoch: 17, log-likelihood: 79592.5469, MPR: 0.4220
Epoch: 18, log-likelihood: 78361.1641, MPR: 0.4200
Epoch: 19, log-likelihood: 77312.8594, MPR: 0.4181
Epoch: 20, log-likelihood: 76412.0547, MPR: 0.4164
Epoch: 21, log-likelihood: 75632.2578, MPR: 0.4148
Epoch: 22, log-likelihood: 74952.1484, MPR: 0.4132
Epoch: 23, log-likelihood: 74355.6641, MPR: 0.4117
Epoch: 24, log-likelihood: 73828.7812, MPR: 0.4104
Epoch: 25, log-likelihood: 73361.4062, MPR: 0.4090
Epoch: 26, log-likelihood: 72944.2031, MPR: 0.4077
Epoch: 27, log-likelihood: 72570.6484, MPR: 0.4065
Epoch: 28, log-likelihood: 72234.1484, MPR: 0.4053
Epoch: 29, log-likelihood: 71930.3594, MPR: 0.4042
Epoch: 30, log-likelihood: 71654.6641, MPR: 0.4031
Epoch: 31, log-likelihood: 71403.6797, MPR: 0.4021
Epoch: 32, log-likelihood: 71174.6562, MPR: 0.4010
Epoch: 33, log-likelihood: 70964.2578, MPR: 0.4001
Epoch: 34, log-likelihood: 70771.5781, MPR: 0.3991
Epoch: 35, log-likelihood: 70592.5391, MPR: 0.3982
Epoch: 36, log-likelihood: 70428.0078, MPR: 0.3972
Epoch: 37, log-likelihood: 70274.8750, MPR: 0.3964
Epoch: 38, log-likelihood: 70132.9766, MPR: 0.3955
Epoch: 39, log-likelihood: 70000.6562, MPR: 0.3947
Epoch: 40, log-likelihood: 69877.2188, MPR: 0.3938
Epoch: 41, log-likelihood: 69761.7188, MPR: 0.3930
Epoch: 42, log-likelihood: 69653.4219, MPR: 0.3922
Epoch: 43, log-likelihood: 69551.7422, MPR: 0.3915
Epoch: 44, log-likelihood: 69455.9297, MPR: 0.3907
Epoch: 45, log-likelihood: 69365.6875, MPR: 0.3900
Epoch: 46, log-likelihood: 69280.3125, MPR: 0.3893
Epoch: 47, log-likelihood: 69199.7344, MPR: 0.3886
Epoch: 48, log-likelihood: 69123.2188, MPR: 0.3879
Epoch: 49, log-likelihood: 69050.9922, MPR: 0.3872
Epoch: 50, log-likelihood: 68981.7422, MPR: 0.3865
Epoch: 51, log-likelihood: 68916.6562, MPR: 0.3859
Epoch: 52, log-likelihood: 68852.9297, MPR: 0.3852
Epoch: 53, log-likelihood: 68793.3828, MPR: 0.3846
Epoch: 54, log-likelihood: 68735.2578, MPR: 0.3839
Epoch: 55, log-likelihood: 68680.6484, MPR: 0.3833
Epoch: 56, log-likelihood: 68627.2031, MPR: 0.3827
Epoch: 57, log-likelihood: 68576.7344, MPR: 0.3821
Epoch: 58, log-likelihood: 68527.5156, MPR: 0.3815
Epoch: 59, log-likelihood: 68480.6797, MPR: 0.3809
Epoch: 60, log-likelihood: 68435.2812, MPR: 0.3803
Epoch: 61, log-likelihood: 68391.7266, MPR: 0.3798
Epoch: 62, log-likelihood: 68349.6094, MPR: 0.3792
Epoch: 63, log-likelihood: 68308.9219, MPR: 0.3787
Epoch: 64, log-likelihood: 68269.5938, MPR: 0.3781
Epoch: 65, log-likelihood: 68231.3906, MPR: 0.3776
Epoch: 66, log-likelihood: 68194.5156, MPR: 0.3771
Epoch: 67, log-likelihood: 68158.6484, MPR: 0.3765
Epoch: 68, log-likelihood: 68124.0156, MPR: 0.3760
Epoch: 69, log-likelihood: 68090.1406, MPR: 0.3755
Epoch: 70, log-likelihood: 68057.5469, MPR: 0.3750
Epoch: 71, log-likelihood: 68025.2969, MPR: 0.3745
Epoch: 72, log-likelihood: 67994.4141, MPR: 0.3740
Epoch: 73, log-likelihood: 67963.7812, MPR: 0.3735
Epoch: 74, log-likelihood: 67934.4453, MPR: 0.3730
Epoch: 75, log-likelihood: 67905.1953, MPR: 0.3725
Epoch: 76, log-likelihood: 67877.1719, MPR: 0.3720
Epoch: 77, log-likelihood: 67849.1953, MPR: 0.3716
Epoch: 78, log-likelihood: 67822.2969, MPR: 0.3711
Epoch: 79, log-likelihood: 67795.6406, MPR: 0.3706
Epoch: 80, log-likelihood: 67769.8125, MPR: 0.3702
Epoch: 81, log-likelihood: 67744.3594, MPR: 0.3697
Epoch: 82, log-likelihood: 67719.5312, MPR: 0.3692
Epoch: 83, log-likelihood: 67695.1328, MPR: 0.3688
Epoch: 84, log-likelihood: 67671.2500, MPR: 0.3684
Epoch: 85, log-likelihood: 67647.7969, MPR: 0.3679
Epoch: 86, log-likelihood: 67624.7812, MPR: 0.3675
Epoch: 87, log-likelihood: 67602.1719, MPR: 0.3670
Epoch: 88, log-likelihood: 67579.9688, MPR: 0.3666
Epoch: 89, log-likelihood: 67558.1328, MPR: 0.3662
Epoch: 90, log-likelihood: 67536.6719, MPR: 0.3657
Epoch: 91, log-likelihood: 67515.5625, MPR: 0.3653
Epoch: 92, log-likelihood: 67494.8125, MPR: 0.3649
Epoch: 93, log-likelihood: 67474.3516, MPR: 0.3645
Epoch: 94, log-likelihood: 67454.2734, MPR: 0.3641
Epoch: 95, log-likelihood: 67434.3750, MPR: 0.3637
Epoch: 96, log-likelihood: 67414.9297, MPR: 0.3633
Epoch: 97, log-likelihood: 67395.4844, MPR: 0.3628
Epoch: 98, log-likelihood: 67376.5625, MPR: 0.3624
Epoch: 99, log-likelihood: 67357.5781, MPR: 0.3620
Epoch: 100, log-likelihood: 67339.0938, MPR: 0.3616

In [10]:
lmf.save("models", "lmf")

In [11]:
px.line(x=range(len(lmf.losses)), y=lmf.losses.cpu(), title="Loss").show()
px.line(x=range(len(lmf.mprs)), y=lmf.mprs.cpu(), title="MPRS").show()

In [13]:
user_id = matrix_mf.usernames_to_ids(["paul"])[0]
print(user_id)

# Get the top 10 recommendations for the user
top_10_ids, top_10_ids_scores = lmf.recommend(user_id, top_k=20, filter_user_items=True)

# Get the top 10 recommendations for the user
matrix_mf.item_ids_to_df(top_10_ids)

-1

,id,username,danceability,duration_ms,instrumentalness,affinity
15,Couple,Stephanie Ross,1.118199,0.971794,1.014813,1.092027
94,Couple,Stephanie Ross,1.025700,0.899719,0.909549,0.868304
337,Property,Amanda Bautista,1.032118,0.999721,1.133375,0.915211
343,Opportunity,Amanda Bautista,1.093076,0.801353,0.914944,0.829884
437,Individual,Amanda Bautista,1.003964,0.907915,1.029226,0.996542
...,...,...,...,...,...,...
74676,Soldier,Dr. William Schaefer,1.122970,0.924892,0.879718,1.029970
74709,Scientist,Tyler Patton,1.053394,1.124458,0.795413,0.857619
74794,Determine,Tyler Patton,0.986698,1.067318,1.064204,1.029139
74822,Character,Tyler Patton,0.976955,0.918152,1.091632,1.062274
74837,Couple,Tyler Patton,0.876797,1.003038,0.874043,0.928267

In [15]:
if lmf.num_factors <= 3:
    df_tracks = df_matrix_mf.copy()
    df_tracks = df_tracks.sample(frac=1) # Shuffle the dataframe
    df_tracks = df_tracks[:150] # Keep only 1000 tracks

    # Add item latent factors to the dataframe
    items_latent_columns = [f"track_latent_{i}" for i in range(lmf.num_factors)]
    for track_id in df_tracks["id"].unique():
        latent_factors = lmf.get_item_factors([matrix_mf.itemnames_to_ids([track_id])[0]]).tolist()
        df_tracks.loc[df_tracks["id"] == track_id, items_latent_columns] = latent_factors

    # Add user latent factors to the dataframe
    users_latent_columns = [f"latent_factor_{i}" for i in range(lmf.num_factors)]
    for user_id in df_tracks["username"].unique():
        latent_factors = lmf.get_user_factors([matrix_mf.usernames_to_ids([user_id])[0]]).tolist()
        df_tracks.loc[df_tracks["username"] == user_id, users_latent_columns] = latent_factors

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=items_latent_columns,
    ).show()

    plotting.plot_latent_space(
        df=df_tracks,
        color=df_tracks["username"],
        text=df_tracks["username"],
        latent_columns=users_latent_columns,
    ).show()