In [1]:
import pandas as pd
from lib import spoti
from constants import data_path, users_list
import os

In [5]:
[u.get_auth_url() for u in users_list.USERS]

['https://accounts.spotify.com/authorize?client_id=a75393ab40f14735bc524677cb4ce3b7&response_type=code&redirect_uri=https%3A%2F%2Fgithub.com%2Fowengombas&scope=user-library-read+user-read-currently-playing+user-read-playback-state+playlist-read-collaborative+user-top-read+user-read-recently-played+user-library-read+user-read-email+']

In [6]:
[u.log_user() for u in users_list.USERS]

[None]

In [7]:
df_playlists = pd.DataFrame()
for u in users_list.USERS:
    df_playlist = u.get_playlists()
    df_playlist.to_json(os.path.join(data_path.DATA_PATH, f"{u.username}_playlists.json"), orient="records")
    df_playlists = pd.concat([df_playlists, df_playlist])
df_playlists

,collaborative,description,external_urls,href,id,images,name,owner,primary_color,public,snapshot_id,tracks,type,uri,username
0,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/2qGpHIzxE...,2qGpHIzxExD8rOMQFFcNq0,"[{'height': 640, 'url': 'https://mosaic.scdn.c...",Musique chill,"{'display_name': 'michele', 'external_urls': {...",None,True,OCwxYmMwNDI3MTk0ZWQ3MzZhYjJjOTQxMjY4OTg0YWVkNG...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:2qGpHIzxExD8rOMQFFcNq0,lsirwguhu
1,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/6AYbXK40T...,6AYbXK40T54z7OBGPWHLHN,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Cantine pour enfant,"{'display_name': 'michele', 'external_urls': {...",None,True,MiwxZGQzMjNhMWQyYjQwYzY3MDk1ODY0NDQ4YTQ0MTA5Mj...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:6AYbXK40T54z7OBGPWHLHN,lsirwguhu
2,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/390N3INmy...,390N3INmyQ9v0uMJcR6iZ1,"[{'height': 640, 'url': 'https://mosaic.scdn.c...",Philippe,"{'display_name': 'michele', 'external_urls': {...",None,True,MzAsMDEzMmMzNTE1YmVhOTA1NDRiZDc1YmRhZTRiZGRkMm...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:390N3INmyQ9v0uMJcR6iZ1,lsirwguhu
3,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/4TMP4al5X...,4TMP4al5XxXB9RuVx73DbB,"[{'height': 640, 'url': 'https://mosaic.scdn.c...",Mami,"{'display_name': 'michele', 'external_urls': {...",None,True,MTEsZDI1MGNhN2Y4MTU3MzYzNjRlZjdlZWJjNWRmMjJjMz...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:4TMP4al5XxXB9RuVx73DbB,lsirwguhu
4,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/1mh2iHOlx...,1mh2iHOlxk2CtxAAaGeYGU,"[{'height': 640, 'url': 'https://mosaic.scdn.c...",:)),"{'display_name': 'michele', 'external_urls': {...",None,True,MTMsZWQ5MDVmYzZkZWNhOTg4Y2U2NWVlZjIxY2IyMjUwNT...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:1mh2iHOlxk2CtxAAaGeYGU,lsirwguhu
5,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/2HKcEhC33...,2HKcEhC33EQzXeeXgYOHP8,"[{'height': 640, 'url': 'https://mosaic.scdn.c...",10 Twenty One Pilots,"{'display_name': 'michele', 'external_urls': {...",None,True,NTYsZGFhYzI4MGM3NWEyNTMwZGMzMjAzYzM1ODdkYjYyMj...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:2HKcEhC33EQzXeeXgYOHP8,lsirwguhu
6,False,,{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/1HfIKWYZQ...,1HfIKWYZQbHttbexmpwhyR,"[{'height': 640, 'url': 'https://mosaic.scdn.c...",:),"{'display_name': 'michele', 'external_urls': {...",None,True,MjIyLGZmYTgwNzVhY2VjMjRkZTM1NDY1NjZkNmI3MWVjZG...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:1HfIKWYZQbHttbexmpwhyR,lsirwguhu
7,True,"Ce soir, ça va chier.",{'spotify': 'https://open.spotify.com/playlist...,https://api.spotify.com/v1/playlists/60LLfcAgS...,60LLfcAgSHTbpiQNnhTuWT,"[{'height': None, 'url': 'https://image-cdn-ak...",Poutougal,"{'display_name': 'Loris Palma', 'external_urls...",None,False,NDUzLDU2Yzk2ZmRlNWE5MDY2YzM0YWZiMGFhMTg2N2RhMW...,{'href': 'https://api.spotify.com/v1/playlists...,playlist,spotify:playlist:60LLfcAgSHTbpiQNnhTuWT,lsirwguhu

In [8]:
all_user_playlists_tracks = pd.DataFrame()
for user in users_list.USERS:
    df_playlists_tracks = pd.DataFrame()
    for playlist_id in df_playlists[df_playlists["username"] == user.username]["id"]:
        df_current_playlist_tracks = user.get_playlist_tracks(playlist_id)
        df_playlists_tracks = pd.concat([df_playlists_tracks, df_current_playlist_tracks])
    df_playlists_tracks.to_json(os.path.join(data_path.DATA_PATH, f"{user.username}_playlists_tracks.json"), orient="records")
    all_user_playlists_tracks = pd.concat([all_user_playlists_tracks, df_playlists_tracks])
all_user_playlists_tracks

,album,artists,available_markets,disc_number,duration_ms,episode,explicit,external_ids,external_urls,href,...,instrumentalness,liveness,valence,tempo,type_features,uri_features,track_href,analysis_url,duration_ms_features,time_signature
0,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,179000,False,False,{'isrc': 'QZW9K2210189'},{'spotify': 'https://open.spotify.com/track/2h...,https://api.spotify.com/v1/tracks/2h444Cn1pbZj...,...,0.000000,0.1010,0.470,174.223,audio_features,spotify:track:2h444Cn1pbZjKPD4jbjY3E,https://api.spotify.com/v1/tracks/2h444Cn1pbZj...,https://api.spotify.com/v1/audio-analysis/2h44...,179000,3
1,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,181106,False,False,{'isrc': 'DECE72300116'},{'spotify': 'https://open.spotify.com/track/0v...,https://api.spotify.com/v1/tracks/0vuyiZejJnlg...,...,0.000000,0.2030,0.561,117.991,audio_features,spotify:track:0vuyiZejJnlgQpxy6XK7u2,https://api.spotify.com/v1/tracks/0vuyiZejJnlg...,https://api.spotify.com/v1/audio-analysis/0vuy...,181107,4
2,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,270635,False,True,{'isrc': 'ZZOPM2236812'},{'spotify': 'https://open.spotify.com/track/5B...,https://api.spotify.com/v1/tracks/5BgeAX4HuZdc...,...,0.000000,0.1810,0.506,112.176,audio_features,spotify:track:5BgeAX4HuZdcuCqmu4pIMM,https://api.spotify.com/v1/tracks/5BgeAX4HuZdc...,https://api.spotify.com/v1/audio-analysis/5Bge...,270635,4
3,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,168126,False,False,{'isrc': 'CAUM72200107'},{'spotify': 'https://open.spotify.com/track/07...,https://api.spotify.com/v1/tracks/079mntueS2KW...,...,0.000000,0.1700,0.221,119.914,audio_features,spotify:track:079mntueS2KWjxVqOHjG70,https://api.spotify.com/v1/tracks/079mntueS2KW...,https://api.spotify.com/v1/audio-analysis/079m...,168126,4
0,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,139000,False,False,{'isrc': 'TCACP1635396'},{'spotify': 'https://open.spotify.com/track/4a...,https://api.spotify.com/v1/tracks/4aDwh1E15pW1...,...,0.000000,0.0979,0.487,81.801,audio_features,spotify:track:4aDwh1E15pW1nXRxbvXqHY,https://api.spotify.com/v1/tracks/4aDwh1E15pW1...,https://api.spotify.com/v1/audio-analysis/4aDw...,139000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,211213,False,True,{'isrc': 'IT4U11700019'},{'spotify': 'https://open.spotify.com/track/07...,https://api.spotify.com/v1/tracks/07VhWcjtxG9f...,...,0.003510,0.1240,0.872,103.021,audio_features,spotify:track:07VhWcjtxG9fe1jZixSY3F,https://api.spotify.com/v1/tracks/07VhWcjtxG9f...,https://api.spotify.com/v1/audio-analysis/07Vh...,211213,4
323,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,162864,False,False,{'isrc': 'USAT21904486'},{'spotify': 'https://open.spotify.com/track/6r...,https://api.spotify.com/v1/tracks/6rVNnvyNeibt...,...,0.000005,0.1250,0.632,179.681,audio_features,spotify:track:6rVNnvyNeibts1uOqdSNIw,https://api.spotify.com/v1/tracks/6rVNnvyNeibt...,https://api.spotify.com/v1/audio-analysis/6rVN...,162864,3
324,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,143791,False,True,{'isrc': 'USAT21903333'},{'spotify': 'https://open.spotify.com/track/6d...,https://api.spotify.com/v1/tracks/6dPyzkyZwoj9...,...,0.000006,0.1370,0.243,133.983,audio_features,spotify:track:6dPyzkyZwoj9LqjQXOFdVv,https://api.spotify.com/v1/tracks/6dPyzkyZwoj9...,https://api.spotify.com/v1/audio-analysis/6dPy...,143792,4
325,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,210000,False,False,{'isrc': 'FR6V80299795'},{'spotify': 'https://open.spotify.com/track/0P...,https://api.spotify.com/v1/tracks/0Psg9I37jSzo...,...,0.000000,0.1240,0.870,120.152,audio_features,spotify:track:0Psg9I37jSzox4p7caEWCN,https://api.spotify.com/v1/tracks/0Psg9I37jSzo...,https://api.spotify.com/v1/audio-analysis/0Psg...,210000,4
326,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,235784,False,False,{'isrc': 'DESD81900185'},{'spotify': 'https://open.spotify.com/track/61...,https://api.spotify.com/v1/tracks/61AYzKQ7kvLJ...,...,0.000011,0.2840,0.674,91.961,audio_features,spotify:track:61AYzKQ7kvLJ82IFaIbRWn,https://api.spotify.com/v1/tracks/61AYzKQ7kvLJ...,https://api.spotify.com/v1/audio-analysis/61AY...,235785,4